### PR TITLE
fix(linux): ensure NvFBC capture works after multiple sessions

### LINKED ISSUE #2974: [NvFBC] Sunshine fails to load video session after 4th attempt. Error 503/-1
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Almost with 100% reliability, sessions will stop working after the 4th.

For example, I initiate a new session by starting a game (or resuming on an already running game).
Then if I close the session (CTRL+ALT+SHIFT+Q also works, you don't need to KILL the session) and resume/start a new one, repeat up to 4 times, the 4th time will invariably fail to start.

The error will be either a 503 or a -1 error on the client.

Once the issue occurs one, it will only be fixed by restarting the Sunshine process. Any number of reconnections will persist the issue.

### Expected Behavior

Sunshine should be able to start/resume an indefinite amount of sessions

(This is NOT related to parallel sessions enabled by the Channels setting; this is strictly single sessions)

### Additional Context

The clients are latest Moonlight. Occurs for both Android and PC.
Issue occurs with any app running. I believe, based on the logs, that the issue is somehow related to starting the video output.

Sunshine host is up to date Ubuntu 24.04 with latest Nvidia drivers.

This has been occurring since before 0.21.0 (this was the first version I ever used).
This has occurred across multiple versions of my OS (Ubuntu 22.10, Ubuntu 23.04, Ubuntu 23.10 and now Ubuntu 24.04).
This has occurred across multiple versions of graphic drivers.

### Host Operating System

Linux

### Operating System Version

24.04

### Architecture

64 bit

### Sunshine commit or version

v2024.805.184417

### Package

Linux - deb

### GPU Type

Nvidia

### GPU Model

RTXA2000

### GPU Driver/Mesa Version

560.31.02

### Capture Method

NvFBC (Linux)

### Config

```Shell
log_path = /home/pi/sunshine/configs/sunshine.log
nv_preset = p1
origin_web_ui_allowed = pc
credentials_file = /home/pi/sunshine/configs/sunshine_state.json
nvenc_spatial_aq = enabled
file_apps = /home/pi/sunshine/configs/apps.json
resolutions = [
    1440x900
]
min_log_level = 1
file_state = /home/pi/sunshine/configs/sunshine_state.json
encoder = nvenc
nvenc_preset = 7
fps = [60]
nv_rc = vbr
capture = nvfbc
native_pen_touch = disabled
channels = 3
sunshine_name = Pi
global_prep_cmd = [{"do":"","undo":""}]
high_resolution_scrolling = disabled
nvenc_twopass = full_res
```

### Apps

_No response_

### Relevant log output

```shell
[2024:08:07:10:13:21]: Debug: Initialized new control stream session by connect data match [v2]
[2024:08:07:10:13:21]: Debug: Control local address [192.168.0.107]
[2024:08:07:10:13:21]: Debug: Control peer address [192.168.0.215:27096]
[2024:08:07:10:13:21]: Info: CLIENT CONNECTED
[2024:08:07:10:13:21]: Debug: type [IDX_REQUEST_IDR_FRAME]
[2024:08:07:10:13:21]: Debug: type [IDX_START_B]
[2024:08:07:10:13:21]: Debug: System tray loop
[2024:08:07:10:13:21]: Debug: RAISE: 192.168.0.215:55402 :: VIDEO
[2024:08:07:10:13:21]: Debug: Received ping [v2] from 192.168.0.215:55402 [0100000042344534374444323846323841453332]
[2024:08:07:10:13:21]: Debug: Start capturing Video
[2024:08:07:10:13:21]: Debug: System tray loop
[2024:08:07:10:13:21]: Debug: --begin relative mouse move packet--
deltaX [1]
deltaY [1]
--end relative mouse move packet--
[2024:08:07:10:13:21]: Debug: --begin relative mouse move packet--
deltaX [-1]
deltaY [-1]
--end relative mouse move packet--
[2024:08:07:10:13:21]: Info: Found [1] outputs
[2024:08:07:10:13:21]: Info: Virtual Desktop: 1440x900
[2024:08:07:10:13:21]: Info: XrandR: available
[2024:08:07:10:13:21]: Info: -- Output --
[2024:08:07:10:13:21]: Debug:   ID: 540
[2024:08:07:10:13:21]: Debug:   Name: DP-0
[2024:08:07:10:13:21]: Info:   Resolution: 1440x900
[2024:08:07:10:13:21]: Info:   Offset: 0x0
[2024:08:07:10:13:21]: Info: Screencasting with NvFBC
[2024:08:07:10:13:21]: Info: SDR color coding [Rec. 601]
[2024:08:07:10:13:21]: Info: Color depth: 8-bit
[2024:08:07:10:13:21]: Info: Color range: [MPEG]
[2024:08:07:10:13:21]: Debug: [hevc_nvenc @ 0x71f71c043400] Loaded Nvenc version 12.2
[2024:08:07:10:13:21]: Debug: [hevc_nvenc @ 0x71f71c043400] Nvenc initialized successfully
[2024:08:07:10:13:21]: Debug: Sent HDR mode: false
[2024:08:07:10:13:21]: Debug: RAISE: 192.168.0.215:55400 :: AUDIO
[2024:08:07:10:13:21]: Debug: Received ping [v2] from 192.168.0.215:55400 [0200000042344534374444323846323841453332]
[2024:08:07:10:13:21]: Debug: Start capturing Audio
[2024:08:07:10:13:21]: Debug: Connecting to pulseaudio
[2024:08:07:10:13:21]: Debug: null-sink args: rate=48000 sink_name=sink-sunshine-stereo format=float channels=2 channel_map=front-left,front-right sink_properties=device.description=sink-sunshine-stereo
[2024:08:07:10:13:21]: Debug: null-sink args: rate=48000 sink_name=sink-sunshine-surround51 format=float channels=6 channel_map=front-left,front-right,front-center,lfe,rear-left,rear-right sink_properties=device.description=sink-sunshine-surround51
[2024:08:07:10:13:21]: Debug: null-sink args: rate=48000 sink_name=sink-sunshine-surround71 format=float channels=8 channel_map=front-left,front-right,front-center,lfe,rear-left,rear-right,side-left,side-right sink_properties=device.description=sink-sunshine-surround71
[2024:08:07:10:13:21]: Info: Setting default sink to: [sink-sunshine-stereo]
[2024:08:07:10:13:21]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2024:08:07:10:13:21]: Info: Opus initialized: 48 kHz, 2 channels, 512 kbps (total), LOWDELAY
[2024:08:07:10:13:21]: Debug: Minimum frame time set to 100ms, based on min fps factor of 1.
[2024:08:07:10:13:21]: Debug: Frame 1: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2024:08:07:10:13:21]: Debug: type [IDX_REQUEST_IDR_FRAME]
[2024:08:07:10:13:21]: Debug: Frame 4: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2024:08:07:10:13:28]: Debug: --begin mouse button packet--
action [00000008]
button [01]
--end mouse button packet--
[2024:08:07:10:13:28]: Debug: --begin mouse button packet--
action [00000009]
button [01]
--end mouse button packet--
[2024:08:07:10:13:29]: Debug: --begin relative mouse move packet--
deltaX [5]
deltaY [2]
--end relative mouse move packet--
[2024:08:07:10:13:30]: Debug: --begin mouse button packet--
action [00000009]
button [01]
--end mouse button packet--
[2024:08:07:10:13:30]: Info: App exited with code [0]
[2024:08:07:10:13:30]: Debug: System tray loop
[2024:08:07:10:13:30]: Debug: System tray loop
[2024:08:07:10:13:30]: Info: Process terminated
[2024:08:07:10:13:30]: Debug: System tray loop
[2024:08:07:10:13:30]: Debug: System tray loop
[2024:08:07:10:13:30]: Debug: System tray loop
[2024:08:07:10:13:30]: Info: Setting default sink to: [auto_null]
[2024:08:07:10:13:30]: Error: Couldn't set default-sink [auto_null]: No such entity
[2024:08:07:10:13:30]: Debug: Pulseadio context terminated
[2024:08:07:10:13:30]: Debug: System tray loop
[2024:08:07:10:13:30]: Debug: System tray loop
[2024:08:07:10:13:31]: Debug: [hevc_nvenc @ 0x71f71c043400] Nvenc unloaded
[2024:08:07:10:13:31]: Error: Couldn't release NvFBC context from current thread: 
[2024:08:07:10:13:31]: Debug: Waiting for video to end...
[2024:08:07:10:13:31]: Debug: Waiting for audio to end...
[2024:08:07:10:13:31]: Debug: Waiting for control to end...
[2024:08:07:10:13:31]: Debug: Resetting Input...
[2024:08:07:10:13:31]: Debug: Session ended
[2024:08:07:10:13:31]: Debug: Waiting for main listening thread to end...
[2024:08:07:10:13:31]: Debug: Waiting for main video thread to end...
[2024:08:07:10:13:31]: Debug: Waiting for main audio thread to end...
[2024:08:07:10:13:31]: Debug: Waiting for main control thread to end...
[2024:08:07:10:13:31]: Debug: All broadcasting threads ended
[2024:08:07:10:13:31]: Debug: System tray loop
[2024:08:07:10:13:31]: Debug: System tray loop
[2024:08:07:10:13:31]: Debug: System tray loop
[2024:08:07:10:13:31]: Debug: System tray loop
[2024:08:07:10:13:31]: Debug: System tray loop
[2024:08:07:10:13:31]: Debug: TUNNEL :: NONE
[2024:08:07:10:13:31]: Debug: METHOD :: GET
[2024:08:07:10:13:31]: Debug: DESTINATION :: /serverinfo
[2024:08:07:10:13:31]: Debug: User-Agent -- Mozilla/5.0
[2024:08:07:10:13:31]: Debug: Accept-Language -- en-150,*
[2024:08:07:10:13:31]: Debug: Accept-Encoding -- gzip, deflate
[2024:08:07:10:13:31]: Debug: Connection -- Keep-Alive
[2024:08:07:10:13:31]: Debug: Host -- 192.168.0.107:1612
[2024:08:07:10:13:31]: Debug:  [--] 
[2024:08:07:10:13:31]: Debug: uuid -- 47727e6176b344a4895237a5db3bb83d
[2024:08:07:10:13:31]: Debug: uniqueid -- 0123456789ABCDEF
[2024:08:07:10:13:31]: Debug:  [--] 
[2024:08:07:10:13:31]: Debug: /CN=NVIDIA GameStream Client -- verified
[2024:08:07:10:13:31]: Debug: TUNNEL :: HTTPS
[2024:08:07:10:13:31]: Debug: METHOD :: GET
[2024:08:07:10:13:31]: Debug: DESTINATION :: /serverinfo
[2024:08:07:10:13:31]: Debug: User-Agent -- Mozilla/5.0
[2024:08:07:10:13:31]: Debug: Accept-Language -- en-150,*
[2024:08:07:10:13:31]: Debug: Accept-Encoding -- gzip, deflate
[2024:08:07:10:13:31]: Debug: Connection -- Keep-Alive
[2024:08:07:10:13:31]: Debug: Host -- 192.168.0.107:47984
[2024:08:07:10:13:31]: Debug:  [--] 
[2024:08:07:10:13:31]: Debug: uuid -- ad4558ee33574d0799ea1660b2a8de45
[2024:08:07:10:13:31]: Debug: uniqueid -- 0123456789ABCDEF
[2024:08:07:10:13:31]: Debug:  [--] 
[2024:08:07:10:13:31]: Debug: /CN=NVIDIA GameStream Client -- verified
[2024:08:07:10:13:31]: Debug: TUNNEL :: HTTPS
[2024:08:07:10:13:31]: Debug: METHOD :: GET
[2024:08:07:10:13:31]: Debug: DESTINATION :: /applist
[2024:08:07:10:13:31]: Debug: User-Agent -- Mozilla/5.0
[2024:08:07:10:13:31]: Debug: Accept-Language -- en-150,*
[2024:08:07:10:13:31]: Debug: Accept-Encoding -- gzip, deflate
[2024:08:07:10:13:31]: Debug: Connection -- Keep-Alive
[2024:08:07:10:13:31]: Debug: Host -- 192.168.0.107:47984
[2024:08:07:10:13:31]: Debug:  [--] 
[2024:08:07:10:13:31]: Debug: uuid -- 2f2c4a88d53e4524862daa1db7412d84
[2024:08:07:10:13:31]: Debug: uniqueid -- 0123456789ABCDEF
[2024:08:07:10:13:31]: Debug:  [--] 
[2024:08:07:10:13:34]: Debug: TUNNEL :: NONE
[2024:08:07:10:13:34]: Debug: METHOD :: GET
[2024:08:07:10:13:34]: Debug: DESTINATION :: /serverinfo
[2024:08:07:10:13:34]: Debug: User-Agent -- Mozilla/5.0
[2024:08:07:10:13:34]: Debug: Accept-Language -- en-150,*
[2024:08:07:10:13:34]: Debug: Accept-Encoding -- gzip, deflate
[2024:08:07:10:13:34]: Debug: Connection -- Keep-Alive
[2024:08:07:10:13:34]: Debug: Host -- 192.168.0.107:1612
[2024:08:07:10:13:34]: Debug:  [--] 
[2024:08:07:10:13:34]: Debug: uuid -- 0acabca533a24409ad0a2cd3555744ad
[2024:08:07:10:13:34]: Debug: uniqueid -- 0123456789ABCDEF
[2024:08:07:10:13:34]: Debug:  [--] 
[2024:08:07:10:13:34]: Debug: /CN=NVIDIA GameStream Client -- verified
[2024:08:07:10:13:34]: Debug: TUNNEL :: HTTPS
[2024:08:07:10:13:34]: Debug: METHOD :: GET
[2024:08:07:10:13:34]: Debug: DESTINATION :: /serverinfo
[2024:08:07:10:13:34]: Debug: User-Agent -- Mozilla/5.0
[2024:08:07:10:13:34]: Debug: Accept-Language -- en-150,*
[2024:08:07:10:13:34]: Debug: Accept-Encoding -- gzip, deflate
[2024:08:07:10:13:34]: Debug: Connection -- Keep-Alive
[2024:08:07:10:13:34]: Debug: Host -- 192.168.0.107:47984
[2024:08:07:10:13:34]: Debug:  [--] 
[2024:08:07:10:13:34]: Debug: uuid -- 4ebdf66349684cb9957464d5731f82e0
[2024:08:07:10:13:34]: Debug: uniqueid -- 0123456789ABCDEF
[2024:08:07:10:13:34]: Debug:  [--] 
[2024:08:07:10:13:37]: Debug: /CN=NVIDIA GameStream Client -- verified
[2024:08:07:10:13:37]: Debug: TUNNEL :: HTTPS
[2024:08:07:10:13:37]: Debug: METHOD :: GET
[2024:08:07:10:13:37]: Debug: DESTINATION :: /launch
[2024:08:07:10:13:37]: Debug: User-Agent -- Mozilla/5.0
[2024:08:07:10:13:37]: Debug: Accept-Language -- en-150,*
[2024:08:07:10:13:37]: Debug: Accept-Encoding -- gzip, deflate
[2024:08:07:10:13:37]: Debug: Connection -- Keep-Alive
[2024:08:07:10:13:37]: Debug: Host -- 192.168.0.107:47984
[2024:08:07:10:13:37]: Debug:  [--] 
[2024:08:07:10:13:37]: Debug: uniqueid -- 0123456789ABCDEF
[2024:08:07:10:13:37]: Debug: additionalStates -- 1
[2024:08:07:10:13:37]: Debug: uuid -- bf823982037d43be9e50fde00a5fda99
[2024:08:07:10:13:37]: Debug: appid -- 348528904
[2024:08:07:10:13:37]: Debug: mode -- 3240x2160x60
[2024:08:07:10:13:37]: Debug: sops -- 0
[2024:08:07:10:13:37]: Debug: rikey -- db66eaf5429a2b2ad961fd3f4cf2fb46
[2024:08:07:10:13:37]: Debug: surroundAudioInfo -- 196610
[2024:08:07:10:13:37]: Debug: rikeyid -- -1843073448
[2024:08:07:10:13:37]: Debug: remoteControllersBitmap -- 0
[2024:08:07:10:13:37]: Debug: corever -- 1
[2024:08:07:10:13:37]: Debug: gcmap -- 0
[2024:08:07:10:13:37]: Debug: localAudioPlayMode -- 0
[2024:08:07:10:13:37]: Debug: gcpersist -- 0
[2024:08:07:10:13:37]: Debug:  [--] 
[2024:08:07:10:13:37]: Info: Trying encoder [nvenc]
[2024:08:07:10:13:37]: Info: Screencasting with NvFBC
[2024:08:07:10:13:38]: Debug: TUNNEL :: NONE
[2024:08:07:10:13:38]: Debug: METHOD :: GET
[2024:08:07:10:13:38]: Debug: DESTINATION :: /serverinfo
[2024:08:07:10:13:38]: Debug: User-Agent -- Mozilla/5.0
[2024:08:07:10:13:38]: Debug: Accept-Language -- en-150,*
[2024:08:07:10:13:38]: Debug: Accept-Encoding -- gzip, deflate
[2024:08:07:10:13:38]: Debug: Connection -- Keep-Alive
[2024:08:07:10:13:38]: Debug: Host -- 192.168.0.107:1612
[2024:08:07:10:13:38]: Debug:  [--] 
[2024:08:07:10:13:38]: Debug: uuid -- 9804b443fcaf4b68a780f91796b466ad
[2024:08:07:10:13:38]: Debug: uniqueid -- 0123456789ABCDEF
[2024:08:07:10:13:38]: Debug:  [--] 
[2024:08:07:10:13:38]: Info: SDR color coding [Rec. 601]
[2024:08:07:10:13:38]: Info: Color depth: 8-bit
[2024:08:07:10:13:38]: Info: Color range: [JPEG]
[2024:08:07:10:13:38]: Debug: [h264_nvenc @ 0x71f7187a6a80] Loaded Nvenc version 12.2
[2024:08:07:10:13:38]: Debug: [h264_nvenc @ 0x71f7187a6a80] Nvenc initialized successfully
[2024:08:07:10:13:38]: Debug: Frame 1: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2024:08:07:10:13:38]: Debug: [h264_nvenc @ 0x71f7187a6a80] Nvenc unloaded
[2024:08:07:10:13:38]: Info: SDR color coding [Rec. 601]
[2024:08:07:10:13:38]: Info: Color depth: 8-bit
[2024:08:07:10:13:38]: Info: Color range: [JPEG]
[2024:08:07:10:13:38]: Debug: [hevc_nvenc @ 0x71f7187a6a80] Loaded Nvenc version 12.2
[2024:08:07:10:13:38]: Debug: [hevc_nvenc @ 0x71f7187a6a80] Nvenc initialized successfully
[2024:08:07:10:13:38]: Debug: Frame 1: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2024:08:07:10:13:38]: Debug: [hevc_nvenc @ 0x71f7187a6a80] Nvenc unloaded
[2024:08:07:10:13:38]: Error: Couldn't destroy session handle: The context is not bound
[2024:08:07:10:13:38]: Info: Screencasting with NvFBC
[2024:08:07:10:13:38]: Info: SDR color coding [Rec. 709]
[2024:08:07:10:13:38]: Info: Color depth: 10-bit
[2024:08:07:10:13:38]: Info: Color range: [JPEG]
[2024:08:07:10:13:38]: Debug: [hevc_nvenc @ 0x71f7187a6a80] Loaded Nvenc version 12.2
[2024:08:07:10:13:38]: Debug: [hevc_nvenc @ 0x71f7187a6a80] Nvenc initialized successfully
[2024:08:07:10:13:38]: Error: cuda::cuda_t doesn't support any format other than AV_PIX_FMT_NV12
[2024:08:07:10:13:39]: Debug: [hevc_nvenc @ 0x71f7187a6a80] Nvenc unloaded
[2024:08:07:10:13:39]: Error: Couldn't destroy session handle: The context is not bound
[2024:08:07:10:13:39]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:08:07:10:13:39]: Info: 
[2024:08:07:10:13:39]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:08:07:10:13:39]: Info: 
[2024:08:07:10:13:39]: Debug: ------  h264 ------
[2024:08:07:10:13:39]: Debug: PASSED: supported
[2024:08:07:10:13:39]: Debug: REF_FRAMES_RESTRICT: supported
[2024:08:07:10:13:39]: Debug: CBR: supported
[2024:08:07:10:13:39]: Debug: DYNAMIC_RANGE: unsupported
[2024:08:07:10:13:39]: Debug: VUI_PARAMETERS: supported
[2024:08:07:10:13:39]: Debug: -------------------
[2024:08:07:10:13:39]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2024:08:07:10:13:39]: Debug: ------  hevc ------
[2024:08:07:10:13:39]: Debug: PASSED: supported
[2024:08:07:10:13:39]: Debug: REF_FRAMES_RESTRICT: supported
[2024:08:07:10:13:39]: Debug: CBR: supported
[2024:08:07:10:13:39]: Debug: DYNAMIC_RANGE: unsupported
[2024:08:07:10:13:39]: Debug: VUI_PARAMETERS: supported
[2024:08:07:10:13:39]: Debug: -------------------
[2024:08:07:10:13:39]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2024:08:07:10:13:39]: Info: Executing: [/home/pi/secondDisk/Games/Proton/GE-Proton9-11/proton run Heroes3HD.exe] in ["/home/pi/secondDisk/Games/Proton/protonData/pfx/drive_c/games/Heroes of Might and Magic III"]
[2024:08:07:10:13:39]: Debug: /CN=NVIDIA GameStream Client -- verified
[2024:08:07:10:13:39]: Debug: TUNNEL :: HTTPS
[2024:08:07:10:13:39]: Debug: METHOD :: GET
[2024:08:07:10:13:39]: Debug: DESTINATION :: /serverinfo
[2024:08:07:10:13:39]: Debug: User-Agent -- Mozilla/5.0
[2024:08:07:10:13:39]: Debug: Accept-Language -- en-150,*
[2024:08:07:10:13:39]: Debug: Accept-Encoding -- gzip, deflate
[2024:08:07:10:13:39]: Debug: Connection -- Keep-Alive
[2024:08:07:10:13:39]: Debug: Host -- 192.168.0.107:47984
[2024:08:07:10:13:39]: Debug:  [--] 
[2024:08:07:10:13:39]: Debug: uuid -- d261f51697e9458d843435cc4a1c9e22
[2024:08:07:10:13:39]: Debug: uniqueid -- 0123456789ABCDEF
[2024:08:07:10:13:39]: Debug:  [--] 
[2024:08:07:10:13:39]: Debug: handle_read_encrypted_header(): Handle read of size: 24 bytes
[2024:08:07:10:13:39]: Debug: handle_read_encrypted(): Handle read of size: 104 bytes
[2024:08:07:10:13:39]: Debug: type [REQUEST]
[2024:08:07:10:13:39]: Debug: sequence number [1]
[2024:08:07:10:13:39]: Debug: protocol :: RTSP/1.0
[2024:08:07:10:13:39]: Debug: payload :: 
[2024:08:07:10:13:39]: Debug: command :: OPTIONS
[2024:08:07:10:13:39]: Debug: target :: rtspenc://192.168.0.107:48010
[2024:08:07:10:13:39]: Debug: CSeq :: 1
[2024:08:07:10:13:39]: Debug: X-GS-ClientVersion :: 14
[2024:08:07:10:13:39]: Debug: Host :: 192.168.0.107
[2024:08:07:10:13:39]: Debug: ---Begin MessageBuffer---
OPTIONS
---End MessageBuffer---
[2024:08:07:10:13:39]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 1



---End Response---
[2024:08:07:10:13:39]: Debug: handle_read_encrypted_header(): Handle read of size: 24 bytes
[2024:08:07:10:13:39]: Debug: handle_read_encrypted(): Handle read of size: 180 bytes
[2024:08:07:10:13:39]: Debug: type [REQUEST]
[2024:08:07:10:13:39]: Debug: sequence number [2]
[2024:08:07:10:13:39]: Debug: protocol :: RTSP/1.0
[2024:08:07:10:13:39]: Debug: payload :: 
[2024:08:07:10:13:39]: Debug: command :: DESCRIBE
[2024:08:07:10:13:39]: Debug: target :: rtspenc://192.168.0.107:48010
[2024:08:07:10:13:39]: Debug: CSeq :: 2
[2024:08:07:10:13:39]: Debug: X-GS-ClientVersion :: 14
[2024:08:07:10:13:39]: Debug: Host :: 192.168.0.107
[2024:08:07:10:13:39]: Debug: Accept :: application/sdp
[2024:08:07:10:13:39]: Debug: If-Modified-Since :: Thu, 01 Jan 1970 00:00:00 GMT
[2024:08:07:10:13:39]: Debug: ---Begin MessageBuffer---
DESCRIBE
---End MessageBuffer---
[2024:08:07:10:13:39]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 2


a=x-ss-general.featureFlags:1
a=x-ss-general.encryptionSupported:5
a=x-ss-general.encryptionRequested:1
sprop-parameter-sets=AAAAAU
a=fmtp:97 surround-params=21101
a=fmtp:97 surround-params=21101
a=fmtp:97 surround-params=642012453
a=fmtp:97 surround-params=660012345
a=fmtp:97 surround-params=85301245367
a=fmtp:97 surround-params=88001234567

---End Response---
[2024:08:07:10:13:39]: Debug: handle_read_encrypted_header(): Handle read of size: 24 bytes
[2024:08:07:10:13:39]: Debug: handle_read_encrypted(): Handle read of size: 189 bytes
[2024:08:07:10:13:39]: Debug: type [REQUEST]
[2024:08:07:10:13:39]: Debug: sequence number [3]
[2024:08:07:10:13:39]: Debug: protocol :: RTSP/1.0
[2024:08:07:10:13:39]: Debug: payload :: 
[2024:08:07:10:13:39]: Debug: command :: SETUP
[2024:08:07:10:13:39]: Debug: target :: streamid=audio/0/0
[2024:08:07:10:13:39]: Debug: CSeq :: 3
[2024:08:07:10:13:39]: Debug: X-GS-ClientVersion :: 14
[2024:08:07:10:13:39]: Debug: Host :: 192.168.0.107
[2024:08:07:10:13:39]: Debug: Transport :: unicast;X-GS-ClientPort=50000-50001
[2024:08:07:10:13:39]: Debug: If-Modified-Since :: Thu, 01 Jan 1970 00:00:00 GMT
[2024:08:07:10:13:39]: Debug: ---Begin MessageBuffer---
SETUP
---End MessageBuffer---
[2024:08:07:10:13:39]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 3
Session: DEADBEEFCAFE;timeout = 90
Transport: server_port=48000
X-SS-Ping-Payload: A89AACB5A4D63009



---End Response---
[2024:08:07:10:13:39]: Debug: handle_read_encrypted_header(): Handle read of size: 24 bytes
[2024:08:07:10:13:39]: Debug: handle_read_encrypted(): Handle read of size: 212 bytes
[2024:08:07:10:13:39]: Debug: type [REQUEST]
[2024:08:07:10:13:39]: Debug: sequence number [4]
[2024:08:07:10:13:39]: Debug: protocol :: RTSP/1.0
[2024:08:07:10:13:39]: Debug: payload :: 
[2024:08:07:10:13:39]: Debug: command :: SETUP
[2024:08:07:10:13:39]: Debug: target :: streamid=video/0/0
[2024:08:07:10:13:39]: Debug: CSeq :: 4
[2024:08:07:10:13:39]: Debug: X-GS-ClientVersion :: 14
[2024:08:07:10:13:39]: Debug: Host :: 192.168.0.107
[2024:08:07:10:13:39]: Debug: Session :: DEADBEEFCAFE
[2024:08:07:10:13:39]: Debug: Transport :: unicast;X-GS-ClientPort=50000-50001
[2024:08:07:10:13:39]: Debug: If-Modified-Since :: Thu, 01 Jan 1970 00:00:00 GMT
[2024:08:07:10:13:39]: Debug: ---Begin MessageBuffer---
SETUP
---End MessageBuffer---
[2024:08:07:10:13:39]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 4
Session: DEADBEEFCAFE;timeout = 90
Transport: server_port=47998
X-SS-Ping-Payload: A89AACB5A4D63009



---End Response---
[2024:08:07:10:13:39]: Debug: handle_read_encrypted_header(): Handle read of size: 24 bytes
[2024:08:07:10:13:39]: Debug: handle_read_encrypted(): Handle read of size: 215 bytes
[2024:08:07:10:13:39]: Debug: type [REQUEST]
[2024:08:07:10:13:39]: Debug: sequence number [5]
[2024:08:07:10:13:39]: Debug: protocol :: RTSP/1.0
[2024:08:07:10:13:39]: Debug: payload :: 
[2024:08:07:10:13:39]: Debug: command :: SETUP
[2024:08:07:10:13:39]: Debug: target :: streamid=control/13/0
[2024:08:07:10:13:39]: Debug: CSeq :: 5
[2024:08:07:10:13:39]: Debug: X-GS-ClientVersion :: 14
[2024:08:07:10:13:39]: Debug: Host :: 192.168.0.107
[2024:08:07:10:13:39]: Debug: Session :: DEADBEEFCAFE
[2024:08:07:10:13:39]: Debug: Transport :: unicast;X-GS-ClientPort=50000-50001
[2024:08:07:10:13:39]: Debug: If-Modified-Since :: Thu, 01 Jan 1970 00:00:00 GMT
[2024:08:07:10:13:39]: Debug: ---Begin MessageBuffer---
SETUP
---End MessageBuffer---
[2024:08:07:10:13:39]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 5
Session: DEADBEEFCAFE;timeout = 90
Transport: server_port=47999
X-SS-Connect-Data: 360019478



---End Response---
[2024:08:07:10:13:39]: Debug: handle_read_encrypted_header(): Handle read of size: 24 bytes
[2024:08:07:10:13:39]: Debug: handle_read_encrypted(): Handle read of size: 1632 bytes
[2024:08:07:10:13:39]: Debug: type [REQUEST]
[2024:08:07:10:13:39]: Debug: sequence number [6]
[2024:08:07:10:13:39]: Debug: protocol :: RTSP/1.0
[2024:08:07:10:13:39]: Debug: payload :: v=0
o=android 0 14 IN IPv4 192.168.0.107
s=NVIDIA Streaming Client
a=x-ml-general.featureFlags:3 
a=x-ss-general.encryptionEnabled:5 
a=x-nv-video[0].clientViewportWd:3240 
a=x-nv-video[0].clientViewportHt:2160 
a=x-nv-video[0].maxFPS:60 
a=x-nv-video[0].packetSize:1392 
a=x-nv-video[0].rateControlMode:4 
a=x-nv-video[0].timeoutLengthMs:7000 
a=x-nv-video[0].framesWithInvalidRefThreshold:0 
a=x-nv-video[0].initialBitrateKbps:55200 
a=x-nv-video[0].initialPeakBitrateKbps:55200 
a=x-nv-vqos[0].bw.minimumBitrateKbps:55200 
a=x-nv-vqos[0].bw.maximumBitrateKbps:55200 
a=x-ml-video.configuredBitrateKbps:69000 
a=x-nv-vqos[0].fec.enable:1 
a=x-nv-vqos[0].videoQualityScoreUpdateTime:5000 
a=x-nv-vqos[0].qosTrafficType:5 
a=x-nv-aqos.qosTrafficType:4 
a=x-nv-general.featureFlags:167 
a=x-nv-general.useReliableUdp:13 
a=x-nv-vqos[0].fec.minRequiredFecPackets:2 
a=x-nv-vqos[0].bllFec.enable:0 
a=x-nv-vqos[0].drc.enable:0 
a=x-nv-general.enableRecoveryMode:0 
a=x-nv-video[0].videoEncoderSlicesPerFrame:1 
a=x-nv-clientSupportHevc:1 
a=x-nv-vqos[0].bitStreamFormat:1 
a=x-nv-video[0].dynamicRangeMode:0 
a=x-nv-video[0].maxNumReferenceFrames:0 
a=x-nv-video[0].clientRefreshRateX100:0 
a=x-nv-audio.surround.numChannels:2 
a=x-nv-audio.surround.channelMask:3 
a=x-nv-audio.surround.enable:0 
a=x-nv-audio.surround.AudioQuality:0 
a=x-nv-aqos.packetDuration:5 
a=x-nv-video[0].encoderCscMode:0 
t=0 0
m=video 47998  
[2024:08:07:10:13:39]: Debug: command :: ANNOUNCE
[2024:08:07:10:13:39]: Debug: target :: streamid=control/13/0
[2024:08:07:10:13:39]: Debug: CSeq :: 6
[2024:08:07:10:13:39]: Debug: X-GS-ClientVersion :: 14
[2024:08:07:10:13:39]: Debug: Host :: 192.168.0.107
[2024:08:07:10:13:39]: Debug: Session :: DEADBEEFCAFE
[2024:08:07:10:13:39]: Debug: Content-type :: application/sdp
[2024:08:07:10:13:39]: Debug: Content-length :: 1459
[2024:08:07:10:13:39]: Debug: ---Begin MessageBuffer---
ANNOUNCE
---End MessageBuffer---
[2024:08:07:10:13:39]: Debug: Found Host: 192.168.0.107
[2024:08:07:10:13:39]: Debug: Client configured bitrate is 69000 Kbps
[2024:08:07:10:13:39]: Debug: Final adjusted video encoding bitrate is 54188 Kbps
[2024:08:07:10:13:39]: Debug: Expecting incoming session connections from 192.168.0.215
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 6



---End Response---
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: handle_read_encrypted_header(): Handle read of size: 24 bytes
[2024:08:07:10:13:39]: Debug: handle_read_encrypted(): Handle read of size: 96 bytes
[2024:08:07:10:13:39]: Debug: type [REQUEST]
[2024:08:07:10:13:39]: Debug: sequence number [7]
[2024:08:07:10:13:39]: Debug: protocol :: RTSP/1.0
[2024:08:07:10:13:39]: Debug: payload :: 
[2024:08:07:10:13:39]: Debug: command :: PLAY
[2024:08:07:10:13:39]: Debug: target :: /
[2024:08:07:10:13:39]: Debug: CSeq :: 7
[2024:08:07:10:13:39]: Debug: X-GS-ClientVersion :: 14
[2024:08:07:10:13:39]: Debug: Host :: 192.168.0.107
[2024:08:07:10:13:39]: Debug: Session :: DEADBEEFCAFE
[2024:08:07:10:13:39]: Debug: ---Begin MessageBuffer---
PLAY
---End MessageBuffer---
[2024:08:07:10:13:39]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 7



---End Response---
[2024:08:07:10:13:39]: Debug: Initialized new control stream session by connect data match [v2]
[2024:08:07:10:13:39]: Debug: Control local address [192.168.0.107]
[2024:08:07:10:13:39]: Debug: Control peer address [192.168.0.215:37079]
[2024:08:07:10:13:39]: Info: CLIENT CONNECTED
[2024:08:07:10:13:39]: Debug: type [IDX_REQUEST_IDR_FRAME]
[2024:08:07:10:13:39]: Debug: type [IDX_START_B]
[2024:08:07:10:13:39]: Debug: RAISE: 192.168.0.215:55185 :: VIDEO
[2024:08:07:10:13:39]: Debug: Received ping [v2] from 192.168.0.215:55185 [0100000039303033364434413542434141393841]
[2024:08:07:10:13:39]: Debug: Start capturing Video
[2024:08:07:10:13:39]: Error: Failed to create session: 
[2024:08:07:10:13:39]: Info: Screencasting with NvFBC
[2024:08:07:10:13:39]: Error: Failed to create session: 
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: RAISE: 192.168.0.215:55183 :: AUDIO
[2024:08:07:10:13:39]: Debug: Received ping [v2] from 192.168.0.215:55183 [0200000039303033364434413542434141393841]
[2024:08:07:10:13:39]: Debug: Start capturing Audio
[2024:08:07:10:13:39]: Debug: Connecting to pulseaudio
[2024:08:07:10:13:39]: Debug: null-sink args: rate=48000 sink_name=sink-sunshine-stereo format=float channels=2 channel_map=front-left,front-right sink_properties=device.description=sink-sunshine-stereo
[2024:08:07:10:13:39]: Debug: null-sink args: rate=48000 sink_name=sink-sunshine-surround51 format=float channels=6 channel_map=front-left,front-right,front-center,lfe,rear-left,rear-right sink_properties=device.description=sink-sunshine-surround51
[2024:08:07:10:13:39]: Debug: null-sink args: rate=48000 sink_name=sink-sunshine-surround71 format=float channels=8 channel_map=front-left,front-right,front-center,lfe,rear-left,rear-right,side-left,side-right sink_properties=device.description=sink-sunshine-surround71
[2024:08:07:10:13:39]: Info: Setting default sink to: [sink-sunshine-stereo]
[2024:08:07:10:13:39]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2024:08:07:10:13:39]: Info: Opus initialized: 48 kHz, 2 channels, 512 kbps (total), LOWDELAY
[2024:08:07:10:13:39]: Info: Setting default sink to: [auto_null]
[2024:08:07:10:13:39]: Error: Couldn't set default-sink [auto_null]: No such entity
[2024:08:07:10:13:39]: Debug: Pulseadio context terminated
[2024:08:07:10:13:39]: Debug: Waiting for video to end...
[2024:08:07:10:13:39]: Debug: Waiting for audio to end...
[2024:08:07:10:13:39]: Debug: Waiting for control to end...
[2024:08:07:10:13:39]: Debug: Resetting Input...
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: Session ended
[2024:08:07:10:13:39]: Debug: Waiting for main listening thread to end...
[2024:08:07:10:13:39]: Debug: Waiting for main video thread to end...
[2024:08:07:10:13:39]: Debug: Waiting for main audio thread to end...
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: Waiting for main control thread to end...
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: All broadcasting threads ended
[2024:08:07:10:13:39]: Debug: System tray loop
[2024:08:07:10:13:39]: Debug: System tray loop
```

### PR DESCRIPTION
**Pull request by insanemal**
## Description
Please excuse the code. Basically I had a suspicion that the 'ctx_t' helper in the NvFBC code path was releasing the context early and that the exhaustion of session handles was causing the "can only reconnect 2-4 times" before it fails to reconnect bug. #2974 

So I tried a dirty workaround of binding the context before destroying the session handle. And guess what, it works. 

I also added some error logs around when it binds and unbinds the context to confirm my suspicions. 

Really the whole code needs to be reworked to ensure the ctx_t class remains in scope correctly. But that's a little above my skill level. 

### Issues Fixed or Closed

Fixes #2974 

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ns6089** [comment]
It ain't stupid if it works.
Just remove needless log lines and we should be able to merge this.

**Comment by insanemal** [comment]
Ok Done.

File: src/platform/linux/cuda.cpp [hunk 1]
```diff
@@ -574,6 +574,7 @@ namespace cuda {
         if (func.nvFBCBindContext(handle, &params)) {
           BOOST_LOG(error) << "Couldn't bind NvFBC context to current thread: " << func.nvFBCGetLastErrorStr(handle);
         }
+
```
Comment (ReenigneArcher) [inline src/platform/linux/cuda.cpp:577]:
```suggestion
```

File: src/platform/linux/cuda.cpp [hunk 2]
```diff
@@ -583,6 +584,7 @@ namespace cuda {
         if (func.nvFBCReleaseContext(handle, &params)) {
           BOOST_LOG(error) << "Couldn't release NvFBC context from current thread: " << func.nvFBCGetLastErrorStr(handle);
         }
+
```
Comment (ReenigneArcher) [inline src/platform/linux/cuda.cpp:587]:
```suggestion
```
