### PR TITLE
Intel QuickSync support for Windows

### LINKED ISSUE #698: Intel Quicksync doesn't work.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Sunshine doesn't detect hardware decoding capabilities of my Intel UHD 630 graphics card in an I7 8750h CPU and instead automatically selects software x264 encoding which is significantly worse for latency and quality.

### Expected Behavior

Hardware encoding is detected and enabled.

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

Windows 10

### Architecture

64 bit

### Sunshine commit or version

0.16.0

### Package

Windows - portable

### GPU Type

Intel

### GPU Model

Intel UHD 630

### GPU Driver/Mesa Version

31.0.15.2737

### Capture Method (Linux Only)

_No response_

### Relevant log output

```Shell
[min_threads] -- [1]
[nv_rc] -- [auto]
[hevc_mode] -- [0]
[dwmflush] -- [enabled]
[gamepad] -- [x360]
[nv_coder] -- [auto]
[min_log_level] -- [2]
[amd_quality] -- [default]
[origin_web_ui_allowed] -- [lan]
[vt_software] -- [auto]
[amd_coder] -- [auto]
[upnp] -- [disabled]
[nv_preset] -- [default]
[fps] -- [[10,30,60,90,120]]
[vt_coder] -- [auto]
[amd_rc] -- [auto]
[vt_realtime] -- [enabled]
[key_rightalt_to_key_win] -- [disabled]
[resolutions] -- [[
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600
]]
[origin_pin_allowed] -- [pc]
[2023:01:04:22:05:27]: Info: Compiling shaders...
[2023:01:04:22:05:27]: Info: Compiled shaders
[2023:01:04:22:05:27]: Warning: Couldn't setup connection to ViGEm for gamepad support [E0000001]
[2023:01:04:22:05:27]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:01:04:22:05:27]: Info: Trying encoder [nvenc]
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:01:04:22:05:27]: Info: Encoder [nvenc] failed
[2023:01:04:22:05:27]: Info: Trying encoder [amdvce]
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Could not open codec [h264_amf]: Unknown error occurred
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Could not open codec [h264_amf]: Unknown error occurred
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Could not open codec [h264_amf]: Unknown error occurred
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Could not open codec [h264_amf]: Unknown error occurred
[2023:01:04:22:05:27]: Info: Encoder [amdvce] failed
[2023:01:04:22:05:27]: Info: Trying encoder [software]
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
x[22023:01:04:22:05:27]: Info: Color coding [Rec. 709]6
4[ 2023:01:04:22:05:27]: Info: Color range: [JPEG][
error]: high profile doesn't support a bit depth of 10
[2023:01:04:22:05:27]: Error: Could not open codec [libx264]: Invalid argument
[2023:01:04:22:05:27]: Error: Failed to sync desktop to thread [0x000000AA]
[2023:01:04:22:05:27]: Info:
Device Description : Intel(R) UHD Graphics 630
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00003E9B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16305 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:04:22:05:27]: Info: Color coding [Rec. 601]
[2023:01:04:22:05:27]: Info: Color range: [JPEG]
[2023:01:04:22:05:27]: Warning: software: h264: replacing nalu prefix data
[2023:01:04:22:05:27]: Info:
[2023:01:04:22:05:27]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:01:04:22:05:27]: Info:
[2023:01:04:22:05:27]: Info: Found encoder software: [libx264]
[2023:01:04:22:05:27]: Info: Configuration UI available at [https://localhost:47990]
[2023:01:04:22:05:28]: Info: Registered Sunshine Gamestream service
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
This PR introduces Intel QuickSync support for Windows. We initially create a D3D11VA hwdevice then use that to derive a QSV context which wraps the underlying D3D11 texture pool. We map the QSV surfaces back to D3D11 textures to draw into them (handled in #736).

The QSV encoder was a little more finicky than AMF and NVENC, so more quirk flags were required to get it to behave (respecting the max frame size, but without lowering the RC buffer too much which caused the HEVC encoder to fail completely on large frames).

This does not address hybrid graphics (Optimus) scenarios. I will put up a second PR for that.

### Screenshot
image
image

### Issues Fixed or Closed
Resolves #698 
Resolves #438

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

File: src/video.cpp [hunk 1]
```diff
@@ -617,6 +696,7 @@ static std::vector<encoder_t> encoders {
   nvenc,
 #endif
 #ifdef _WIN32
+  quicksync,
```
Comment (brad-richardson) [inline src/video.cpp:699]: Should this go below the amd encoder? Otherwise I assume we would encode with quicksync if someone had an Intel igpu + amd gpu

Comment (cgutman) [reply src/video.cpp:699]: I don't think it actually matters today, since the Desktop Duplication API only supports instantiation on GPUs where the display is physically connected. `DuplicateOutput1()` would fail when called on the dGPU, since the display is connected to the iGPU and it would end up selecting QuickSync anyway.

In the future, we could add support for cross-adapter encoding, but that entails 4 copies per frame (iGPU texture -> iGPU staging texture -> dGPU staging texture -> dGPU texture) so might not have good performance anyway.
