### PR TITLE
fix(process): avoid leaking zombies and fds in detached processes

### LINKED ISSUE #3378: Detached Processes launched by sunshine end up as zombies on linux after closing them
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

When you start applications on a linux host with sunshine trough detached command with setsid like setsid steam or setsid gamescope -e -- steam steam://open/bigpicture it will not be truely detached from the parent process meaning when you try to stop the application launched by sunshine it will leave a zombie process that will keep using up pid's until you stop sunshine or restart your pc.

### Expected Behavior

Launching an application detached from the parent process should actually detach it and not keep it in a semi attached state were it then just doesn't get a response by the parent process when it tries to die (that results in a zombie process).

### Additional Context

Either something has to change how detached commands work or the parent has to actually allow the child process to die instead of leaving it in a limbo.

### Host Operating System

Linux

### Operating System Version

Fedora 41 KDE

### Architecture

amd64/x86_64

### Sunshine commit or version

v2024.1107.45727

### Package

Linux - Fedora Copr

### GPU Type

Nvidia

### GPU Model

Nividia RTX2070 Super

### GPU Driver/Mesa Version

565.57.01

### Capture Method

None

### Config

_No response_

### Apps

```json
{
    "env": {
        "PATH": "$(PATH):$(HOME)\/.local\/bin"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png",
            "exclude-global-prep-cmd": "false",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5"
        },
        {
            "name": "Low Res Desktop",
            "image-path": "desktop.png",
            "prep-cmd": [
                {
                    "do": "xrandr --output HDMI-1 --mode 1920x1080",
                    "undo": "xrandr --output HDMI-1 --mode 1920x1200"
                }
            ]
        },
        {
            "name": "MoonDeckStream",
            "output": "",
            "cmd": "",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "detached": [
                "\/home\/user\/.Appimages\/moondeckbuddy.appimage --exec MoonDeckStream"
            ],
            "image-path": "",
            "prep-cmd": [
                {
                    "do": "sh -c \"kscreen-doctor output.HDMI-A-1.mode.${SUNSHINE_CLIENT_WIDTH}x${SUNSHINE_CLIENT_HEIGHT}@${SUNSHINE_CLIENT_FPS}\"",
                    "undo": "kscreen-doctor output.HDMI-A-1.mode.1920x1080@60"
                }
            ]
        },
        {
            "name": "Steam Big Picture",
            "detached": [
                "setsid gamescope -e -- steam steam:\/\/open\/bigpicture"
            ],
            "image-path": "steam.png",
            "exclude-global-prep-cmd": "",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5"
        }
    ]
}
```

### Relevant log output

```shell
Nothing like that.
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
We were leaking detached child processes on Mac and Linux because we are expected to still wait on those with `waitpid()` in order to reap their entry in the process table. We will now do that when `proc_t::running()` is called (which happens regularly while streaming and periodically when clients poll for server info). This isn't a perfect solution but it's much better than the current situation today where all detached processes become zombies.

We were also leaking file descriptors into detached processes which could cause our log files and sockets to persist longer than expected.

### Issues Fixed or Closed
Fixes #3378

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

File: src/platform/linux/misc.cpp [hunk 1]
```diff
@@ -241,22 +241,24 @@ namespace platf {
 
   bp::child
   run_command(bool elevated, bool interactive, const std::string &cmd, boost::filesystem::path &working_dir, const bp::environment &env, FILE *file, std::error_code &ec, bp::group *group) {
+    // clang-format off
```
Comment (cgutman) [inline src/platform/linux/misc.cpp:244]: clang-format gets confused by the `boost::process` syntax and thinks `bp::std_in` is a template class `bp::std_in <bp::null, bp::std_out>`

**Review by ReenigneArcher — APPROVED** [review]
