### PR TITLE
fix(linux): fix touch misalignment for wlgrab on scaled outputs

### LINKED ISSUE #2166: Touch input is wrong on multi-monitor configurations on Linux
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Touch input is wrong when I have multiple monitors connected. No such issue on a single-monitor configuration

### Expected Behavior

_No response_

### Additional Context

[sunshine_touch_bug.webm](https://github.com/LizardByte/Sunshine/assets/9915567/3077b559-47af-412e-b98c-5908a36afaf6)

### Host Operating System

Linux

### Operating System Version

Arch Linux KDE

### Architecture

64 bit

### Sunshine commit or version

sunshine-git nightly.dev.r214.g032680c-1

### Package

Linux - AUR (Third Party)

### GPU Type

AMD

### GPU Model

RX 6700XT

### GPU Driver/Mesa Version

Mesa 24.0.1-arch1.1

### Capture Method (Linux Only)

KMS

### Config

```Shell
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600,
    1280x800
]
upnp = enabled
nv_preset = default
amd_quality = default
amd_rc = auto
nv_rc = auto
output_name = 2
```

### Apps

_No response_

### Relevant log output

```shell
[2024:02:23:19:29:53]: Info: Found display [wayland-0]
[2024:02:23:19:29:53]: Info: Found interface: zxdg_output_manager_v1(32) version 3
[2024:02:23:19:29:53]: Info: Found interface: wl_output(49) version 4
[2024:02:23:19:29:53]: Info: Found interface: wl_output(67) version 4
[2024:02:23:19:29:53]: Info: Found interface: wl_output(70) version 4
[2024:02:23:19:29:53]: Warning: Missing Wayland wire for wlr-export-dmabuf
[2024:02:23:19:29:53]: Info: Found display [wayland-0]
[2024:02:23:19:29:53]: Info: Found display [wayland-0]
[2024:02:23:19:29:53]: Info: Found interface: zxdg_output_manager_v1(32) version 3
[2024:02:23:19:29:53]: Info: Found interface: wl_output(49) version 4
[2024:02:23:19:29:53]: Info: Found interface: wl_output(67) version 4
[2024:02:23:19:29:53]: Info: Found interface: wl_output(70) version 4
[2024:02:23:19:29:53]: Info: Resolution: 1920x1080
[2024:02:23:19:29:53]: Info: Resolution: 1920x1080
[2024:02:23:19:29:53]: Info: Resolution: 1920x1080
[2024:02:23:19:29:53]: Info: Offset: 1920x0
[2024:02:23:19:29:53]: Info: Logical size: 1920x1080
[2024:02:23:19:29:53]: Info: Name: DP-1
[2024:02:23:19:29:53]: Info: Found monitor: ASR PG27FF1A/3394
[2024:02:23:19:29:53]: Info: Offset: 0x0
[2024:02:23:19:29:53]: Info: Logical size: 1920x1080
[2024:02:23:19:29:53]: Info: Name: DP-2
[2024:02:23:19:29:53]: Info: Found monitor: Philips Consumer Electronics Company Philips 226V4/UK81443014262
[2024:02:23:19:29:53]: Info: Offset: 3840x0
[2024:02:23:19:29:53]: Info: Logical size: 1080x1920
[2024:02:23:19:29:53]: Info: Name: HDMI-A-1
[2024:02:23:19:29:53]: Info: Found monitor: Philips Consumer Electronics Company Philips 235PL/DL41103143133
[2024:02:23:19:29:53]: Info: DP-1: ASR PG27FF1A/3394
[2024:02:23:19:29:53]: Info: DP-2: Philips Consumer Electronics Company Philips 226V4/UK81443014262
[2024:02:23:19:29:53]: Info: HDMI-A-1: Philips Consumer Electronics Company Philips 235PL/DL41103143133
[2024:02:23:19:29:53]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:02:23:19:29:53]: Info: Trying encoder [nvenc]
[2024:02:23:19:29:53]: Info: Screencasting with KMS
[2024:02:23:19:29:53]: Info: Found monitor for DRM screencasting
[2024:02:23:19:29:53]: Info: Found connector ID [113]
[2024:02:23:19:29:53]: Info: Found cursor plane [88]
[2024:02:23:19:29:53]: Warning: Attempting to use NVENC without CUDA support. Reverting back to GPU -> RAM -> GPU
[2024:02:23:19:29:53]: Info: Found monitor for DRM screencasting
[2024:02:23:19:29:53]: Info: Found connector ID [113]
[2024:02:23:19:29:53]: Info: Found cursor plane [88]
[2024:02:23:19:29:53]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:53]: Info: Color depth: 8-bit
[2024:02:23:19:29:53]: Info: Color range: [JPEG]
[2024:02:23:19:29:53]: Error: [AVHWDeviceContext @ 0x6029a7730680] Cannot load libcuda.so.1
[2024:02:23:19:29:53]: Error: [AVHWDeviceContext @ 0x6029a7730680] Could not dynamically load CUDA
[2024:02:23:19:29:53]: Error: Failed to create a CUDA device: Операция не позволена
[2024:02:23:19:29:53]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:53]: Info: Color depth: 8-bit
[2024:02:23:19:29:53]: Info: Color range: [JPEG]
[2024:02:23:19:29:53]: Error: [AVHWDeviceContext @ 0x6029a77dd780] Cannot load libcuda.so.1
[2024:02:23:19:29:53]: Error: [AVHWDeviceContext @ 0x6029a77dd780] Could not dynamically load CUDA
[2024:02:23:19:29:53]: Error: Failed to create a CUDA device: Операция не позволена
[2024:02:23:19:29:53]: Info: Encoder [nvenc] failed
[2024:02:23:19:29:53]: Info: Trying encoder [vaapi]
[2024:02:23:19:29:53]: Info: Screencasting with KMS
[2024:02:23:19:29:53]: Info: Found monitor for DRM screencasting
[2024:02:23:19:29:53]: Info: Found connector ID [113]
[2024:02:23:19:29:53]: Info: Found cursor plane [88]
[2024:02:23:19:29:53]: Info: System tray created
[2024:02:23:19:29:53]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:53]: Info: Color depth: 8-bit
[2024:02:23:19:29:53]: Info: Color range: [JPEG]
[2024:02:23:19:29:53]: Error: [h264_vaapi @ 0x6029a7683640] No usable encoding entrypoint found for profile VAProfileH264High (7).
[2024:02:23:19:29:53]: Info: Retrying with fallback configuration options for [h264_vaapi] after error: Функция не реализована
[2024:02:23:19:29:53]: Warning: [h264_vaapi @ 0x6029a77de580] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[2024:02:23:19:29:53]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:53]: Info: Color depth: 8-bit
[2024:02:23:19:29:53]: Info: Color range: [JPEG]
[2024:02:23:19:29:53]: Error: [hevc_vaapi @ 0x7430dc079f80] No usable encoding entrypoint found for profile VAProfileHEVCMain (17).
[2024:02:23:19:29:53]: Info: Retrying with fallback configuration options for [hevc_vaapi] after error: Функция не реализована
[2024:02:23:19:29:53]: Warning: [hevc_vaapi @ 0x6029a7683640] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[2024:02:23:19:29:53]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:53]: Info: Color depth: 8-bit
[2024:02:23:19:29:53]: Info: Color range: [JPEG]
[2024:02:23:19:29:53]: Error: [av1_vaapi @ 0x7430dc079f80] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:02:23:19:29:53]: Info: Retrying with fallback configuration options for [av1_vaapi] after error: Функция не реализована
[2024:02:23:19:29:53]: Error: [av1_vaapi @ 0x6029a77de580] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:02:23:19:29:53]: Error: Could not open codec [av1_vaapi]: Функция не реализована
[2024:02:23:19:29:53]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:53]: Info: Color depth: 8-bit
[2024:02:23:19:29:53]: Info: Color range: [JPEG]
[2024:02:23:19:29:53]: Error: [av1_vaapi @ 0x7430dc079f80] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:02:23:19:29:53]: Info: Retrying with fallback configuration options for [av1_vaapi] after error: Функция не реализована
[2024:02:23:19:29:53]: Error: [av1_vaapi @ 0x6029a813cbc0] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:02:23:19:29:53]: Error: Could not open codec [av1_vaapi]: Функция не реализована
[2024:02:23:19:29:53]: Info: Screencasting with KMS
[2024:02:23:19:29:53]: Info: Found monitor for DRM screencasting
[2024:02:23:19:29:53]: Info: Found connector ID [113]
[2024:02:23:19:29:53]: Info: Found cursor plane [88]
[2024:02:23:19:29:53]: Info: SDR color coding [Rec. 709]
[2024:02:23:19:29:53]: Info: Color depth: 10-bit
[2024:02:23:19:29:53]: Info: Color range: [JPEG]
[2024:02:23:19:29:53]: Error: [hevc_vaapi @ 0x6029a813cbc0] No usable encoding entrypoint found for profile VAProfileHEVCMain10 (18).
[2024:02:23:19:29:53]: Info: Retrying with fallback configuration options for [hevc_vaapi] after error: Функция не реализована
[2024:02:23:19:29:53]: Warning: [hevc_vaapi @ 0x7430dc079f80] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[2024:02:23:19:29:53]: Info: 
[2024:02:23:19:29:53]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:02:23:19:29:53]: Info: 
[2024:02:23:19:29:53]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2024:02:23:19:29:53]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2024:02:23:19:29:53]: Info: Adding avahi service Sunshine
[2024:02:23:19:29:53]: Info: Configuration UI available at [https://localhost:47990]
[2024:02:23:19:29:54]: Info: Avahi service Sunshine successfully established.
[2024:02:23:19:29:55]: Info: Completed UPnP port mappings to 192.168.88.200 via http://192.168.88.240:2828/gateway.xml
[2024:02:23:19:29:59]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:02:23:19:29:59]: Info: Trying encoder [nvenc]
[2024:02:23:19:29:59]: Info: Screencasting with KMS
[2024:02:23:19:29:59]: Info: Found monitor for DRM screencasting
[2024:02:23:19:29:59]: Info: Found connector ID [113]
[2024:02:23:19:29:59]: Info: Found cursor plane [88]
[2024:02:23:19:29:59]: Warning: Attempting to use NVENC without CUDA support. Reverting back to GPU -> RAM -> GPU
[2024:02:23:19:29:59]: Info: Found monitor for DRM screencasting
[2024:02:23:19:29:59]: Info: Found connector ID [113]
[2024:02:23:19:29:59]: Info: Found cursor plane [88]
[2024:02:23:19:29:59]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:59]: Info: Color depth: 8-bit
[2024:02:23:19:29:59]: Info: Color range: [JPEG]
[2024:02:23:19:29:59]: Error: [AVHWDeviceContext @ 0x74309c1ff240] Cannot load libcuda.so.1
[2024:02:23:19:29:59]: Error: [AVHWDeviceContext @ 0x74309c1ff240] Could not dynamically load CUDA
[2024:02:23:19:29:59]: Error: Failed to create a CUDA device: Операция не позволена
[2024:02:23:19:29:59]: Info: Encoder [nvenc] failed
[2024:02:23:19:29:59]: Info: Trying encoder [vaapi]
[2024:02:23:19:29:59]: Info: Screencasting with KMS
[2024:02:23:19:29:59]: Info: Found monitor for DRM screencasting
[2024:02:23:19:29:59]: Info: Found connector ID [113]
[2024:02:23:19:29:59]: Info: Found cursor plane [88]
[2024:02:23:19:29:59]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:59]: Info: Color depth: 8-bit
[2024:02:23:19:29:59]: Info: Color range: [JPEG]
[2024:02:23:19:29:59]: Error: [h264_vaapi @ 0x74309c2e6080] No usable encoding entrypoint found for profile VAProfileH264High (7).
[2024:02:23:19:29:59]: Info: Retrying with fallback configuration options for [h264_vaapi] after error: Функция не реализована
[2024:02:23:19:29:59]: Warning: [h264_vaapi @ 0x74309c3ce080] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[2024:02:23:19:29:59]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:59]: Info: Color depth: 8-bit
[2024:02:23:19:29:59]: Info: Color range: [JPEG]
[2024:02:23:19:29:59]: Error: [hevc_vaapi @ 0x74309c3ce080] No usable encoding entrypoint found for profile VAProfileHEVCMain (17).
[2024:02:23:19:29:59]: Info: Retrying with fallback configuration options for [hevc_vaapi] after error: Функция не реализована
[2024:02:23:19:29:59]: Warning: [hevc_vaapi @ 0x74309cc41d00] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[2024:02:23:19:29:59]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:59]: Info: Color depth: 8-bit
[2024:02:23:19:29:59]: Info: Color range: [JPEG]
[2024:02:23:19:29:59]: Error: [av1_vaapi @ 0x74309cc41d00] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:02:23:19:29:59]: Info: Retrying with fallback configuration options for [av1_vaapi] after error: Функция не реализована
[2024:02:23:19:29:59]: Error: [av1_vaapi @ 0x74309cb23c40] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:02:23:19:29:59]: Error: Could not open codec [av1_vaapi]: Функция не реализована
[2024:02:23:19:29:59]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:29:59]: Info: Color depth: 8-bit
[2024:02:23:19:29:59]: Info: Color range: [JPEG]
[2024:02:23:19:29:59]: Error: [av1_vaapi @ 0x74309cc41d00] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:02:23:19:29:59]: Info: Retrying with fallback configuration options for [av1_vaapi] after error: Функция не реализована
[2024:02:23:19:29:59]: Error: [av1_vaapi @ 0x74309c3ce080] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:02:23:19:29:59]: Error: Could not open codec [av1_vaapi]: Функция не реализована
[2024:02:23:19:29:59]: Info: Screencasting with KMS
[2024:02:23:19:29:59]: Info: Found monitor for DRM screencasting
[2024:02:23:19:29:59]: Info: Found connector ID [113]
[2024:02:23:19:29:59]: Info: Found cursor plane [88]
[2024:02:23:19:29:59]: Info: SDR color coding [Rec. 709]
[2024:02:23:19:29:59]: Info: Color depth: 10-bit
[2024:02:23:19:29:59]: Info: Color range: [JPEG]
[2024:02:23:19:29:59]: Error: [hevc_vaapi @ 0x74309c3ce080] No usable encoding entrypoint found for profile VAProfileHEVCMain10 (18).
[2024:02:23:19:29:59]: Info: Retrying with fallback configuration options for [hevc_vaapi] after error: Функция не реализована
[2024:02:23:19:29:59]: Warning: [hevc_vaapi @ 0x74309cc41d00] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[2024:02:23:19:29:59]: Info: 
[2024:02:23:19:29:59]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:02:23:19:29:59]: Info: 
[2024:02:23:19:29:59]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2024:02:23:19:29:59]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2024:02:23:19:29:59]: Info: Executing Do Cmd: [kscreen-doctor output.DP-1.mode.19]
[2024:02:23:19:29:59]: Info: Executing [Desktop]
[2024:02:23:19:30:00]: Info: CLIENT CONNECTED
[2024:02:23:19:30:00]: Info: Found display [wayland-0]
[2024:02:23:19:30:00]: Info: Found interface: zxdg_output_manager_v1(32) version 3
[2024:02:23:19:30:00]: Info: Found interface: wl_output(49) version 4
[2024:02:23:19:30:00]: Info: Found interface: wl_output(67) version 4
[2024:02:23:19:30:00]: Info: Found interface: wl_output(70) version 4
[2024:02:23:19:30:00]: Info: Resolution: 1280x800
[2024:02:23:19:30:00]: Info: Resolution: 1920x1080
[2024:02:23:19:30:00]: Info: Resolution: 1920x1080
[2024:02:23:19:30:00]: Info: Offset: 1920x0
[2024:02:23:19:30:00]: Info: Logical size: 1280x800
[2024:02:23:19:30:00]: Info: Name: DP-1
[2024:02:23:19:30:00]: Info: Found monitor: ASR PG27FF1A/3394
[2024:02:23:19:30:00]: Info: Offset: 0x0
[2024:02:23:19:30:00]: Info: Logical size: 1920x1080
[2024:02:23:19:30:00]: Info: Name: DP-2
[2024:02:23:19:30:00]: Info: Found monitor: Philips Consumer Electronics Company Philips 226V4/UK81443014262
[2024:02:23:19:30:00]: Info: Offset: 3840x0
[2024:02:23:19:30:00]: Info: Logical size: 1080x1920
[2024:02:23:19:30:00]: Info: Name: HDMI-A-1
[2024:02:23:19:30:00]: Info: Found monitor: Philips Consumer Electronics Company Philips 235PL/DL41103143133
[2024:02:23:19:30:00]: Info: DP-1: ASR PG27FF1A/3394
[2024:02:23:19:30:00]: Info: DP-2: Philips Consumer Electronics Company Philips 226V4/UK81443014262
[2024:02:23:19:30:00]: Info: HDMI-A-1: Philips Consumer Electronics Company Philips 235PL/DL41103143133
[2024:02:23:19:30:00]: Info: Screencasting with KMS
[2024:02:23:19:30:00]: Info: Found monitor for DRM screencasting
[2024:02:23:19:30:00]: Info: Found connector ID [113]
[2024:02:23:19:30:00]: Info: Found cursor plane [88]
[2024:02:23:19:30:00]: Info: SDR color coding [Rec. 601]
[2024:02:23:19:30:00]: Info: Color depth: 8-bit
[2024:02:23:19:30:00]: Info: Color range: [MPEG]
[2024:02:23:19:30:00]: Error: [hevc_vaapi @ 0x7430b42b0c00] No usable encoding entrypoint found for profile VAProfileHEVCMain (17).
[2024:02:23:19:30:00]: Info: Retrying with fallback configuration options for [hevc_vaapi] after error: Функция не реализована
[2024:02:23:19:30:00]: Warning: [hevc_vaapi @ 0x7430b4acabc0] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[2024:02:23:19:30:00]: Info: Setting default sink to: [sink-sunshine-stereo]
[2024:02:23:19:30:00]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2024:02:23:19:30:41]: Info: CLIENT DISCONNECTED
[2024:02:23:19:30:41]: Info: Setting default sink to: [alsa_output.pci-0000_06_00.0.iec958-dts-surround-51]
[2024:02:23:19:30:46]: Info: Executing Undo Cmd: [kscreen-doctor output.DP-1.mode.1]
[2024:02:23:20:01:05]: Info: Opening UI from system tray
[2024:02:23:20:01:06]: Info: Opened url [https://localhost:47990]
```

### PR DESCRIPTION
**Pull request by herboh**
## Description

PR #4607 added logical dimension tracking and `scalar_tpcoords` scaling support for the `kmsgrab` (KMS/DRM) capture backend, but my configuration (niri, multimonitor, scaled hidpi output) was still mapping input to the wrong portion of the desktop.  

This PR tries to mirror the pattern used in `kmsgrab.cpp` to `wlgrab.cpp`:
- Adds `env_logical_width` / `env_logical_height` statics to the `wl` namespace
- Sets `logical_width`, `logical_height`, `env_logical_width`, `env_logical_height` on the display object during `wlr_t::init()`

Additionally, the touch and pen passthrough functions in `input.cpp` are updated to normalize coordinates relative to the streamed monitor rather than the full desktop. 

### Issues Fixed or Closed

- Partially fixes #2166 for wlgrab

## Type of Change

- [ ] **feat**: New feature (non-breaking change which adds functionality)
- [x] **fix**: Bug fix (non-breaking change which fixes an issue)
- [ ] **docs**: Documentation only changes
- [ ] **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semicolons, etc.)
- [ ] **refactor**: Code change that neither fixes a bug nor adds a feature
- [ ] **perf**: Code change that improves performance
- [ ] **test**: Adding missing tests or correcting existing tests
- [ ] **build**: Changes that affect the build system or external dependencies
- [ ] **ci**: Changes to CI configuration files and scripts
- [ ] **chore**: Other changes that don't modify src or test files
- [ ] **revert**: Reverts a previous commit
- [ ] **BREAKING CHANGE**: Introduces a breaking change (can be combined with any type above)

## Checklist

- [x] Code follows the style guidelines of this project
- [x] Code has been self-reviewed
- [x] Code has been commented, particularly in hard-to-understand areas
- [x] Code docstring/documentation-blocks for new or existing methods/components have been added or updated
- [ ] Unit tests have been added or updated for any new or modified functionality

### AI Usage

- [ ] **None**: No AI tools were used in creating this PR
- [ ] **Light**: AI provided minor assistance (formatting, simple suggestions)
- [x] **Moderate**: AI helped with code generation or debugging specific parts
- [ ] **Heavy**: AI generated most or all of the code changes

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
@juliosanz could you review please?

**Review by juliosanz — COMMENTED** [review]
KMS still works just fine like it did in PR #4607. Changes made are in `wlgrab.cpp` and, indeed, mirror those made to `kmsgrab.cpp`.

At first glance, these changes should absolutely make things work right in `wlroots`. I don't have an installation at hand to try it myself, though. @Dregu pointed out some issues my PR had in `wlroots`, perhaps they can test it better.

**Comment by herboh** [comment]
Follow up commit to address the Sonar issues with duplication in `input.cpp`.

  - added a helper function for touch and pen to use for monitor normalization
  - removed `wlgrab.cpp` globals to instead compute local dimensions during wlgrab init
  - renamed variables `wlgrab.cpp` to avoid shadowing a class field

  No functional changes, just to better match the guidelines.

**Comment by ReenigneArcher** [comment]
> Follow up commit to address the Sonar issues with duplication in `input.cpp`.
> 
>     * added a helper function for touch and pen to use for monitor normalization
> 
>     * removed `wlgrab.cpp` globals to instead compute local dimensions during wlgrab init
> 
>     * renamed variables `wlgrab.cpp` to avoid shadowing a class field
> 
> 
> No functional changes, just to better match the guidelines.

Thank you! Really appreciate when we can get some of this code cleaned up!

**Comment by ReenigneArcher** [comment]
There's some issues building the docs:

```
Generating code for file src/home/docs/checkouts/readthedocs.org/user_builds/sunshinestream/checkouts/4665/src/input.cpp:907: error: argument 'input' of command @param is not found in the argument list of input::monitor_touch_port(const input::touch_port_t &touch_port, std::pair< float, float > &coords)
--
/home/docs/checkouts/readthedocs.org/user_builds/sunshinestream/checkouts/4665/src/input.cpp:907: error: argument 'packet' of command @param is not found in the argument list of input::monitor_touch_port(const input::touch_port_t &touch_port, std::pair< float, float > &coords)
/home/docs/checkouts/readthedocs.org/user_builds/sunshinestream/checkouts/4665/src/input.cpp:907: error: The following parameters of input::monitor_touch_port(const input::touch_port_t &touch_port, std::pair< float, float > &coords) are not documented:
parameter 'touch_port'
parameter 'coords'
```

File: src/input.cpp [hunk 1]
```diff
@@ -903,10 +903,30 @@ namespace input {
...
+
+    return platf::touch_port_t {
+      touch_port.offset_x,
+      touch_port.offset_y,
+      static_cast<int>(monitor_logical_w),
+      static_cast<int>(monitor_logical_h)
+    };
+  }
+
   void passthrough(std::shared_ptr<input_t> &input, PSS_TOUCH_PACKET packet) {
```
Comment (ReenigneArcher) [inline src/input.cpp:935]:
```suggestion

  /**
   * @brief Called to pass a touch message to the platform backend.
   * @param input The input context pointer.
   * @param packet The touch packet.
   */
  void passthrough(std::shared_ptr<input_t> &input, PSS_TOUCH_PACKET packet) {
```

I think the docs were accidentally removed from this function?

**Comment by Dregu** [comment]
> perhaps they can test it better

Well I don't use touch, but at least the things I do use, mouse on scaled wlr and kms, still seem to work fine 👍🏻

**Comment by herboh** [comment]
Should be ready for rebase/review. @ReenigneArcher 

On the remaining duplication warning: the duplication is from existing blocks I did not introduce in this PR, just touched/moved around. I can try to refactor that code if it's required to pass the checks, but I figured it was best to keep the PR simple to limit unintentional effects.

Let me know if there's anything else I can do. Thanks for the help and feedback so far.
