### PR TITLE
Fix macOS video capture backend

### LINKED ISSUE #1348: MacPort 0.20.0 and up returns segmentation fault 11
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

0.19.1 works well but after updating to 0.20.0 and nightly build. zsh returns zsh: segmentation fault sunshine and bash returns Segmentation fault: 11
it doesn't seem like a GPU issue integrated and discrete gpu returns the same error unlike #804

### Expected Behavior

_No response_

### Additional Context

_No response_

### Host Operating System

macOS

### Operating System Version

macOS 13.4 (22F66)

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

macOS - Portfile

### GPU Type

AMD

### GPU Model

Radeon Pro 555X/Intel UHD Graphics 630

### GPU Driver/Mesa Version

Latest

### Capture Method (Linux Only)

_No response_

### Config

```Shell
default
```

### Apps

_No response_

### Relevant log output

```shell
user@mac .ports % sunshine
[2023:06:03:12:42:55]: Info: Sunshine version: 0.20.0
[2023:06:03:12:42:55]: Info: system_tray() is not yet implemented for this platform.
[2023:06:03:12:42:55]: Error: No screen capture permission!
[2023:06:03:12:42:55]: Error: Please activate it in 'System Preferences' -> 'Privacy' -> 'Screen Recording'
[2023:06:03:12:42:55]: Error: Platform failed to initialize
[2023:06:03:12:42:55]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:06:03:12:42:55]: Info: Trying encoder [videotoolbox]
[2023:06:03:12:42:55]: Info: SDR color coding [Rec. 601]
[2023:06:03:12:42:55]: Info: Color range: [JPEG]

  [Restored Jun 3, 2023 at 12:43:09 PM]
Restored session: Sat Jun  3 12:43:07 +03 2023
user@mac .ports % sunshine
[2023:06:03:12:43:11]: Info: Sunshine version: 0.20.0
[2023:06:03:12:43:11]: Info: system_tray() is not yet implemented for this platform.
[2023:06:03:12:43:11]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:06:03:12:43:11]: Info: Trying encoder [videotoolbox]
[2023:06:03:12:43:11]: Info: SDR color coding [Rec. 601]
[2023:06:03:12:43:11]: Info: Color range: [JPEG]
zsh: segmentation fault  sunshine
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
This PR fixes a _ton_ of issues in the macOS video capture backend and also considerably simplifies the code. It also implements zero-copy encoding like Windows and Linux have.

Bugs fixed include:
- Use after free on startup caused by pointing the AVFrame into the av_img_t's locked CVPixelBuffer without retaining ownership of it
- Encoding fails with an invalid argument error for non-`PARALLEL_ENCODING` encoders
- Incorrect color range and color space with the VideoToolbox encoder
- Invocation of `push_captured_image_cb()` was incorrectly never reporting a new frame
- Modifying a CVPixelBuffer that we had locked with `kCVPixelBufferLock_ReadOnly`
- Captured images with a stride that was not a multiple of 32 would be completely corrupt due to incorrect stride alignment

### Issues Fixed or Closed
Fixes #1348

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

File: src/platform/macos/display.mm [hunk 1]
```diff
@@ -135,7 +135,7 @@
 
   std::shared_ptr<display_t>
   display(platf::mem_type_e hwdevice_type, const std::string &display_name, const video::config_t &config) {
-    if (hwdevice_type != platf::mem_type_e::system) {
+    if (hwdevice_type != platf::mem_type_e::system && hwdevice_type != platf::mem_type_e::videotoolbox) {
```
Comment (ns6089) [inline src/platform/macos/display.mm:138]: Do we still support `platf::mem_type_e::system`?

File: src/platform/macos/nv12_zero_device.cpp [hunk 2]
```diff
@@ -17,23 +17,19 @@ namespace platf {
...
-      av_frame->linesize[i] = CVPixelBufferGetBytesPerRowOfPlane(av_img->pixel_buffer->buf, i);
-      av_frame->data[i] = (uint8_t *) CVPixelBufferGetBaseAddressOfPlane(av_img->pixel_buffer->buf, i);
-    }
+    av_buffer_unref(&av_frame->buf[0]);
 
-    // We just set data pointers to point into our CVPixelBuffer above, so we have to hold
-    // a reference to these buffers to keep them around until the AVFrame is done using them.
-    backing_img.sample_buffer = av_img->sample_buffer;
-    backing_img.pixel_buffer = av_img->pixel_buffer;
+    av_frame->buf[0] = av_buffer_create((uint8_t *) CFRetain(av_img->pixel_buffer->buf), 0, free_buffer, NULL, 0);
```
Comment (ns6089) [inline src/platform/macos/nv12_zero_device.cpp:31]: Maybe add a couple of words why we use `av_buffer_create()` here, since we don't do it anywhere else.
I understood it as ffmpeg "smart-pointer" that will be freed in `av_frame_free()`.

File: src/platform/macos/display.mm (hunk 1 above)
Comment (cgutman) [reply src/platform/macos/display.mm:138]: Yep, the software encoder uses that.

File: src/platform/macos/nv12_zero_device.cpp (hunk 2 above)
Comment (cgutman) [reply src/platform/macos/nv12_zero_device.cpp:37]: Added a comment here.
