### PR TITLE
feat(input/linux): allow ds5 gamepads to have a fixed device mac based on controller index

### LINKED ISSUE #3404: Sunshine virtual Dualsense controller registers with new ids every new session
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

When using steam with a dualsense gamepad I've noticed that the controller settings such as adjusting the deadzone or enabling rumble weren't "saving" after exiting and re-entering a sunshine session. Upon further investigation I noticed that the steam controller configuration utility was creating new profiles for each session, as if I was using a differen't controller each time, each marked with a unique id.

Here is a listing of some of the files in `~/.steam/steam/steamapps/common/Steam Controller Configs/<user id>/config/` that were created in a short time while debugging this issue:

```
nov 16 17:23 preferences_DSef07194a5c1d.vdf
nov 16 17:21 configset_controller_ps5.vdf
nov 16 17:21 configset_DSef07194a5c1d.vdf
nov 16 17:13 preferences_DS2c96dc8a35d4.vdf
nov 16 17:13 configset_DS2c96dc8a35d4.vdf
nov 16 17:12 preferences_DS2ab093035886.vdf
nov 16 17:10 configset_DS2ab093035886.vdf
nov 16 17:08 steam_autocloud.vdf
nov 16 17:03 preferences_DS1772a2de5625.vdf
nov 16 17:01 configset_DS1772a2de5625.vdf
nov 16 16:53 preferences_DSa5324fc07c7c.vdf
nov 16 16:51 configset_DSa5324fc07c7c.vdf
```

Each set of files is clearly marked with a unique id that ideally should not change across session since it is the same controller.

By looking at the kernel logs you can cross-reference the ids present in those config file names with ones registered by hidraw/uhid (?):
```
[nov16 16:51] input: Touch passthrough as /devices/virtual/input/input84
[  +0,000115] input: Pen passthrough as /devices/virtual/input/input85
[  +0,116280] playstation 0003:054C:0CE6.000B: hidraw6: USB HID v81.11 Gamepad [Sunshine DualSense (virtual) pad] on a5:32:4f:c0:7c:7c
[  +0,000044] input: Sunshine DualSense (virtual) pad as /devices/virtual/misc/uhid/0003:054C:0CE6.000B/input/input86
[  +0,000044] input: Sunshine DualSense (virtual) pad Motion Sensors as /devices/virtual/misc/uhid/0003:054C:0CE6.000B/input/input87
[  +0,000027] input: Sunshine DualSense (virtual) pad Touchpad as /devices/virtual/misc/uhid/0003:054C:0CE6.000B/input/input88
[  +0,000098] playstation 0003:054C:0CE6.000B: Registered DualSense controller hw_version=0x01000208 fw_version=0x01000036
[nov16 17:01] input: Touch passthrough as /devices/virtual/input/input89
[  +0,000120] input: Pen passthrough as /devices/virtual/input/input90
[  +0,120389] playstation 0003:054C:0CE6.000C: hidraw6: USB HID v81.11 Gamepad [Sunshine DualSense (virtual) pad] on 17:72:a2:de:56:25
[  +0,000043] input: Sunshine DualSense (virtual) pad as /devices/virtual/misc/uhid/0003:054C:0CE6.000C/input/input91
[  +0,000040] input: Sunshine DualSense (virtual) pad Motion Sensors as /devices/virtual/misc/uhid/0003:054C:0CE6.000C/input/input92
[  +0,000031] input: Sunshine DualSense (virtual) pad Touchpad as /devices/virtual/misc/uhid/0003:054C:0CE6.000C/input/input93
[  +0,000092] playstation 0003:054C:0CE6.000C: Registered DualSense controller hw_version=0x01000208 fw_version=0x01000036
[nov16 17:10] input: Touch passthrough as /devices/virtual/input/input94
[  +0,000104] input: Pen passthrough as /devices/virtual/input/input95
[  +0,107964] playstation 0003:054C:0CE6.000D: hidraw6: USB HID v81.11 Gamepad [Sunshine DualSense (virtual) pad] on 2a:b0:93:3:58:86
[  +0,000053] input: Sunshine DualSense (virtual) pad as /devices/virtual/misc/uhid/0003:054C:0CE6.000D/input/input96
[  +0,000047] input: Sunshine DualSense (virtual) pad Motion Sensors as /devices/virtual/misc/uhid/0003:054C:0CE6.000D/input/input97
[  +0,000034] input: Sunshine DualSense (virtual) pad Touchpad as /devices/virtual/misc/uhid/0003:054C:0CE6.000D/input/input98
[  +0,000107] playstation 0003:054C:0CE6.000D: Registered DualSense controller hw_version=0x01000208 fw_version=0x01000036
[nov16 17:13] input: Touch passthrough as /devices/virtual/input/input99
[  +0,000132] input: Pen passthrough as /devices/virtual/input/input100
[  +0,105293] playstation 0003:054C:0CE6.000E: hidraw6: USB HID v81.11 Gamepad [Sunshine DualSense (virtual) pad] on 2c:96:dc:8a:35:d4
[  +0,000051] input: Sunshine DualSense (virtual) pad as /devices/virtual/misc/uhid/0003:054C:0CE6.000E/input/input101
[  +0,000058] input: Sunshine DualSense (virtual) pad Motion Sensors as /devices/virtual/misc/uhid/0003:054C:0CE6.000E/input/input102
[  +0,000047] input: Sunshine DualSense (virtual) pad Touchpad as /devices/virtual/misc/uhid/0003:054C:0CE6.000E/input/input103
[  +0,000095] playstation 0003:054C:0CE6.000E: Registered DualSense controller hw_version=0x01000208 fw_version=0x01000036
[nov16 17:21] input: Touch passthrough as /devices/virtual/input/input104
[  +0,000138] input: Pen passthrough as /devices/virtual/input/input105
[  +0,124731] playstation 0003:054C:0CE6.000F: hidraw6: USB HID v81.11 Gamepad [Sunshine DualSense (virtual) pad] on ef:7:19:4a:5c:1d
[  +0,000042] input: Sunshine DualSense (virtual) pad as /devices/virtual/misc/uhid/0003:054C:0CE6.000F/input/input106
[  +0,000039] input: Sunshine DualSense (virtual) pad Motion Sensors as /devices/virtual/misc/uhid/0003:054C:0CE6.000F/input/input107
[  +0,000029] input: Sunshine DualSense (virtual) pad Touchpad as /devices/virtual/misc/uhid/0003:054C:0CE6.000F/input/input108
[  +0,000088] playstation 0003:054C:0CE6.000F: Registered DualSense controller hw_version=0x01000208 fw_version=0x01000036
```

I've looked around in the bugtracker expecting this issue to already be reported but couldn't find any. Could this be an issue unique to my setup? Can anyone else reproduce this behavior?

### Expected Behavior

Virtual controller ids of the same real controller should remain the same across sessions.

### Additional Context

_No response_

### Host Operating System

Linux

### Operating System Version

Fedora Workstation 41

### Architecture

amd64/x86_64

### Sunshine commit or version

2024.1115.40818

### Package

Linux - Fedora Copr

### GPU Type

AMD

### GPU Model

Radeon RX 6700 XT

### GPU Driver/Mesa Version

24.2.6

### Capture Method

KMX (Linux)

### Config

_No response_

### Apps

_No response_

### Relevant log output

```shell
relevant logs in the description of the bug
```

### PR DESCRIPTION
**Pull request by Kishi85**
## Description
This PR adds an option to change how virtual DS5 controllers are created that allows them to retain controller settings (when stored based on the virtual devices MAC-Address, like Steam does) by disabling the random MAC generation and manually specifiying a private MAC-based on the connected gamepads global index. The behaviour then should be equal to the way XBox- and Switchcontrollers and DS4 on Windows are handled currently.

### Issues Fixed or Closed

- Resolves #3404

## Type of Change

- [X] **feat**: New feature (non-breaking change which adds functionality)
- [ ] **fix**: Bug fix (non-breaking change which fixes an issue)
- [ ] **docs**: Documentation only changes
- [ ] **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semicolons, etc.)
- [ ] **refactor**: Code change that neither fixes a bug nor adds a feature
- [ ] **perf**: Code change that improves performance
- [ ] **test**: Adding missing tests or correcting existing tests
- [ ] **build**: Changes that affect the build system or external dependencies
- [ ] **ci**: Changes to CI configuration files and scripts
- [ ] **chore**: Other changes that don't modify src or test files
- [ ] **revert**: Reverts a previous commit
- [ ] **BREAKING CHANGE**: Introduces a breaking change (can be combined with any type above)

## Checklist

- [X] Code follows the style guidelines of this project
- [X] Code has been self-reviewed
- [X] Code has been commented, particularly in hard-to-understand areas
- [X] Code docstring/documentation-blocks for new or existing methods/components have been added or updated
- [ ] Unit tests have been added or updated for any new or modified functionality

### AI Usage

- [X] **None**: No AI tools were used in creating this PR
- [ ] **Light**: AI provided minor assistance (formatting, simple suggestions)
- [ ] **Moderate**: AI helped with code generation or debugging specific parts
- [ ] **Heavy**: AI generated most or all of the code changes

### CODE REVIEW

File: src_assets/common/assets/web/configs/tabs/Inputs.vue [hunk 1]
```diff
@@ -89,6 +89,32 @@ const config = ref(props.config)
           </div>
         </div>
       </template>
+      <template v-if="config.gamepad === 'ds5' || (config.gamepad === 'auto' && platform === 'linux')">
```
Comment (ReenigneArcher) [inline src_assets/common/assets/web/configs/tabs/Inputs.vue:92]: This PR made me realize we have a bug in the UI.

The ds4 section above is also supposed to apply to ds5. It was created before we used ds5 on Linux. I think we can make the above section work for both ds4 and ds5 with a little bit of tweaking the `v-if` statements.

File: src/platform/linux/input/inputtino_gamepad.cpp [hunk 2]
```diff
@@ -42,8 +42,14 @@ namespace platf::gamepad {
...
-  auto create_ds5() {
-    return inputtino::PS5Joypad::create({.name = "Sunshine PS5 (virtual) pad", .vendor_id = 0x054C, .product_id = 0x0CE6, .version = 0x8111});
+  auto create_ds5(int globalIndex) {
+    if (!config::input.ds5_inputtino_randomize_mac && globalIndex >= 0 && globalIndex <= 255) {
+      // Generate private virtual device MAC based on gamepad globalIndex between 0 (00) and 255 (ff)
+      std::string device_mac = std::format("02:00:00:00:00:{:#02x}", globalIndex);
+      return inputtino::PS5Joypad::create({.name = "Sunshine PS5 (virtual) pad", .vendor_id = 0x054C, .product_id = 0x0CE6, .version = 0x8111, .device_phys=device_mac, .device_uniq=device_mac});
+    } else {
+      return inputtino::PS5Joypad::create({.name = "Sunshine PS5 (virtual) pad", .vendor_id = 0x054C, .product_id = 0x0CE6, .version = 0x8111});
+    }
```
Comment (ReenigneArcher) [inline src/platform/linux/input/inputtino_gamepad.cpp]: I haven't tested it, but could this work?

```suggestion
    std::string device_mac;

    if (!config::input.ds5_inputtino_randomize_mac && globalIndex >= 0 && globalIndex <= 255) {
      // Generate private virtual device MAC based on gamepad globalIndex between 0 (00) and 255 (ff)
      device_mac = std::format("02:00:00:00:00:{:#02x}", globalIndex);
    }
    return inputtino::PS5Joypad::create({.name = "Sunshine PS5 (virtual) pad", .vendor_id = 0x54C, .product_id = 0x0CE6, .version = 0x8111, .device_phys=device_mac, .device_uniq=device_mac});
```

If not, could we do something like this?

```suggestion
    std::string device_mac;

    std::string device_name = "Sunshine PS5 (virtual) pad";
    int device_vendor_id = 0x54C;  // or whatever type is needed
    int device_product_id = 0x0CE6;
    int device_version = 0x8111;
    if (!config::input.ds5_inputtino_randomize_mac && globalIndex >= 0 && globalIndex <= 255) {
      // Generate private virtual device MAC based on gamepad globalIndex between 0 (00) and 255 (ff)
      device_mac = std::format("02:00:00:00:00:{:#02x}", globalIndex);
return inputtino::PS5Joypad::create({.name = device_name, .vendor_id = device_vendor_id, .product_id = device_product_id, .version = device_version, .device_phys=device_mac, .device_uniq=device_mac});
    } else {
      return inputtino::PS5Joypad::create({.name = device_name, .vendor_id = device_vendor_id, .product_id = device_product_id, .version = device_version});
    }
```

Comment (Kishi85) [reply src/platform/linux/input/inputtino_gamepad.cpp]: I understand the intention behind this suggestion and have pushed a change that should work (can't test this until probably next week)  from what inputtino's source contains for device_phys and device_uniq. Maybe @ABeltramo could add to this if necessary?

File: src_assets/common/assets/web/configs/tabs/Inputs.vue (hunk 1 above)
Comment (Kishi85) [reply src_assets/common/assets/web/configs/tabs/Inputs.vue:92]: I've noted that as well and could probably fix that here but I'm not sure if this would be better done in a separate PR.

File: src/platform/linux/input/inputtino_gamepad.cpp (hunk 2 above)
Comment (ReenigneArcher) [reply src/platform/linux/input/inputtino_gamepad.cpp]: Cool, assuming it works I'm good with the change you made. Thanks!

File: src_assets/common/assets/web/configs/tabs/Inputs.vue (hunk 1 above)
Comment (ReenigneArcher) [reply src_assets/common/assets/web/configs/tabs/Inputs.vue:92]: I can fix in a separate PR, no problem.

Comment (ReenigneArcher) [reply src_assets/common/assets/web/configs/tabs/Inputs.vue:92]: My comment was incorrect because I can't find any reference to `ds4_back_as_touchpad_click` in inputtino for ds5, so I guess disregard my comment.

Comment (Kishi85) [reply src_assets/common/assets/web/configs/tabs/Inputs.vue:92]: > My comment was incorrect because I can't find any reference to `ds4_back_as_touchpad_click` in inputtino for ds5, so I guess disregard my comment.

Your comment is correct but the options used are ```motion_as_ds4``` (Line 70) and ```touchpad_as_ds4``` (Line 73) for the gamepad type autodetection part, so at least those should be shown for DS4 and DS5 but IMHO this should be done in a separate PR.

**Comment by Kishi85** [comment]
I've taken the time to test this a bit today and after removing the hex base prefix it is working as intended but the current static mac prefix is not working with Steam the way it should (probably because it is classed as a private mac). I'll do some further testing and probably have to update the used prefix before this can be merged for the desired effect.

EDIT: Further testing shows that with randomized MAC by inputtino the Steam preferences filename matches the generated MAC but with the statically created one it does not work and steam randomizes the config. Could this be a weird string formatting problem?

**Comment by ABeltramo** [comment]
Thanks for working on this, the PR looks good!  
I've tested this locally and I think I see where the issue is: inputtino always [generates a random MAC address](https://github.com/games-on-whales/inputtino/blob/83cf70ef33196a2a022671ccf8a686fc8f67ae8e/src/uhid/joypad_ps5.cpp#L219-L236) and that will most likely mess up the matching.  

You can easily check the output `HID_PHYS` and `HID_UNIQ` using
```bash
udevadm monitor -u -p
```
and hot-plugging the device during a stream.  

As a side note, my original comment was kind of wrong.. `PHYS` is just the "physical path" of the device in the system, such as the USB port or Bluetooth connection. It's most likely not being used for matching, so we can definitely leave that one out. Not sure if `HID_PHYS` is generated based on a combination of things (including the MAC address?), I'll have to test it better.

I'm going to add something in inputtino that controls the MAC address generation, that's most likely the only thing needed to fix this..

**Comment by Kishi85** [comment]
> Thanks for working on this, the PR looks good! I've tested this locally and I think I see where the issue is: inputtino always [generates a random MAC address](https://github.com/games-on-whales/inputtino/blob/83cf70ef33196a2a022671ccf8a686fc8f67ae8e/src/uhid/joypad_ps5.cpp#L219-L236) and that will most likely mess up the matching.
> 
> You can easily check the output `HID_PHYS` and `HID_UNIQ` using
> 
> ```shell
> udevadm monitor -u -p
> ```
> 
> and hot-plugging the device during a stream.
> 
> As a side note, my original comment was kind of wrong.. `PHYS` is just the "physical path" of the device in the system, such as the USB port or Bluetooth connection. It's most likely not being used for matching, so we can definitely leave that one out. Not sure if `HID_PHYS` is generated based on a combination of things (including the MAC address?), I'll have to test it better.
> 
> I'm going to add something in inputtino that controls the MAC address generation, that's most likely the only thing needed to fix this..

That sounds good as it would simplify things for use-cases like this. You could probably just use the value in device_uniq for the MAC-Address as long as it is valid.

I've seen that the generated mac is also used [here](https://github.com/games-on-whales/inputtino/blob/83cf70ef33196a2a022671ccf8a686fc8f67ae8e/src/uhid/joypad_ps5.cpp#L327) and for that call it can't be specified manually.  Maybe thats the main culprit?

EDIT: It's used throught the PS5Joypad-Implementation so being able to specify a value upon creation seems to be the only logical way

**Comment by Kishi85** [comment]
Can confirm that this requires the already mentioned changes to MAC handling in inputtino to work as intended. @ABeltramo I'll keep a look out on the fix on your side and adapt this PR if necessary.

To test this i did a rather quick hack on inputtino that parses back the mac from device_uniq to joypad._state before calling UHID create2 and then it is finally working in Steam. Here's the patch if anybody wants to try it:
```patch
diff -ruN a/third-party/inputtino/src/uhid/joypad_ps5.cpp sunshine/third-party/inputtino/src/uhid/joypad_ps5.cpp
--- a/third-party/inputtino/src/uhid/joypad_ps5.cpp     2025-08-15 13:00:08.148557490 +0200
+++ sunshine/third-party/inputtino/src/uhid/joypad_ps5.cpp      2025-08-15 13:27:51.574081232 +0200
@@ -8,6 +8,8 @@
 #include <inputtino/input.hpp>
 #include <iomanip>
 #include <random>
+#include <regex>
+#include <sstream>
 #include <uhid/protected_types.hpp>
 #include <uhid/ps5.hpp>
 #include <uhid/uhid.hpp>
@@ -272,6 +274,16 @@
   }
   if (def.uniq.empty()) {
     def.uniq = joypad.get_mac_address();
+  } else {
+    if (std::regex_match(def.uniq, (std::regex) "^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$")) {
+      std::string item;
+      std::stringstream mac = std::stringstream(def.uniq);
+      int i = 0;
+      while (std::getline(mac, item, ':')) {
+          joypad._state->mac_address[i] = std::stoi(item, NULL, 16);
+          i = i + 1;
+      }
+    }
   }
 
   auto dev =
```

File: src_assets/common/assets/web/configs/tabs/Inputs.vue (hunk 1 above)
Comment (ReenigneArcher) [reply src_assets/common/assets/web/configs/tabs/Inputs.vue:92]: You're correct, interesting. The UI code has a comment that those are for Windows only, while the other (`ds4_back_as_touchpad_click`) is listed as all platforms. Agree it should be fixed separately.

**Comment by ABeltramo** [comment]
@Kishi85 I've just pushed a potential fix for this https://github.com/games-on-whales/inputtino/pull/31  

You should be able to just pass the `device_uniq` property in the canonical MAC address format like `AA:00:CC:11:EE:22` and it should fix the matching issue for this issue. The `phys` shouldn't be needed, I've hardcoded `INPUTTINO_BT_LINK` if it's empty, but you can pass any String in theory. I don't think any SW relies on that..

I gave that a quick go, and it seems to be working for me, let me know if this fixes it for you too, and I'll merge the PR in inputtino.

**Comment by Kishi85** [comment]
> @Kishi85 I've just pushed a potential fix for this [games-on-whales/inputtino#31](https://github.com/games-on-whales/inputtino/pull/31)
> 
> You should be able to just pass the `device_uniq` property in the canonical MAC address format like `AA:00:CC:11:EE:22` and it should fix the matching issue for this issue. The `phys` shouldn't be needed, I've hardcoded `INPUTTINO_BT_LINK` if it's empty, but you can pass any String in theory. I don't think any SW relies on that..
> 
> I gave that a quick go, and it seems to be working for me, let me know if this fixes it for you too, and I'll merge the PR in inputtino.

I've tested it and apart from that remark I left on the PR everything looks good to me and is working. ~~I'm not sure whether I'll remove the device_phys from this PR tho~~ I'll leave device_phys in for now as that is what is shown in dmesg after when the controller connects (otherwise it would show INPUTTINO_BT_LINK instead of the MAC address):

Example: ```hidraw5: BLUETOOTH HID v81.11 Gamepad [Sunshine PS5 (virtual) pad] on``` **02:00:00:00:00:00**

**Comment by ABeltramo** [comment]
> I've tested it and apart from that remark I left on the PR everything looks good to me

You lost me there, which remark are you talking about?

**Comment by Kishi85** [comment]
> > I've tested it and apart from that remark I left on the PR everything looks good to me
> 
> You lost me there, which remark are you talking about?

My review about making the MAC parser safer by regex matching it beforehand on your PR at https://github.com/games-on-whales/inputtino/pull/31

EDIT: Whoops. Forgot to submit, should be there now.

**Comment by Kishi85** [comment]
This is ready for merge on my end and @ABeltramo has updated inputtino so that device_uniq does what is necessary for this to fully work now. 

Since I haven't worked that much with dependabot so far: Do I have to update the submodule in this PR or will dependabot put up a separate PR for inputtino?

File: src/platform/linux/input/inputtino_gamepad.cpp [hunk 3]
```diff
@@ -42,8 +42,23 @@ namespace platf::gamepad {
                                             .version = 0x8111});
   }
 
-  auto create_ds5() {
-    return inputtino::PS5Joypad::create({.name = "Sunshine PS5 (virtual) pad", .vendor_id = 0x054C, .product_id = 0x0CE6, .version = 0x8111});
+  auto create_ds5(int globalIndex) {
+    std::string device_mac;
```
Comment (ReenigneArcher) [inline src/platform/linux/input/inputtino_gamepad.cpp]:
```suggestion
    std::string device_mac = "";
```

File: src/platform/linux/input/inputtino_gamepad.cpp [hunk 4]
```diff
@@ -42,8 +42,23 @@ namespace platf::gamepad {
...
+
+    if (!config::input.ds5_inputtino_randomize_mac && globalIndex >= 0 && globalIndex <= 255) {
+      // Generate private virtual device MAC based on gamepad globalIndex between 0 (00) and 255 (ff)
+      device_mac = std::format("02:00:00:00:00:{:02x}", globalIndex);
+    } else {
+      // Inputtino checks empty() to generate a random MAC
+      device_mac = "";
+    }
```
Comment (ReenigneArcher) [inline src/platform/linux/input/inputtino_gamepad.cpp]:
```suggestion
    }
```

**Review by ReenigneArcher — COMMENTED** [review]
We could initialize the device_mac as empty and then set it only if needed, reducing the if/else block.

There's a few lint errors here: https://github.com/LizardByte/Sunshine/actions/runs/16984755077/job/48225412676?pr=4158#step:11:19

Otherwise, looks fine to me.

**Review by ReenigneArcher — APPROVED** [review]

**Comment by Kishi85** [comment]
Done as requested. For this to fully work it requires the third-party/inputtino to be bumped to latest stable but i'm assuming dependabot will take care of this.

**Comment by ReenigneArcher** [comment]
> For this to fully work it requires the third-party/inputtino to be bumped to latest stable but i'm assuming dependabot will take care of this.

Yes, dependabot will pick up any changes. Currently it runs daily (M-F), so should pick up on Monday.
