### PR TITLE
fix(macos/linux): import boost headers normally

### LINKED ISSUE #3052: Installing on MacOS M3
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

Running brew install sunshine exits with:

../../../../build/assets/web/assets/ResourceCard-ea4a7cba.js                  1.67 kB │ gzip:   0.64 kB
../../../../build/assets/web/assets/index-1d511c0f.js                         2.06 kB │ gzip:   0.90 kB
../../../../build/assets/web/assets/Navbar-dbaf0800.js                        2.16 kB │ gzip:   0.94 kB
../../../../build/assets/web/assets/config-f4fb6dcb.js                        4.97 kB │ gzip:   2.10 kB
../../../../build/assets/web/assets/apps-966a1e70.js                         85.57 kB │ gzip:  25.93 kB
../../../../build/assets/web/assets/_plugin-vue_export-helper-fe085d29.js   327.84 kB │ gzip: 111.98 kB
✓ built in 1.04s
[ 98%] Built target web-ui
make: *** [all] Error 2

### Expected Behavior

Success

### Additional Context

command sunshine doesn't register since the build fails
Link given when failed /lizardbyte/homebrew-homebrew/issues does not exist (issue reporting disabled for that repo)

### Host Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Architecture

arm

### Sunshine commit or version

the one on homebrew, can't run the command

### Package

Linux - Homebrew

### GPU Type

AMD

### GPU Model

Apple Silicon M3 Pro Max

### GPU Driver/Mesa Version

Apple Silicon M3 Pro Max

### Capture Method

None

### Config

```Shell
none
```

### Apps

_No response_

### Relevant log output

```shell
../../../../build/assets/web/assets/ResourceCard-ea4a7cba.js                  1.67 kB │ gzip:   0.64 kB
../../../../build/assets/web/assets/index-1d511c0f.js                         2.06 kB │ gzip:   0.90 kB
../../../../build/assets/web/assets/Navbar-dbaf0800.js                        2.16 kB │ gzip:   0.94 kB
../../../../build/assets/web/assets/config-f4fb6dcb.js                        4.97 kB │ gzip:   2.10 kB
../../../../build/assets/web/assets/apps-966a1e70.js                         85.57 kB │ gzip:  25.93 kB
../../../../build/assets/web/assets/_plugin-vue_export-helper-fe085d29.js   327.84 kB │ gzip: 111.98 kB
✓ built in 1.04s
[ 98%] Built target web-ui
make: *** [all] Error 2
```

### LINKED ISSUE #3098: macOS install via Brew fails at make step
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Running `brew install` fails at the `make -j` step.

```
==> Installing sunshine from lizardbyte/homebrew
==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 -DSUNSHINE_ASSETS_DIR=sunshine/assets -DSUNSHINE_BUILD_HOMEBREW=ON -DTESTS_ENABLE_PYTHON_TESTS=OFF
==> make -j
Last 15 lines from /Users/brandonli/Library/Logs/Homebrew/sunshine/02.make:
13 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/process.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
18 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/platform/macos/misc.mm.o] Error 1
8 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/stream.cpp.o] Error 1
8 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/httpcommon.cpp.o] Error 1
8 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/confighttp.cpp.o] Error 1
7 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/nvhttp.cpp.o] Error 1
make[1]: **
* [tests/CMakeFiles/test_sunshine.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues
```

Full 02.make file:
[02.make.txt](https://github.com/user-attachments/files/16744047/02.make.txt)

### Expected Behavior

Successful installation.

### Additional Context

_No response_

### Host Operating System

macOS

### Operating System Version

14.4.1 (23E224)

### Architecture

64 bit

### Sunshine commit or version

88ce5077b04e56a4b8717b67b685b1d47a0d0a00

### Package

macOS - Homebrew

### GPU Type

AMD

### GPU Model

5500M

### GPU Driver/Mesa Version

NA

### Capture Method

None

### Config

```Shell
NA
```

### Apps

_No response_

### Relevant log output

```shell
NA
```

### PR DESCRIPTION
**Pull request by Hazer**
## Description
macOS build seems to be broken because of boost headers, linux seems to be working as is, but since the forward headers issue is windows only, I think we should handle it as a Windows only flag.

### Issues Fixed or Closed
- Fixes #3052
- Fixes #3098

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

File: src/platform/common.h [hunk 1]
```diff
@@ -31,6 +35,7 @@ struct AVHWFramesContext;
 struct AVCodecContext;
 struct AVDictionary;
 
+#ifdef _WIN32
 // Forward declarations of boost classes to avoid having to include boost headers
 // here, which results in issues with Windows.h and WinSock2.h include order.
 namespace boost {
```
Comment (Hazer) [inline src/platform/common.h:41]: Is this still relevant for Windows with our current build tools?

**Review by ReenigneArcher — APPROVED** [review]

File: src/platform/common.h (hunk 1 above)
Comment (cgutman) [reply src/platform/common.h:41]: Yep it still is.

```
In file included from C:/msys64/ucrt64/include/boost/asio/detail/win_event.hpp:25,
                 from C:/msys64/ucrt64/include/boost/asio/detail/event.hpp:23,
                 from C:/msys64/ucrt64/include/boost/asio/execution/blocking_adaptation.hpp:19,
                 from C:/msys64/ucrt64/include/boost/asio/execution.hpp:22,
                 from C:/msys64/ucrt64/include/boost/asio/any_completion_executor.hpp:22,
                 from C:/msys64/ucrt64/include/boost/asio.hpp:20,
                 from C:/Users/camer/moonlight-src/LB_Sunshine/src/platform/common.h:14,
                 from C:\Users\camer\moonlight-src\LB_Sunshine\src\platform\windows\input.cpp:18:
C:/msys64/ucrt64/include/boost/asio/detail/socket_types.hpp:24:4: error: #error WinSock.h has already been included
   24 | #  error WinSock.h has already been included
      |    ^~~~~
In file included from C:/msys64/ucrt64/include/boost/asio/detail/socket_types.hpp:33:
C:/msys64/ucrt64/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
   15 | #warning Please include winsock2.h before windows.h
      |  ^~~~~~~
In file included from C:/msys64/ucrt64/include/windows.h:72,
                 from C:/msys64/ucrt64/include/winsock2.h:23,
                 from C:/msys64/ucrt64/include/boost/asio/detail/socket_types.hpp:33,
                 from C:/msys64/ucrt64/include/boost/asio/detail/win_event.hpp:25,
                 from C:/msys64/ucrt64/include/boost/asio/detail/event.hpp:23,
                 from C:/msys64/ucrt64/include/boost/asio/execution/blocking_adaptation.hpp:19,
                 from C:/msys64/ucrt64/include/boost/asio/execution.hpp:22,
                 from C:/msys64/ucrt64/include/boost/asio/any_completion_executor.hpp:22,
                 from C:/msys64/ucrt64/include/boost/asio.hpp:20,
                 from C:\Users\camer\moonlight-src\LB_Sunshine\src\platform/common.h:14,
                 from C:\Users\camer\moonlight-src\LB_Sunshine\src\input.h:9,
                 from C:\Users\camer\moonlight-src\LB_Sunshine\src\input.cpp:21:

```

Comment (Hazer) [reply src/platform/common.h:41]: Perfect, thanks for testing it out!

**Review by ReenigneArcher — APPROVED** [review]
