### PR TITLE
fix(hostname): fix handling of non-ASCII hostnames on Windows

### LINKED ISSUE #3381: Unable to connect if PC hostname is UTF-16 encoded
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

On Windows, if the hostname of the PC is UTF-16 encoded (mine included ö), everything appears to start and work from from the Sunshine side (besides a small error about encoding in the logs) but connecting to Moonlight will fail without a helpful message. Overriding the name to be UTF-8 encoded solves the problem.

### Expected Behavior

Any valid UTF-16 encoded (or otherwise extended) string should be a valid hostname

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

10

### Architecture

amd64/x86_64

### Sunshine commit or version

0.23.1

### Package

Windows - installer (recommended)

### GPU Type

Nvidia

### GPU Model

RTX 2060 Super

### GPU Driver/Mesa Version

Unknown

### Capture Method

None

### Config

_No response_

### Apps

_No response_

### Relevant log output

```shell
[2024:11:08:06:36:42]: Info: Sunshine version: v0.23.1
[2024:11:08:06:36:42]: Info: nvprefs: No need to modify application profile settings
[2024:11:08:06:36:42]: Info: nvprefs: Changed OGL_CPL_PREFER_DXPRESENT to OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED for base profile
[2024:11:08:06:36:42]: Info: Compiling shaders...
[2024:11:08:06:36:42]: Info: System tray created
[2024:11:08:06:36:42]: Info: Compiled shaders
[2024:11:08:06:36:42]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:11:08:06:36:42]: Info: Trying encoder [nvenc]
[2024:11:08:06:36:42]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2024:11:08:06:36:42]: Info: Set GPU preference: 1
[2024:11:08:06:36:42]: Info: 
Device Description : NVIDIA GeForce RTX 2060 SUPER
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00001F06
Device Video Mem   : 8006 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16337 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2024:11:08:06:36:42]: Info: Active GPU has HAGS disabled
[2024:11:08:06:36:42]: Info: Using realtime GPU priority
[2024:11:08:06:36:42]: Info: Desktop resolution [2560x1440]
[2024:11:08:06:36:42]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:11:08:06:36:42]: Info: Display refresh rate [59.951Hz]
[2024:11:08:06:36:42]: Info: Requested frame rate [60fps]
[2024:11:08:06:36:42]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.662109,0.329102]
Green Primary      : [0.300781,0.620117]
Blue Primary       : [0.144531,0.0488281]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:11:08:06:36:42]: Info: SDR color coding [Rec. 601]
[2024:11:08:06:36:42]: Info: Color depth: 8-bit
[2024:11:08:06:36:42]: Info: Color range: [JPEG]
[2024:11:08:06:36:42]: Info: NvEnc: created encoder P1 two-pass rfi
[2024:11:08:06:36:42]: Info: SDR color coding [Rec. 601]
[2024:11:08:06:36:42]: Info: Color depth: 8-bit
[2024:11:08:06:36:42]: Info: Color range: [JPEG]
[2024:11:08:06:36:42]: Info: NvEnc: created encoder P1 two-pass rfi
[2024:11:08:06:36:42]: Info: SDR color coding [Rec. 601]
[2024:11:08:06:36:42]: Info: Color depth: 8-bit
[2024:11:08:06:36:42]: Info: Color range: [JPEG]
[2024:11:08:06:36:42]: Error: NvEnc: encoding format is not supported by the gpu
[2024:11:08:06:36:43]: Info: 
Device Description : NVIDIA GeForce RTX 2060 SUPER
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00001F06
Device Video Mem   : 8006 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16337 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2024:11:08:06:36:43]: Info: Active GPU has HAGS disabled
[2024:11:08:06:36:43]: Info: Using realtime GPU priority
[2024:11:08:06:36:43]: Info: Desktop resolution [2560x1440]
[2024:11:08:06:36:43]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:11:08:06:36:43]: Info: Display refresh rate [59.951Hz]
[2024:11:08:06:36:43]: Info: Requested frame rate [60fps]
[2024:11:08:06:36:43]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.662109,0.329102]
Green Primary      : [0.300781,0.620117]
Blue Primary       : [0.144531,0.0488281]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:11:08:06:36:43]: Info: SDR color coding [Rec. 709]
[2024:11:08:06:36:43]: Info: Color depth: 10-bit
[2024:11:08:06:36:43]: Info: Color range: [JPEG]
[2024:11:08:06:36:43]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2024:11:08:06:36:43]: Info: 
[2024:11:08:06:36:43]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:11:08:06:36:43]: Info: 
[2024:11:08:06:36:43]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2024:11:08:06:36:43]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2024:11:08:06:36:43]: Error: Failed to get UTF-16 buffer size: 1113
[2024:11:08:06:36:43]: Info: Configuration UI available at [https://localhost:47990]
[2024:11:08:06:36:43]: Info: Registered Sunshine mDNS service
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
`boost::asio::ip::host_name()` uses `gethostname()` under the hood on Windows, which returns characters in the OEM codepage (though Boost does not document this anywhere). This isn't what Sunshine is expecting, so it misinterprets the output as UTF-8 and writes potentially invalid characters into the `/serverinfo` response.

Other platforms use UTF-8 as their 8-bit string representation, so they should be fine to still call `boost::asio::ip::host_name()`.

### Issues Fixed or Closed
Fixes #3381

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

File: tests/unit/platform/test_common.cpp [hunk 1]
```diff
@@ -47,3 +49,8 @@ INSTANTIATE_TEST_SUITE_P(
     std::make_tuple("SUNSHINE_UNIT_TEST_ENV_VAR", "test_value_0", 0),
     std::make_tuple("SUNSHINE_UNIT_TEST_ENV_VAR", "test_value_1", 0),
     std::make_tuple("", "test_value", -1)));
+
+TEST(HostnameTests, TestAsioEquality) {
+  // These should be equivalent on all platforms for ASCII hostnames
+  ASSERT_EQ(platf::get_host_name(), boost::asio::ip::host_name());
+}
```
Comment (ReenigneArcher) [inline tests/unit/platform/test_common.cpp:56]:
```suggestion
}

```

nit

**Comment by cgutman** [comment]
Tested locally with hostname containing `ü` and confirmed that mDNS worked and the PC, iOS, and Android Moonlight clients displayed the names properly.
