### PR TITLE
fix: automatic selection for hybrid GPU and IDDSampleDriver users

### LINKED ISSUE #1632: [Nightly] Sunshine chose wrong adaptor.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

ADAPTER and DISPLAY (whatever I disable Intel or not, the `DISPLAY50` always under `4070 Ti`):
```
====== ADAPTER =====
Device Name      : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID : 0x000010DE
Device Device ID : 0x00002782
Device Video Mem : 12010 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16166 MiB

    ====== OUTPUT ======
    Output Name       : \\.\DISPLAY50
    AttachedToDesktop : yes
    Resolution        : 1920x1080

====== ADAPTER =====
Device Name      : Intel(R) UHD Graphics 770
Device Vendor ID : 0x00008086
Device Device ID : 0x0000A780
Device Video Mem : 128 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16166 MiB
```
the `\\.\DISPLAY50` is a virtual display created by `parsec VDA` or `usbmmid` or `iddSampleAdapter`

### Expected Behavior

Sunshine should detect a output `\\.\display50` on `NVIDIA GeForce RTX 4070 Ti`, chose it, and could stream video normally.

But actually it chose the `Intel(R) UHD Graphics 770`, and trying to use `av1_qsv` codec. No video output at this time.

And after I disabled the `Intel(R) UHD Graphics 770`, sunshine could chose the right `NVIDIA GeForce RTX 4070 Ti` now, and could stream normally.

### Additional Context

<details>
<summary>If I start sunshine with intel disabled</summary>

```
[2023:09:13:15:44:15]: Info: nvprefs: No need to modify application profile settings
[2023:09:13:15:44:15]: Info: nvprefs: Changed OGL_CPL_PREFER_DXPRESENT to OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED for base profile
[2023:09:13:15:44:15]: Info: Sunshine version: 0.20.0.8e5516c1232bb95ed9d637cea3a292385480805f
[2023:09:13:15:44:15]: Info: Compiling shaders...
[2023:09:13:15:44:15]: Info: System tray created
[2023:09:13:15:44:15]: Info: Compiled shaders
[2023:09:13:15:44:15]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:09:13:15:44:15]: Info: Trying encoder [nvenc]
[2023:09:13:15:44:15]: Info: ddprobe.exe [1] [\\.\DISPLAY50] returned: 0x00000000
[2023:09:13:15:44:15]: Info: Set GPU preference: 1
[2023:09:13:15:44:16]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:44:16]: Info: Active GPU has HAGS enabled
[2023:09:13:15:44:16]: Info: Using realtime GPU priority
[2023:09:13:15:44:16]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:44:16]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:44:16]: Info: Display refresh rate [60Hz]
[2023:09:13:15:44:16]: Info: Requested frame rate [60fps]
[2023:09:13:15:44:16]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
```

</details>

<details><summary> If I specific adaptor or reenable Intel </summary>

```
[2023:09:13:15:51:22]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:09:13:15:51:22]: Info: Trying encoder [nvenc]
[2023:09:13:15:51:22]: Error: Failed to locate an output device
[2023:09:13:15:51:23]: Error: Failed to locate an output device
[2023:09:13:15:51:23]: Info: Encoder [nvenc] failed
[2023:09:13:15:51:23]: Info: Trying encoder [quicksync]
[2023:09:13:15:51:24]: Error: Failed to locate an output device
[2023:09:13:15:51:24]: Error: Failed to locate an output device
[2023:09:13:15:51:24]: Info: Encoder [quicksync] failed
[2023:09:13:15:51:24]: Info: Trying encoder [amdvce]
[2023:09:13:15:51:25]: Error: Failed to locate an output device
[2023:09:13:15:51:26]: Error: Failed to locate an output device
[2023:09:13:15:51:26]: Info: Encoder [amdvce] failed
[2023:09:13:15:51:26]: Info: Trying encoder [software]
[2023:09:13:15:51:26]: Error: Failed to locate an output device
[2023:09:13:15:51:27]: Error: Failed to locate an output device
[2023:09:13:15:51:27]: Info: Encoder [software] failed
[2023:09:13:15:51:27]: Fatal: Couldn't find any working encoder
```

</details>

<details><summary> If start sunshine with intel enabled </summary>

<p>
<p>
definitely it chose intel 770, and trying `*_qvs` codecs

</details>

### Host Operating System

Windows

### Operating System Version

Windows 11 22621.2134

### Architecture

64 bit

### Sunshine commit or version

0.20.0.8e5516c1232bb95ed9d637cea3a292385480805f

### Package

Portable

### GPU Type

Nvidia

### GPU Model

GeForce 4070 Ti

### GPU Driver/Mesa Version

536.67

### Capture Method (Linux Only)

_No response_

### Config

```Shell
output_name = \\.\DISPLAY50
resolutions = [
    1280x720,
    1920x1080,
    3840x2160,
    2550x1440
]
fps = [60,120,144]
adapter_name = NVIDIA GeForce RTX 4070 Ti
```

### Apps

_No response_

### Relevant log output

<details> <summary>Launch with intel disabled, try stream, reenable intel, and etc </summary>

```shell
[2023:09:13:15:44:15]: Info: nvprefs: No need to modify application profile settings
[2023:09:13:15:44:15]: Info: nvprefs: Changed OGL_CPL_PREFER_DXPRESENT to OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED for base profile
[2023:09:13:15:44:15]: Info: Sunshine version: 0.20.0.8e5516c1232bb95ed9d637cea3a292385480805f
[2023:09:13:15:44:15]: Info: Compiling shaders...
[2023:09:13:15:44:15]: Info: System tray created
[2023:09:13:15:44:15]: Info: Compiled shaders
[2023:09:13:15:44:15]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:09:13:15:44:15]: Info: Trying encoder [nvenc]
[2023:09:13:15:44:15]: Info: ddprobe.exe [1] [\\.\DISPLAY50] returned: 0x00000000
[2023:09:13:15:44:15]: Info: Set GPU preference: 1
[2023:09:13:15:44:16]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:44:16]: Info: Active GPU has HAGS enabled
[2023:09:13:15:44:16]: Info: Using realtime GPU priority
[2023:09:13:15:44:16]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:44:16]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:44:16]: Info: Display refresh rate [60Hz]
[2023:09:13:15:44:16]: Info: Requested frame rate [60fps]
[2023:09:13:15:44:16]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:44:17]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:44:17]: Info: Active GPU has HAGS enabled
[2023:09:13:15:44:17]: Info: Using realtime GPU priority
[2023:09:13:15:44:17]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:44:17]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:44:17]: Info: Display refresh rate [60Hz]
[2023:09:13:15:44:17]: Info: Requested frame rate [60fps]
[2023:09:13:15:44:17]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:44:17]: Info: SDR color coding [Rec. 601]
[2023:09:13:15:44:17]: Info: Color depth: 8-bit
[2023:09:13:15:44:17]: Info: Color range: [JPEG]
[2023:09:13:15:44:17]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:09:13:15:44:17]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:44:17]: Info: Active GPU has HAGS enabled
[2023:09:13:15:44:17]: Info: Using realtime GPU priority
[2023:09:13:15:44:17]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:44:17]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:44:17]: Info: Display refresh rate [60Hz]
[2023:09:13:15:44:17]: Info: Requested frame rate [60fps]
[2023:09:13:15:44:17]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:44:17]: Info: SDR color coding [Rec. 601]
[2023:09:13:15:44:17]: Info: Color depth: 8-bit
[2023:09:13:15:44:17]: Info: Color range: [JPEG]
[2023:09:13:15:44:17]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:09:13:15:44:18]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:44:18]: Info: Active GPU has HAGS enabled
[2023:09:13:15:44:18]: Info: Using realtime GPU priority
[2023:09:13:15:44:18]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:44:18]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:44:18]: Info: Display refresh rate [60Hz]
[2023:09:13:15:44:18]: Info: Requested frame rate [60fps]
[2023:09:13:15:44:18]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:44:18]: Info: SDR color coding [Rec. 601]
[2023:09:13:15:44:18]: Info: Color depth: 8-bit
[2023:09:13:15:44:18]: Info: Color range: [JPEG]
[2023:09:13:15:44:18]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:09:13:15:44:19]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:44:19]: Info: Active GPU has HAGS enabled
[2023:09:13:15:44:19]: Info: Using realtime GPU priority
[2023:09:13:15:44:19]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:44:19]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:44:19]: Info: Display refresh rate [60Hz]
[2023:09:13:15:44:19]: Info: Requested frame rate [60fps]
[2023:09:13:15:44:19]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:44:19]: Info: SDR color coding [Rec. 709]
[2023:09:13:15:44:19]: Info: Color depth: 10-bit
[2023:09:13:15:44:19]: Info: Color range: [JPEG]
[2023:09:13:15:44:19]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:09:13:15:44:19]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:44:19]: Info: Active GPU has HAGS enabled
[2023:09:13:15:44:19]: Info: Using realtime GPU priority
[2023:09:13:15:44:19]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:44:19]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:44:19]: Info: Display refresh rate [60Hz]
[2023:09:13:15:44:19]: Info: Requested frame rate [60fps]
[2023:09:13:15:44:19]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:44:19]: Info: SDR color coding [Rec. 709]
[2023:09:13:15:44:19]: Info: Color depth: 10-bit
[2023:09:13:15:44:19]: Info: Color range: [JPEG]
[2023:09:13:15:44:19]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:09:13:15:44:20]: Info: 
[2023:09:13:15:44:20]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:09:13:15:44:20]: Info: 
[2023:09:13:15:44:20]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2023:09:13:15:44:20]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2023:09:13:15:44:20]: Info: Found AV1 encoder: av1_nvenc [nvenc]
[2023:09:13:15:44:20]: Info: Configuration UI available at [https://localhost:47990]
[2023:09:13:15:44:20]: Info: Registered Sunshine mDNS service
[2023:09:13:15:51:22]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:09:13:15:51:22]: Info: Trying encoder [nvenc]
[2023:09:13:15:51:22]: Error: Failed to locate an output device
[2023:09:13:15:51:23]: Error: Failed to locate an output device
[2023:09:13:15:51:23]: Info: Encoder [nvenc] failed
[2023:09:13:15:51:23]: Info: Trying encoder [quicksync]
[2023:09:13:15:51:24]: Error: Failed to locate an output device
[2023:09:13:15:51:24]: Error: Failed to locate an output device
[2023:09:13:15:51:24]: Info: Encoder [quicksync] failed
[2023:09:13:15:51:24]: Info: Trying encoder [amdvce]
[2023:09:13:15:51:25]: Error: Failed to locate an output device
[2023:09:13:15:51:26]: Error: Failed to locate an output device
[2023:09:13:15:51:26]: Info: Encoder [amdvce] failed
[2023:09:13:15:51:26]: Info: Trying encoder [software]
[2023:09:13:15:51:26]: Error: Failed to locate an output device
[2023:09:13:15:51:27]: Error: Failed to locate an output device
[2023:09:13:15:51:27]: Info: Encoder [software] failed
[2023:09:13:15:51:27]: Fatal: Couldn't find any working encoder
[2023:09:13:15:51:58]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:09:13:15:51:58]: Info: Trying encoder [nvenc]
[2023:09:13:15:51:58]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:51:58]: Info: Active GPU has HAGS enabled
[2023:09:13:15:51:58]: Info: Using realtime GPU priority
[2023:09:13:15:51:58]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:51:58]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:51:58]: Info: Display refresh rate [60Hz]
[2023:09:13:15:51:58]: Info: Requested frame rate [60fps]
[2023:09:13:15:51:58]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:51:59]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:51:59]: Info: Active GPU has HAGS enabled
[2023:09:13:15:51:59]: Info: Using realtime GPU priority
[2023:09:13:15:51:59]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:51:59]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:51:59]: Info: Display refresh rate [60Hz]
[2023:09:13:15:51:59]: Info: Requested frame rate [60fps]
[2023:09:13:15:51:59]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:51:59]: Info: SDR color coding [Rec. 601]
[2023:09:13:15:51:59]: Info: Color depth: 8-bit
[2023:09:13:15:51:59]: Info: Color range: [JPEG]
[2023:09:13:15:51:59]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:09:13:15:51:59]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:51:59]: Info: Active GPU has HAGS enabled
[2023:09:13:15:51:59]: Info: Using realtime GPU priority
[2023:09:13:15:51:59]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:51:59]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:51:59]: Info: Display refresh rate [60Hz]
[2023:09:13:15:51:59]: Info: Requested frame rate [60fps]
[2023:09:13:15:51:59]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:51:59]: Info: SDR color coding [Rec. 601]
[2023:09:13:15:51:59]: Info: Color depth: 8-bit
[2023:09:13:15:51:59]: Info: Color range: [JPEG]
[2023:09:13:15:52:00]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:09:13:15:52:00]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:52:00]: Info: Active GPU has HAGS enabled
[2023:09:13:15:52:00]: Info: Using realtime GPU priority
[2023:09:13:15:52:00]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:52:00]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:52:00]: Info: Display refresh rate [60Hz]
[2023:09:13:15:52:00]: Info: Requested frame rate [60fps]
[2023:09:13:15:52:00]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:52:00]: Info: SDR color coding [Rec. 601]
[2023:09:13:15:52:00]: Info: Color depth: 8-bit
[2023:09:13:15:52:00]: Info: Color range: [JPEG]
[2023:09:13:15:52:00]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:09:13:15:52:00]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:52:00]: Info: Active GPU has HAGS enabled
[2023:09:13:15:52:00]: Info: Using realtime GPU priority
[2023:09:13:15:52:00]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:52:00]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:52:00]: Info: Display refresh rate [60Hz]
[2023:09:13:15:52:00]: Info: Requested frame rate [60fps]
[2023:09:13:15:52:00]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:52:00]: Info: SDR color coding [Rec. 709]
[2023:09:13:15:52:00]: Info: Color depth: 10-bit
[2023:09:13:15:52:00]: Info: Color range: [JPEG]
[2023:09:13:15:52:00]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:09:13:15:52:01]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:52:01]: Info: Active GPU has HAGS enabled
[2023:09:13:15:52:01]: Info: Using realtime GPU priority
[2023:09:13:15:52:01]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:52:01]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:52:01]: Info: Display refresh rate [60Hz]
[2023:09:13:15:52:01]: Info: Requested frame rate [60fps]
[2023:09:13:15:52:01]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:52:01]: Info: SDR color coding [Rec. 709]
[2023:09:13:15:52:01]: Info: Color depth: 10-bit
[2023:09:13:15:52:01]: Info: Color range: [JPEG]
[2023:09:13:15:52:01]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:09:13:15:52:01]: Info: 
[2023:09:13:15:52:01]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:09:13:15:52:01]: Info: 
[2023:09:13:15:52:01]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2023:09:13:15:52:01]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2023:09:13:15:52:01]: Info: Found AV1 encoder: av1_nvenc [nvenc]
[2023:09:13:15:52:01]: Info: Executing [Desktop]
[2023:09:13:15:52:02]: Info: nvprefs: No need to modify application profile settings
[2023:09:13:15:52:02]: Info: nvprefs: No need to modify global profile settings
[2023:09:13:15:52:02]: Info: CLIENT CONNECTED
[2023:09:13:15:52:02]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16166 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:09:13:15:52:02]: Info: Active GPU has HAGS enabled
[2023:09:13:15:52:02]: Info: Using realtime GPU priority
[2023:09:13:15:52:02]: Info: Desktop resolution [1920x1080]
[2023:09:13:15:52:02]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:52:02]: Info: Display refresh rate [60Hz]
[2023:09:13:15:52:02]: Info: Requested frame rate [60fps]
[2023:09:13:15:52:02]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0,0]
Green Primary      : [0,0]
Blue Primary       : [0,0]
White Point        : [0,0]
Min Luminance      : 0 nits
Max Luminance      : 0 nits
Max Full Luminance : 0 nits
[2023:09:13:15:52:02]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:09:13:15:52:02]: Info: SDR color coding [Rec. 601]
[2023:09:13:15:52:02]: Info: Color depth: 8-bit
[2023:09:13:15:52:02]: Info: Color range: [MPEG]
[2023:09:13:15:52:02]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:09:13:15:52:02]: Warning: Failed to install Steam audio drivers: 259
[2023:09:13:15:52:16]: Info: CLIENT DISCONNECTED
```
</details>

### LINKED ISSUE #2076: Unable to connect to IddSampleDriver display
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I have a setup with NVIDIA 4090 and integrated AMD graphics cards:
Zrzut ekranu 2024-01-30 o 10 35 49

Display#10 is [IddSampleDriver](https://github.com/itsmikethetech/Virtual-Display-Driver) and Display#1 is HDMI plug connected to HDMI port on NVIDIA 4090. For some reason, moonlight is not able to connect to sunshine once display is set as Display#10 ('Output Name' in Audio/Video settings), there is black screen on the client for few seconds and an error indicating that it does not recieve signal on ports 47998 and 48000. If I set it to Display#1 I am able to connect and then change the screen with Ctrl + Alt + Shift + F1-F2, virtual display works as expected.

In addition, if I unplug the HDMI plug and keep only virtual desktop and leave 'Output Name' empty, then moonlight is not able to connect as well.

Here is my device manager configuration:
Zrzut ekranu 2024-01-30 o 10 34 41
Zrzut ekranu 2024-01-30 o 10 34 30

### Expected Behavior

I would like to connect to virtual display driver.

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 4090

### GPU Driver/Mesa Version

551.23

### Capture Method (Linux Only)

_No response_

### Config

```Shell
av1_mode = 3
hevc_mode = 3
min_log_level = 1
output_name = \\.\DISPLAY1
```

### Apps

_No response_

### Relevant log output

```shell
On sunshine side I am getting:

[2024:01:30:09:57:20]: Error: DuplicateOutput() test failed [0x887A0004]
```
Full log is available [here](https://pastebin.com/pp64JxJ4).
Here is part of the log from sunshine around moonlight client connection:

```
---End Response---
[2024:01:30:09:57:19]: Debug: handle_read(): Handle read of size: 1072 bytes
[2024:01:30:09:57:19]: Debug: handle_payload(): Handle read of size: 900 bytes
[2024:01:30:09:57:19]: Debug: Found Content-Length: 1386 bytes
[2024:01:30:09:57:19]: Debug: handle_payload(): Handle read of size: 486 bytes
[2024:01:30:09:57:19]: Debug: Found Content-Length: 1386 bytes
[2024:01:30:09:57:19]: Debug: type [REQUEST]
[2024:01:30:09:57:19]: Debug: sequence number [6]
[2024:01:30:09:57:19]: Debug: protocol :: RTSP/1.0
[2024:01:30:09:57:19]: Debug: payload :: v=0
o=android 0 14 IN IPv4 192.168.1.22
s=NVIDIA Streaming Client
a=x-ml-general.featureFlags:1 
a=x-nv-video[0].clientViewportWd:3840 
a=x-nv-video[0].clientViewportHt:2160 
a=x-nv-video[0].maxFPS:120 
a=x-nv-video[0].packetSize:1392 
a=x-nv-video[0].rateControlMode:4 
a=x-nv-video[0].timeoutLengthMs:7000 
a=x-nv-video[0].framesWithInvalidRefThreshold:0 
a=x-nv-video[0].initialBitrateKbps:100000 
a=x-nv-video[0].initialPeakBitrateKbps:100000 
a=x-nv-vqos[0].bw.minimumBitrateKbps:100000 
a=x-nv-vqos[0].bw.maximumBitrateKbps:100000 
a=x-nv-vqos[0].fec.enable:1 
a=x-nv-vqos[0].videoQualityScoreUpdateTime:5000 
a=x-nv-vqos[0].qosTrafficType:5 
a=x-nv-aqos.qosTrafficType:4 
a=x-nv-general.featureFlags:167 
a=x-nv-general.useReliableUdp:13 
a=x-nv-vqos[0].fec.minRequiredFecPackets:2 
a=x-nv-vqos[0].bllFec.enable:0 
a=x-nv-vqos[0].drc.enable:0 
a=x-nv-general.enableRecoveryMode:0 
a=x-nv-video[0].videoEncoderSlicesPerFrame:1 
a=x-nv-clientSupportHevc:1 
a=x-nv-vqos[0].bitStreamFormat:1 
a=x-nv-video[0].dynamicRangeMode:1 
a=x-nv-video[0].maxNumReferenceFrames:0 
a=x-nv-video[0].clientRefreshRateX100:0 
a=x-nv-audio.surround.numChannels:8 
a=x-nv-audio.surround.channelMask:1599 
a=x-nv-audio.surround.enable:1 
a=x-nv-audio.surround.AudioQuality:1 
a=x-nv-aqos.packetDuration:5 
a=x-nv-video[0].encoderCscMode:0 
t=0 0
m=video 47998  
[2024:01:30:09:57:19]: Debug: command :: ANNOUNCE
[2024:01:30:09:57:19]: Debug: target :: streamid=control/13/0
[2024:01:30:09:57:19]: Debug: CSeq :: 6
[2024:01:30:09:57:19]: Debug: X-GS-ClientVersion :: 14
[2024:01:30:09:57:19]: Debug: Host :: 192.168.1.22
[2024:01:30:09:57:19]: Debug: Session :: DEADBEEFCAFE
[2024:01:30:09:57:19]: Debug: Content-type :: application/sdp
[2024:01:30:09:57:19]: Debug: Content-length :: 1386
[2024:01:30:09:57:19]: Debug: ---Begin MessageBuffer---
ANNOUNCE
---End MessageBuffer---
[2024:01:30:09:57:19]: Debug: /CN=NVIDIA GameStream Client -- verified
[2024:01:30:09:57:19]: Debug: TUNNEL :: HTTPS
[2024:01:30:09:57:19]: Debug: METHOD :: GET
[2024:01:30:09:57:19]: Debug: DESTINATION :: /serverinfo
[2024:01:30:09:57:19]: Debug: User-Agent -- Mozilla/5.0
[2024:01:30:09:57:19]: Debug: Accept-Language -- pl-PL,en,*
[2024:01:30:09:57:19]: Debug: Accept-Encoding -- gzip, deflate
[2024:01:30:09:57:19]: Debug: Connection -- Keep-Alive
[2024:01:30:09:57:19]: Debug: Host -- 192.168.1.22:47984
[2024:01:30:09:57:19]: Debug:  [--] 
[2024:01:30:09:57:19]: Debug: uuid -- aa23437dbe114094ad6a9b0169e6a621
[2024:01:30:09:57:19]: Debug: uniqueid -- 0123456789ABCDEF
[2024:01:30:09:57:19]: Debug:  [--] 
[2024:01:30:09:57:19]: Info: nvprefs: No need to modify application profile settings
[2024:01:30:09:57:19]: Info: nvprefs: No need to modify global profile settings
[2024:01:30:09:57:19]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 6
 
 
 
---End Response---
[2024:01:30:09:57:19]: Debug: handle_read(): Handle read of size: 95 bytes
[2024:01:30:09:57:19]: Debug: handle_payload(): Handle read of size: 0 bytes
[2024:01:30:09:57:19]: Debug: type [REQUEST]
[2024:01:30:09:57:19]: Debug: sequence number [7]
[2024:01:30:09:57:19]: Debug: protocol :: RTSP/1.0
[2024:01:30:09:57:19]: Debug: payload :: 
[2024:01:30:09:57:19]: Debug: command :: PLAY
[2024:01:30:09:57:19]: Debug: target :: /
[2024:01:30:09:57:19]: Debug: CSeq :: 7
[2024:01:30:09:57:19]: Debug: X-GS-ClientVersion :: 14
[2024:01:30:09:57:19]: Debug: Host :: 192.168.1.22
[2024:01:30:09:57:19]: Debug: Session :: DEADBEEFCAFE
[2024:01:30:09:57:19]: Debug: ---Begin MessageBuffer---
PLAY
---End MessageBuffer---
[2024:01:30:09:57:19]: Debug: ---Begin Response---
RTSP/1.0 200 OK
CSeq: 7
 
 
 
---End Response---
[2024:01:30:09:57:19]: Info: CLIENT CONNECTED
[2024:01:30:09:57:19]: Debug: type [IDX_REQUEST_IDR_FRAME]
[2024:01:30:09:57:19]: Debug: type [IDX_START_B]
[2024:01:30:09:57:19]: Debug: RAISE: 192.168.1.188:61073 :: VIDEO
[2024:01:30:09:57:19]: Debug: Received ping from 192.168.1.188:61073 [474E4950]
[2024:01:30:09:57:19]: Debug: Start capturing Video
[2024:01:30:09:57:19]: Debug: Detecting monitors...
[2024:01:30:09:57:19]: Debug: 
====== ADAPTER =====
Device Name      : AMD Radeon(TM) Graphics
Device Vendor ID : 0x00001002
Device Device ID : 0x0000164E
Device Video Mem : 485 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 15946 MiB
 
    ====== OUTPUT ======
[2024:01:30:09:57:19]: Debug:     Output Name       : \\.\DISPLAY1
    AttachedToDesktop : yes
    Resolution        : 1920x1080
 
[2024:01:30:09:57:19]: Debug: --begin relative mouse move packet--
deltaX [1]
deltaY [1]
--end relative mouse move packet--
[2024:01:30:09:57:19]: Debug: --begin relative mouse move packet--
deltaX [-1]
deltaY [-1]
--end relative mouse move packet--
[2024:01:30:09:57:20]: Debug: RAISE: 192.168.1.188:62935 :: AUDIO
[2024:01:30:09:57:20]: Debug: Received ping from 192.168.1.188:62935 [474E4950]
[2024:01:30:09:57:20]: Debug: Start capturing Audio
[2024:01:30:09:57:20]: Debug: Stereo: supported
[2024:01:30:09:57:20]: Debug: Surround 5.1: supported
[2024:01:30:09:57:20]: Debug: Surround 7.1: supported
[2024:01:30:09:57:20]: Debug: Stereo: supported
[2024:01:30:09:57:20]: Debug: Surround 5.1: supported
[2024:01:30:09:57:20]: Debug: Surround 7.1: supported
[2024:01:30:09:57:20]: Debug: Stereo: supported
[2024:01:30:09:57:20]: Debug: Surround 5.1: supported
[2024:01:30:09:57:20]: Debug: Surround 7.1: supported
[2024:01:30:09:57:20]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:01:30:09:57:20]: Debug:     Output Name       : \\.\DISPLAY10
    AttachedToDesktop : yes
    Resolution        : 3840x2160
 
[2024:01:30:09:57:20]: Debug: Stereo: supported
[2024:01:30:09:57:20]: Debug: Surround 5.1: supported
[2024:01:30:09:57:20]: Debug: Surround 7.1: supported
[2024:01:30:09:57:20]: Debug: 
```
```

### LINKED ISSUE #2078: Sunshine doesn't switch display adapter between laptop iGPU and dGPU
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I'm using a laptop with both an Intel HD630 iGPU and an NVIDIA RTX. I use a dummy HDMI adapter into the HDMI port, which is wired directly to the dGPU so that I can stream from that dummy HDMI adapter and use dGPU for encoding, which supports HEVC HDR.

The problem is, when Sunshine starts along with Windows, it auto-detects the built-in laptop display + iGPU and uses that combo. After I use the MonitorSwitch app to specifically choose to turn off the built-in laptop display, only using dummy HDMI + dGPU, Sunshine still tries to use iGPU to encode, which causes an error.

It would have been much better if Sunshine could auto-detect the display adapter changes to choose the display adapter dynamically.

### Expected Behavior

_No response_

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

Windows 11 22H2 22621.3007

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2080 Super Max-Q

### GPU Driver/Mesa Version

551.23

### Capture Method (Linux Only)

_No response_

### Config

```Shell
sw_preset = ultrafast
qsv_preset = veryfast
min_log_level = 0
qsv_coder = cavlc
global_prep_cmd = [{"do":"cmd /C C:\\Users\\ngqna\\Downloads\\qres\\qres.bat %SUNSHINE_CLIENT_WIDTH% %SUNSHINE_CLIENT_HEIGHT% %SUNSHINE_APP_NAME%","undo":"cmd /C C:\\Users\\ngqna\\Downloads\\qres\\qres_reset.bat","elevated":false}]
fps = [60]
resolutions = [
    1680x1050,
    1920x1080,
    1280x720,
    3840x2160
]
channels = 2
hevc_mode = 0
encoder = nvenc
gamepad = x360
av1_mode = 2
```

### Apps

_No response_

### Relevant log output

```shell
too long to paste here
```

### LINKED ISSUE #2203: Failed to locate an output device, DuplicateOutput() test failed [0x887A0004], No displays were found after reenumeration!
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Start the game and the game will freeze after automatically going full screen.

### Expected Behavior

Normal operation

### Additional Context

After launching Minecraft Dungeons, the screen freezes when the game is automatically switched to full screen, and can only be restored by closing the game with a shortcut key. The same issue also appeared in Hitman 3, but the way I quit after running the game remotely via Steam made it so that I didn't freeze again when I opened the game with Moonlight. The same method can get Minecraft Dungeons to work, only it's more complicated. There is also a Fatal: Couldn't find any working encoder error before installing the nightly version

### Host Operating System

Windows

### Operating System Version

Windows 11 23H2 22635.3212

### Architecture

64 bit

### Sunshine commit or version

0.21.0.5606840c8983b714a0e442c42d887a49807715e1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 4070 LapTap

### GPU Driver/Mesa Version

551.61

### Capture Method (Linux Only)

_No response_

### Config

```Shell
It is empty.
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH);$(ProgramFiles(x86))\\Steam"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png"
        },
        {
            "name": "Steam",
            "image-path": "steam.png",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "cmd": "\"D:\\Program Files (x86)\\Steam\\steam.exe\""
        },
        {
            "name": "Epic",
            "output": "",
            "cmd": "\"D:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win64\\EpicGamesLauncher.exe\"",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "image-path": ""
        },
        {
            "name": "Minecraft Dungeons",
            "output": "",
            "cmd": "\"D:\\XboxGames\\Minecraft Dungeons\\Content\\Dungeons.exe\"",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "image-path": "C:\\Program Files\\Sunshine\\config\/covers\/igdb_110474.png"
        }
    ]
}
```

### Relevant log output

```shell
[2024:03:03:19:38:41]: Info: Sunshine version: 0.21.0.5606840c8983b714a0e442c42d887a49807715e1
[2024:03:03:19:38:41]: Info: nvprefs: Opened undo file from previous improper termination
[2024:03:03:19:38:41]: Info: nvprefs: Restored OGL_CPL_PREFER_DXPRESENT for base profile
[2024:03:03:19:38:41]: Info: nvprefs: Restored global profile settings from undo file - deleting the file
[2024:03:03:19:38:41]: Info: nvprefs: No need to modify application profile settings
[2024:03:03:19:38:41]: Info: nvprefs: Changed OGL_CPL_PREFER_DXPRESENT to OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED for base profile
[2024:03:03:19:38:41]: Info: Compiling shaders...
[2024:03:03:19:38:41]: Info: Compiled shaders
[2024:03:03:19:38:41]: Info: System tray created
[2024:03:03:19:38:41]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:03:03:19:38:41]: Info: Trying encoder [nvenc]
[2024:03:03:19:38:41]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2024:03:03:19:38:41]: Info: Set GPU preference: 1
[2024:03:03:19:38:41]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:38:41]: Info: Active GPU has HAGS disabled
[2024:03:03:19:38:41]: Info: Using realtime GPU priority
[2024:03:03:19:38:41]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:38:41]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:38:41]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:38:41]: Info: Requested frame rate [60fps]
[2024:03:03:19:38:41]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:38:41]: Info: Encoder [nvenc] is not supported on this GPU
[2024:03:03:19:38:41]: Info: Trying encoder [quicksync]
[2024:03:03:19:38:41]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:38:41]: Info: Active GPU has HAGS disabled
[2024:03:03:19:38:41]: Info: Using realtime GPU priority
[2024:03:03:19:38:41]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:38:41]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:38:41]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:38:41]: Info: Requested frame rate [60fps]
[2024:03:03:19:38:41]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:38:41]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:38:41]: Info: Color depth: 8-bit
[2024:03:03:19:38:41]: Info: Color range: [JPEG]
[2024:03:03:19:38:42]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:38:42]: Info: Color depth: 8-bit
[2024:03:03:19:38:42]: Info: Color range: [JPEG]
[2024:03:03:19:38:42]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:38:42]: Info: Color depth: 8-bit
[2024:03:03:19:38:42]: Info: Color range: [JPEG]
[2024:03:03:19:38:42]: Error: [av1_qsv @ 0000026961ef4840] Current codec type is unsupported
[2024:03:03:19:38:42]: Error: [av1_qsv @ 0000026961ef4840] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
[2024:03:03:19:38:42]: Error: Could not open codec [av1_qsv]: Function not implemented
[2024:03:03:19:38:42]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:38:42]: Info: Active GPU has HAGS disabled
[2024:03:03:19:38:42]: Info: Using realtime GPU priority
[2024:03:03:19:38:42]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:38:42]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:38:42]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:38:42]: Info: Requested frame rate [60fps]
[2024:03:03:19:38:42]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:38:42]: Info: SDR color coding [Rec. 709]
[2024:03:03:19:38:42]: Info: Color depth: 10-bit
[2024:03:03:19:38:42]: Info: Color range: [JPEG]
[2024:03:03:19:38:43]: Info: 
[2024:03:03:19:38:43]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:03:03:19:38:43]: Info: 
[2024:03:03:19:38:43]: Info: Found H.264 encoder: h264_qsv [quicksync]
[2024:03:03:19:38:43]: Info: Found HEVC encoder: hevc_qsv [quicksync]
[2024:03:03:19:38:43]: Info: Configuration UI available at [https://localhost:47990]
[2024:03:03:19:38:44]: Info: Registered Sunshine mDNS service
[2024:03:03:19:39:30]: Info: Encoder reenumeration is required
[2024:03:03:19:39:30]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:03:03:19:39:30]: Info: Trying encoder [nvenc]
[2024:03:03:19:39:30]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:39:30]: Info: Active GPU has HAGS disabled
[2024:03:03:19:39:30]: Info: Using realtime GPU priority
[2024:03:03:19:39:30]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:39:30]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:30]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:39:30]: Info: Requested frame rate [60fps]
[2024:03:03:19:39:30]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:39:30]: Info: Encoder [nvenc] is not supported on this GPU
[2024:03:03:19:39:30]: Info: Trying encoder [quicksync]
[2024:03:03:19:39:31]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:39:31]: Info: Active GPU has HAGS disabled
[2024:03:03:19:39:31]: Info: Using realtime GPU priority
[2024:03:03:19:39:31]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:39:31]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:31]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:39:31]: Info: Requested frame rate [60fps]
[2024:03:03:19:39:31]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:39:31]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:39:31]: Info: Color depth: 8-bit
[2024:03:03:19:39:31]: Info: Color range: [JPEG]
[2024:03:03:19:39:31]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:39:31]: Info: Color depth: 8-bit
[2024:03:03:19:39:31]: Info: Color range: [JPEG]
[2024:03:03:19:39:31]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:39:31]: Info: Color depth: 8-bit
[2024:03:03:19:39:31]: Info: Color range: [JPEG]
[2024:03:03:19:39:32]: Error: [av1_qsv @ 0000026961e8ee40] Current codec type is unsupported
[2024:03:03:19:39:32]: Error: [av1_qsv @ 0000026961e8ee40] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
[2024:03:03:19:39:32]: Error: Could not open codec [av1_qsv]: Function not implemented
[2024:03:03:19:39:32]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:39:32]: Info: Active GPU has HAGS disabled
[2024:03:03:19:39:32]: Info: Using realtime GPU priority
[2024:03:03:19:39:32]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:39:32]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:32]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:39:32]: Info: Requested frame rate [60fps]
[2024:03:03:19:39:32]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:39:32]: Info: SDR color coding [Rec. 709]
[2024:03:03:19:39:32]: Info: Color depth: 10-bit
[2024:03:03:19:39:32]: Info: Color range: [JPEG]
[2024:03:03:19:39:32]: Info: 
[2024:03:03:19:39:32]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:03:03:19:39:32]: Info: 
[2024:03:03:19:39:32]: Info: Found H.264 encoder: h264_qsv [quicksync]
[2024:03:03:19:39:32]: Info: Found HEVC encoder: hevc_qsv [quicksync]
[2024:03:03:19:39:32]: Info: Executing [Desktop]
[2024:03:03:19:39:32]: Info: nvprefs: No need to modify application profile settings
[2024:03:03:19:39:32]: Info: nvprefs: No need to modify global profile settings
[2024:03:03:19:39:32]: Info: WLAN interface 0 is now in low latency mode
[2024:03:03:19:39:32]: Info: CLIENT CONNECTED
[2024:03:03:19:39:32]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:39:32]: Info: Active GPU has HAGS disabled
[2024:03:03:19:39:32]: Info: Using realtime GPU priority
[2024:03:03:19:39:32]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:39:32]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:32]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:39:32]: Info: Requested frame rate [60fps]
[2024:03:03:19:39:32]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:39:33]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:39:33]: Info: Color depth: 8-bit
[2024:03:03:19:39:33]: Info: Color range: [MPEG]
[2024:03:03:19:39:33]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:36]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:39:36]: Info: Active GPU has HAGS disabled
[2024:03:03:19:39:36]: Info: Using realtime GPU priority
[2024:03:03:19:39:36]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:39:36]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:36]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:39:36]: Info: Requested frame rate [60fps]
[2024:03:03:19:39:36]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:39:36]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:36]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:39:36]: Info: Color depth: 8-bit
[2024:03:03:19:39:36]: Info: Color range: [MPEG]
[2024:03:03:19:39:42]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:39:42]: Info: Active GPU has HAGS disabled
[2024:03:03:19:39:42]: Info: Using realtime GPU priority
[2024:03:03:19:39:42]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:39:42]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:42]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:39:42]: Info: Requested frame rate [60fps]
[2024:03:03:19:39:42]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:39:42]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:39:42]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:39:42]: Info: Color depth: 8-bit
[2024:03:03:19:39:42]: Info: Color range: [MPEG]
[2024:03:03:19:40:11]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:11]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:12]: Error: Failed to locate an output device
[2024:03:03:19:40:13]: Error: Failed to locate an output device
[2024:03:03:19:40:13]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:13]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:14]: Error: Failed to locate an output device
[2024:03:03:19:40:15]: Error: Failed to locate an output device
[2024:03:03:19:40:15]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:15]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:16]: Error: Failed to locate an output device
[2024:03:03:19:40:16]: Error: Failed to locate an output device
[2024:03:03:19:40:17]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:17]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:18]: Error: Failed to locate an output device
[2024:03:03:19:40:18]: Error: Failed to locate an output device
[2024:03:03:19:40:19]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:19]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:19]: Error: Failed to locate an output device
[2024:03:03:19:40:20]: Error: Failed to locate an output device
[2024:03:03:19:40:21]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:21]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:21]: Error: Failed to locate an output device
[2024:03:03:19:40:22]: Error: Failed to locate an output device
[2024:03:03:19:40:23]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:23]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:23]: Error: Failed to locate an output device
[2024:03:03:19:40:24]: Error: Failed to locate an output device
[2024:03:03:19:40:24]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:24]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:25]: Error: Failed to locate an output device
[2024:03:03:19:40:26]: Error: Failed to locate an output device
[2024:03:03:19:40:26]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:26]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:27]: Error: Failed to locate an output device
[2024:03:03:19:40:27]: Error: Failed to locate an output device
[2024:03:03:19:40:28]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:28]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:28]: Error: Failed to locate an output device
[2024:03:03:19:40:29]: Error: Failed to locate an output device
[2024:03:03:19:40:30]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:30]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:30]: Error: Failed to locate an output device
[2024:03:03:19:40:31]: Error: Failed to locate an output device
[2024:03:03:19:40:32]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:32]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:32]: Error: Failed to locate an output device
[2024:03:03:19:40:33]: Error: Failed to locate an output device
[2024:03:03:19:40:33]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:33]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:34]: Error: Failed to locate an output device
[2024:03:03:19:40:35]: Error: Failed to locate an output device
[2024:03:03:19:40:35]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:35]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:36]: Error: Failed to locate an output device
[2024:03:03:19:40:36]: Error: Failed to locate an output device
[2024:03:03:19:40:37]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:37]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:38]: Error: Failed to locate an output device
[2024:03:03:19:40:38]: Error: Failed to locate an output device
[2024:03:03:19:40:39]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:39]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:39]: Error: Failed to locate an output device
[2024:03:03:19:40:40]: Error: Failed to locate an output device
[2024:03:03:19:40:41]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:41]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:41]: Error: Failed to locate an output device
[2024:03:03:19:40:42]: Error: Failed to locate an output device
[2024:03:03:19:40:43]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:43]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:43]: Error: Failed to locate an output device
[2024:03:03:19:40:44]: Error: Failed to locate an output device
[2024:03:03:19:40:44]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:44]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:45]: Error: Failed to locate an output device
[2024:03:03:19:40:46]: Error: Failed to locate an output device
[2024:03:03:19:40:46]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:46]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:47]: Error: Failed to locate an output device
[2024:03:03:19:40:47]: Error: Failed to locate an output device
[2024:03:03:19:40:48]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:48]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:49]: Error: Failed to locate an output device
[2024:03:03:19:40:49]: Error: Failed to locate an output device
[2024:03:03:19:40:50]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:50]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:50]: Error: Failed to locate an output device
[2024:03:03:19:40:51]: Error: Failed to locate an output device
[2024:03:03:19:40:52]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:52]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:52]: Error: Failed to locate an output device
[2024:03:03:19:40:53]: Error: Failed to locate an output device
[2024:03:03:19:40:54]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:54]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:54]: Error: Failed to locate an output device
[2024:03:03:19:40:55]: Error: Failed to locate an output device
[2024:03:03:19:40:55]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:55]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:56]: Error: Failed to locate an output device
[2024:03:03:19:40:57]: Error: Failed to locate an output device
[2024:03:03:19:40:57]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:57]: Error: No displays were found after reenumeration!
[2024:03:03:19:40:58]: Error: Failed to locate an output device
[2024:03:03:19:40:58]: Error: Failed to locate an output device
[2024:03:03:19:40:59]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:40:59]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:00]: Error: Failed to locate an output device
[2024:03:03:19:41:00]: Error: Failed to locate an output device
[2024:03:03:19:41:01]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:01]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:01]: Error: Failed to locate an output device
[2024:03:03:19:41:02]: Error: Failed to locate an output device
[2024:03:03:19:41:03]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:03]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:03]: Error: Failed to locate an output device
[2024:03:03:19:41:04]: Error: Failed to locate an output device
[2024:03:03:19:41:05]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:05]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:05]: Error: Failed to locate an output device
[2024:03:03:19:41:06]: Error: Failed to locate an output device
[2024:03:03:19:41:06]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:06]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:07]: Error: Failed to locate an output device
[2024:03:03:19:41:08]: Error: Failed to locate an output device
[2024:03:03:19:41:08]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:08]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:09]: Error: Failed to locate an output device
[2024:03:03:19:41:09]: Error: Failed to locate an output device
[2024:03:03:19:41:10]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:10]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:11]: Error: Failed to locate an output device
[2024:03:03:19:41:11]: Error: Failed to locate an output device
[2024:03:03:19:41:12]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:12]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:12]: Error: Failed to locate an output device
[2024:03:03:19:41:13]: Error: Failed to locate an output device
[2024:03:03:19:41:14]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:14]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:14]: Error: Failed to locate an output device
[2024:03:03:19:41:15]: Error: Failed to locate an output device
[2024:03:03:19:41:16]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:16]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:16]: Error: Failed to locate an output device
[2024:03:03:19:41:17]: Error: Failed to locate an output device
[2024:03:03:19:41:17]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:17]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:18]: Error: Failed to locate an output device
[2024:03:03:19:41:19]: Error: Failed to locate an output device
[2024:03:03:19:41:19]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:19]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:20]: Error: Failed to locate an output device
[2024:03:03:19:41:20]: Error: Failed to locate an output device
[2024:03:03:19:41:21]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:21]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:22]: Error: Failed to locate an output device
[2024:03:03:19:41:22]: Error: Failed to locate an output device
[2024:03:03:19:41:23]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:23]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:23]: Error: Failed to locate an output device
[2024:03:03:19:41:24]: Error: Failed to locate an output device
[2024:03:03:19:41:25]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:25]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:25]: Error: Failed to locate an output device
[2024:03:03:19:41:26]: Error: Failed to locate an output device
[2024:03:03:19:41:27]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:27]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:27]: Error: Failed to locate an output device
[2024:03:03:19:41:28]: Error: Failed to locate an output device
[2024:03:03:19:41:28]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:28]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:29]: Error: Failed to locate an output device
[2024:03:03:19:41:30]: Error: Failed to locate an output device
[2024:03:03:19:41:30]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:30]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:31]: Error: Failed to locate an output device
[2024:03:03:19:41:31]: Error: Failed to locate an output device
[2024:03:03:19:41:32]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:32]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:33]: Error: Failed to locate an output device
[2024:03:03:19:41:33]: Error: Failed to locate an output device
[2024:03:03:19:41:34]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:34]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:34]: Error: Failed to locate an output device
[2024:03:03:19:41:35]: Error: Failed to locate an output device
[2024:03:03:19:41:36]: Error: DuplicateOutput() test failed [0x887A0004]
[2024:03:03:19:41:36]: Error: No displays were found after reenumeration!
[2024:03:03:19:41:36]: Error: Failed to locate an output device
[2024:03:03:19:41:37]: Error: Failed to locate an output device
[2024:03:03:19:41:38]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:41:38]: Info: Active GPU has HAGS disabled
[2024:03:03:19:41:38]: Info: Using realtime GPU priority
[2024:03:03:19:41:38]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:41:38]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:41:38]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:41:38]: Info: Requested frame rate [60fps]
[2024:03:03:19:41:38]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:41:38]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:41:38]: Info: Color depth: 8-bit
[2024:03:03:19:41:38]: Info: Color range: [MPEG]
[2024:03:03:19:41:38]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:42:18]: Info: Opening UI from system tray
[2024:03:03:19:42:18]: Info: Resolved user-provided command 'https://localhost:47990' to '"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --single-argument https://localhost:47990'
[2024:03:03:19:42:18]: Info: https://localhost:47990 running with PID 19908
[2024:03:03:19:42:18]: Info: Opened url [https://localhost:47990]
[2024:03:03:19:42:20]: Info: Web UI: [127.0.0.1] -- not authorized
[2024:03:03:19:42:54]: Info: CLIENT DISCONNECTED
[2024:03:03:19:51:59]: Info: Encoder reenumeration is required
[2024:03:03:19:51:59]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:03:03:19:51:59]: Info: Trying encoder [nvenc]
[2024:03:03:19:51:59]: Error: DuplicateOutput() test failed [0x80070005]
[2024:03:03:19:52:00]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:52:00]: Info: Active GPU has HAGS disabled
[2024:03:03:19:52:00]: Info: Using realtime GPU priority
[2024:03:03:19:52:00]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:52:00]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:52:00]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:52:00]: Info: Requested frame rate [60fps]
[2024:03:03:19:52:00]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:52:00]: Info: Encoder [nvenc] is not supported on this GPU
[2024:03:03:19:52:00]: Info: Trying encoder [quicksync]
[2024:03:03:19:52:00]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:52:00]: Info: Active GPU has HAGS disabled
[2024:03:03:19:52:00]: Info: Using realtime GPU priority
[2024:03:03:19:52:00]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:52:00]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:52:00]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:52:00]: Info: Requested frame rate [60fps]
[2024:03:03:19:52:00]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:52:00]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:52:00]: Info: Color depth: 8-bit
[2024:03:03:19:52:00]: Info: Color range: [JPEG]
[2024:03:03:19:52:00]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:52:00]: Info: Color depth: 8-bit
[2024:03:03:19:52:00]: Info: Color range: [JPEG]
[2024:03:03:19:52:00]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:52:00]: Info: Color depth: 8-bit
[2024:03:03:19:52:00]: Info: Color range: [JPEG]
[2024:03:03:19:52:01]: Error: [av1_qsv @ 0000026961f18580] Current codec type is unsupported
[2024:03:03:19:52:01]: Error: [av1_qsv @ 0000026961f18580] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
[2024:03:03:19:52:01]: Error: Could not open codec [av1_qsv]: Function not implemented
[2024:03:03:19:52:01]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:52:01]: Info: Active GPU has HAGS disabled
[2024:03:03:19:52:01]: Info: Using realtime GPU priority
[2024:03:03:19:52:01]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:52:01]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:52:01]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:52:01]: Info: Requested frame rate [60fps]
[2024:03:03:19:52:01]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:52:01]: Info: SDR color coding [Rec. 709]
[2024:03:03:19:52:01]: Info: Color depth: 10-bit
[2024:03:03:19:52:01]: Info: Color range: [JPEG]
[2024:03:03:19:52:01]: Info: 
[2024:03:03:19:52:01]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:03:03:19:52:01]: Info: 
[2024:03:03:19:52:01]: Info: Found H.264 encoder: h264_qsv [quicksync]
[2024:03:03:19:52:01]: Info: Found HEVC encoder: hevc_qsv [quicksync]
[2024:03:03:19:52:01]: Info: nvprefs: No need to modify application profile settings
[2024:03:03:19:52:01]: Info: nvprefs: No need to modify global profile settings
[2024:03:03:19:52:01]: Info: WLAN interface 0 is now in low latency mode
[2024:03:03:19:52:01]: Info: CLIENT CONNECTED
[2024:03:03:19:52:01]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:52:01]: Info: Active GPU has HAGS disabled
[2024:03:03:19:52:01]: Info: Using realtime GPU priority
[2024:03:03:19:52:01]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:52:01]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:52:01]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:52:01]: Info: Requested frame rate [60fps]
[2024:03:03:19:52:01]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:52:01]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:52:01]: Info: Color depth: 8-bit
[2024:03:03:19:52:01]: Info: Color range: [MPEG]
[2024:03:03:19:52:01]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:52:31]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:52:31]: Info: Active GPU has HAGS disabled
[2024:03:03:19:52:31]: Info: Using realtime GPU priority
[2024:03:03:19:52:31]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:52:31]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:52:31]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:52:31]: Info: Requested frame rate [60fps]
[2024:03:03:19:52:31]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:52:31]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:52:31]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:52:31]: Info: Color depth: 8-bit
[2024:03:03:19:52:31]: Info: Color range: [MPEG]
[2024:03:03:19:52:33]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:52:33]: Info: Active GPU has HAGS disabled
[2024:03:03:19:52:33]: Info: Using realtime GPU priority
[2024:03:03:19:52:33]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:52:33]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:52:33]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:52:33]: Info: Requested frame rate [60fps]
[2024:03:03:19:52:33]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:52:33]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:52:33]: Info: Color depth: 8-bit
[2024:03:03:19:52:33]: Info: Color range: [MPEG]
[2024:03:03:19:52:33]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:54:46]: Info: Opening UI from system tray
[2024:03:03:19:54:46]: Info: Resolved user-provided command 'https://localhost:47990' to '"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --single-argument https://localhost:47990'
[2024:03:03:19:54:46]: Info: https://localhost:47990 running with PID 20748
[2024:03:03:19:54:46]: Info: Opened url [https://localhost:47990]
[2024:03:03:19:55:24]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:55:24]: Info: Active GPU has HAGS disabled
[2024:03:03:19:55:24]: Info: Using realtime GPU priority
[2024:03:03:19:55:24]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:55:24]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:55:24]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:55:24]: Info: Requested frame rate [60fps]
[2024:03:03:19:55:24]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:55:24]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:55:24]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:55:24]: Info: Color depth: 8-bit
[2024:03:03:19:55:24]: Info: Color range: [MPEG]
[2024:03:03:19:56:30]: Info: 
Device Description : Intel(R) UHD Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000A788
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8045 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1600
Offset             : 0x0
Virtual Desktop    : 2560x1600
[2024:03:03:19:56:30]: Info: Active GPU has HAGS disabled
[2024:03:03:19:56:30]: Info: Using realtime GPU priority
[2024:03:03:19:56:30]: Info: Desktop resolution [2560x1600]
[2024:03:03:19:56:30]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:56:30]: Info: Display refresh rate [165.002Hz]
[2024:03:03:19:56:30]: Info: Requested frame rate [60fps]
[2024:03:03:19:56:30]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.654297,0.326172]
Green Primary      : [0.297852,0.606445]
Blue Primary       : [0.146484,0.0566406]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:03:03:19:56:30]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:03:03:19:56:30]: Info: SDR color coding [Rec. 601]
[2024:03:03:19:56:30]: Info: Color depth: 8-bit
[2024:03:03:19:56:30]: Info: Color range: [MPEG]
```

### LINKED ISSUE #2875: Black screen with multiple GPUs with virtual display, isolated to simply multiple GPUs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

I have 2 tesla T4 virtualized in a Windows VM with Proxmox VE (latest).
When I only passthrough 1 GPU, Sunshine does not complain. I'm using the Virtual Display Driver for this, and it works great.

However, when I passthrough both gpus on the SeaBIOS VM, Sunshine returns a black screen then disconnects me for "no video from host". Inputs and Audio are working as intended.

There is no network to consider here as it's localhost.
The only thing differentiating the working setup from the non-working setup is the SeaBIOS (legacy, which should have 0 effect)
and the fact that I have 2 Tesla T4s in this case, not 1.

I have tried restricting Sunshine to either gPU to no avail.
I've tried telling Sunshine to only use NVENC.
I've tried changing the autodetect capture APIs from duplication to the beta to no avail.
I have tried HEVC vs H264 to no avail.
I have tried every configuration option that could affect this to no avail.

I know that my virtualized setup and gpus with no display out will definitely raise some eyebrows, but again, the setup works with a single GPU with no complaints. However I must pass through both gpus to the windows VM, and there's no reason for this not to work as such.

Most importantly, other remote options such as Parsec, Anydesk, Teamviewer all have no complaints. It is only Sunshine that is causing this issue, but I much prefer sunshine over all alternatives.

https://pastebin.com/RVy5qApc Debug logs

### Expected Behavior

With multiple GPUs, sunshine should choose one and not display a black screen or "no video received from host" and exit.

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

11 Pro (latest)

### Architecture

64 bit

### Sunshine commit or version

v2024.715.152002

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Tesla T4

### GPU Driver/Mesa Version

552.74

### Capture Method

Desktop Duplication API (Windows)

### Config

```Shell
encoder = nvenc
sunshine_name = MSKontakt
port = 49000
resolutions = [
    3440x1440
]
fps = [120]
min_threads = 6
av1_mode = 1
```

### Apps

```json
N/A
```

### Relevant log output

```shell
https://pastebin.com/RVy5qApc
```

### PR DESCRIPTION
**Pull request by Nonary**
## Description
Enhances the ddprobe utility to test to see if frames can be captured and that they are also not empty frames. If one of the 10 frames captured is not empty, it will return back successful. Previously it was only testing to see if it can be duplicated, but would fail on capturing frames which would cause Sunshine to pick the wrong GPU.

### Screenshot
N/A

### Issues Fixed or Closed
- Fixes #2203 
- Fixes #2076
- Fixes #2875
- Fixes #2078
- Fixes #1632

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

File: tools/ddprobe.cpp [hunk 1]
```diff
@@ -69,9 +69,131 @@ syncThreadDesktop() {
...
+ *
+ * This function checks if the provided frame is entirely black by inspecting each pixel in both the x and y dimensions. It inspects the RGB channels of each pixel and compares them against a specified black threshold. If any pixel's RGB values exceed this threshold, the frame is considered not black, and the function returns `false`. Otherwise, if all pixels are below the threshold, the function returns `true`.
+ *
+ * @param mappedResource A reference to a `D3D11_MAPPED_SUBRESOURCE` structure that contains the mapped subresource data of the frame to be analyzed.
+ * @param frameDesc A reference to a `D3D11_TEXTURE2D_DESC` structure that describes the texture properties, including width and height.
+ * @param blackThreshold A floating-point value representing the threshold above which a pixel's RGB channels are considered non-black. The value ranges from 0.0f to 1.0f, with a default value of 0.1f.
+ * @return bool Returns `true` if the frame is determined to be black, otherwise returns `false`.
+ */
+bool
+isFrameBlack(const D3D11_MAPPED_SUBRESOURCE &mappedResource, const D3D11_TEXTURE2D_DESC &frameDesc, float blackThreshold = 0.1f) {
```
Comment (FrogTheFrog) [inline tools/ddprobe.cpp:83]: Sunshine uses snake_case naming conventions. I think newly added code should also use it.

File: tools/ddprobe.cpp [hunk 2]
```diff
@@ -69,9 +69,131 @@ syncThreadDesktop() {
...
+    if (FAILED(status)) {
+      std::cout << "Failed to acquire next frame [0x" << std::hex << status << "]" << std::endl;
+      return status;
+    }
+
+    std::cout << "Frame acquired successfully." << std::endl;
+
+    ID3D11Texture2D *frameTexture = nullptr;
+    status = frameResource->QueryInterface(__uuidof(ID3D11Texture2D), (void **) &frameTexture);
+    frameResource->Release();
```
Comment (FrogTheFrog) [inline tools/ddprobe.cpp:136]: Unsafe resource cleanup. "RAII" based approach should be used, like `util::fail_guard` or `boost::scope::scope_exit` (if available).

For example:
```
IDXGIResource *frame_resource = nullptr;
auto frame_resource_guard{util::fail_guard([&]() {
    if (frame_resource) {
        frame_resource ->Release();
        frame_resource  = nullptr;
    }
}};

File: tools/ddprobe.cpp [hunk 3]
```diff
@@ -92,24 +214,41 @@ test_dxgi_duplication(dxgi::adapter_t &adapter, dxgi::output_t &output) {
...
-  return output1->DuplicateOutput((IUnknown *) device.get(), &dup);
+  HRESULT result = output1->DuplicateOutput(static_cast<IUnknown *>(device.get()), &dup);
+
+  if (SUCCEEDED(result)) {
+    // If duplication is successful, test frame capture
+    HRESULT captureResult = test_frame_capture(dup, device.get());
+    if (SUCCEEDED(captureResult)) {
+      return S_OK;
+    }
+    else {
```
Comment (FrogTheFrog) [inline tools/ddprobe.cpp:243]: Redundant else.

File: tools/ddprobe.cpp [hunk 4]
```diff
@@ -92,24 +214,41 @@ test_dxgi_duplication(dxgi::adapter_t &adapter, dxgi::output_t &output) {
...
+      std::cout << "Frame capture test failed [0x" << std::hex << captureResult << "]" << std::endl;
+      return captureResult;
+    }
+  }
+  else {
```
Comment (FrogTheFrog) [inline tools/ddprobe.cpp:248]: Redundant else.

File: tools/ddprobe.cpp [hunk 5]
```diff
@@ -69,9 +69,131 @@ syncThreadDesktop() {
...
+    }
+
+    ID3D11DeviceContext *context = nullptr;
+    device->GetImmediateContext(&context);
+    context->CopyResource(stagingTexture, frameTexture);
+    frameTexture->Release();
+
+    D3D11_MAPPED_SUBRESOURCE mappedResource;
+    status = context->Map(stagingTexture, 0, D3D11_MAP_READ, 0, &mappedResource);
+    if (SUCCEEDED(status)) {
```
Comment (FrogTheFrog) [inline tools/ddprobe.cpp:164]: This conditional could potentially be reversed (or otherwise simplified) if RAII-based cleanup is implemented.

**Comment by FrogTheFrog** [comment]
I have no idea about whether the code logic is correct or not, but I've added a few remarks about other stuff.

File: tools/ddprobe.cpp (hunk 1 above)
Comment (Nonary) [reply tools/ddprobe.cpp:83]: It's a mixture of both actually, the only consistent behavior was that it appeared more internal functions weren't snake_cased so that's why I did it that way, fixing it is no big deal either way

File: tools/ddprobe.cpp (hunk 3 above)
Comment (Nonary) [reply tools/ddprobe.cpp:243]: I prefer to call that explicitly defined else 😅


That's just a matter of preference basically, even if it doesn't matter a lot of people prefer seeing else as it is easier to read.

File: tools/ddprobe.cpp (hunk 4 above)
Comment (Nonary) [reply tools/ddprobe.cpp:248]: Same as before, this is more a programmers preference. A lot of devs include else for clarity even if it doesn't matter.

File: tools/ddprobe.cpp (hunk 2 above)
Comment (Nonary) [reply tools/ddprobe.cpp:136]: I've though about ComPTR instead as well, but not surprised I missed that one because I don't really code in c++ often

File: tools/ddprobe.cpp (hunk 3 above)
Comment (ReenigneArcher) [reply tools/ddprobe.cpp:243]: If you don't mind... for this code base I prefer to remove the redundancy. It reduces nesting and is easier to read (IMO).

Comment (FrogTheFrog) [reply tools/ddprobe.cpp:243]: As we don't have a coding guideline, I pointed this out, we discussed it and that's that.

Now, how do I resolve this...

File: tools/ddprobe.cpp (hunk 1 above)
Comment (ReenigneArcher) [reply tools/ddprobe.cpp:83]: We have a lot of inconsistency. The new pattern would ideally be snake case though.

While I like the idea of camel case... it has some issues. For example take a function named `get_gfe_version`... in camel case, that's `getGfeVersion` or `getGFEVersion`? Both of those are harder to read and I'm not sure either is correct.

Mostly, I like to follow what python does with PEP8, as it's pretty well thought out and defined.

File: tools/ddprobe.cpp (hunk 3 above)
Comment (Nonary) [reply tools/ddprobe.cpp:243]: > If you don't mind... for this code base I prefer to remove the redundancy. It reduces nesting and is easier to read (IMO).

I honestly don't see how it's easier to read by removing braces and hiding the branch path by using a return

By removing the else, you make it harder for IDE to be able to simply hide the code path by minimizing it.

If anything it makes it harder to maintain in my opinion, but whatever, the debate of if/else is one of the most controversial ones for developers, I'll remove it

**Comment by Nonary** [comment]
I'm having troubles recompiling sunshine on master branch ever since the game capture commit was added

And yeah I did swap the docs to master and followed the steps, but it just refuses to compile.

So I'm planning to push these changes again soon just need to clone an earlier build of sunshine before that was added so that way the old build instructions for me work and I can test locally again

**Comment by ReenigneArcher** [comment]
Probably one these are the reasons...

1. Need to use ucrt64 instead of mingw64
2. Need to downgrade curl, see https://github.com/LizardByte/Sunshine/blob/f9c885a414f92d8277337e2fd1283110a0e376bb/.github/workflows/CI.yml#L1008-L1030

File: tools/ddprobe.cpp (hunk 3 above)
Comment (ReenigneArcher) [reply tools/ddprobe.cpp:243]: JetBrains IDEs complain about redundant else clauses, by default.

image

**Comment by Nonary** [comment]
> Probably one these are the reasons...
> 
> 1. Need to use ucrt64 instead of mingw64
> 2. Need to downgrade curl, see https://github.com/LizardByte/Sunshine/blob/f9c885a414f92d8277337e2fd1283110a0e376bb/.github/workflows/CI.yml#L1008-L1030

That was the first place I looked when I suspected documentation was wrong, made no difference. 

```
BI::Windows::UI::Core::Point'
 1605 |                     struct Point AdjustedPoint;
C:/msys64/ucrt64/include/windows.ui.core.h:1605: note: forward declaration of 'struct ABI::Windows::UI::Core::Point'
C:/msys64/ucrt64/include/windows.ui.core.h:2762: error: use of enum 'VirtualKey' without previous declaration
 2762 |                         enum VirtualKey key,
C:/msys64/ucrt64/include/windows.ui.core.h:2766: error: use of enum 'VirtualKey' without previous declaration
 2766 |                         enum VirtualKey key,
C:/msys64/ucrt64/include/windows.ui.core.h:4608: error: use of enum 'VirtualKey' without previous declaration
 4608 |                         enum VirtualKey *value) = 0;
C:/msys64/ucrt64/include/windows.ui.core.h:4879: error: use of enum 'VirtualKeyModifiers' without previous declaration
 4879 |                         enum VirtualKeyModifiers *value) = 0;
In file included from C:/msys64/ucrt64/include/windows.graphics.capture.interop.h:42:
C:/msys64/ucrt64/include/windows.graphics.capture.h:905: error: use of enum 'DirectXPixelFormat' without previous declaration
  905 |                         enum DirectXPixelFormat pixel_format,
C:/msys64/ucrt64/include/windows.graphics.capture.h:1103: error: use of enum 'DirectXPixelFormat' without previous declaration 1103 |                         enum DirectXPixelFormat pixel_format,
C:/msys64/ucrt64/include/windows.graphics.capture.h:1239: error: use of enum 'DirectXPixelFormat' without previous declaration 1239 |                         enum DirectXPixelFormat pixel_format,
[30/72] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/nvhttp.cpp.obj
ninja: build stopped: subcommand failed.
```

File: tools/ddprobe.cpp (hunk 3 above)
Comment (Nonary) [reply tools/ddprobe.cpp:243]: > JetBrains IDEs complain about redundant else clauses, by default.
> 
> image
Yeah I am just going to say we agree to disagree there.

Imagine if, when you're trying to plan an event, you thought, "If event_needs_planning... return plan_event; return event_planned!" But that’s not how most humans think. Instead, we think more like, "If event_needs_planning, plan_event; otherwirse I don't need to plan anything."

The "else" statement mirrors how we naturally think, which is why I argue it's easier to understand and follow the flow. It also makes it much easier to hide branches in the IDE, which is the main benefit of it. If you followed every rule we would end up with complete garbage code like https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition

**Comment by ReenigneArcher** [comment]
Works for me in Win 11 (not beta channel)... and ucrt64 with ninja. Tough to diagnose without seeing more logs like cmake logs (after clearing cache and re-running) and everything.

Haven't been any recent changes to mingw-w64-cppwinrt, https://github.com/msys2/MINGW-packages/commits/0517c5b3b68994453d599fe1c3b4fdfc24907334/mingw-w64-cppwinrt/PKGBUILD

Also, note you need to run all of those commands in order... not just downgrade curl.

Lastly, be sure to update submodules.

**Comment by Nonary** [comment]
> Works for me in Win 11 (not beta channel)... and ucrt64 with ninja. Tough to diagnose without seeing more logs like cmake logs (after clearing cache and re-running) and everything.
> 
> Haven't been any recent changes to mingw-w64-cppwinrt, https://github.com/msys2/MINGW-packages/commits/0517c5b3b68994453d599fe1c3b4fdfc24907334/mingw-w64-cppwinrt/PKGBUILD
> 
> Also, note you need to run all of those commands in order... not just downgrade curl.
> 
> Lastly, be sure to update submodules.
> 
> p.s. I'm closing the previously closed issues, which were either closed because the users found workarounds, or went stale. No need to re-open them, you can still link your PR to closed issued.

As long as the fix bot attaches a comment stating it has been fixed, that's all I was really going for on that one. To make sure people where notified that had commented on those issues

I've been beating my head around this for like an hour and a half now, so just going to clone out an old base of sunshine, then cherry pick the commits on top of that so it builds for me to test it.

**Comment by ReenigneArcher** [comment]
> As long as the fix bot attaches a comment stating it has been fixed, that's all I was really going for on that one.

Oh, okay... That was a manual process before... after merging we had to go and apply the "fixed" label. We're no longer doing that since we got rid of the nightly branch.

**Comment by ReenigneArcher** [comment]
Replicating the build issues in CI now: https://github.com/LizardByte/Sunshine/actions/runs/10342476366/job/28625553004?pr=3003#step:9:169

File: tools/ddprobe.cpp (hunk 3 above)
Comment (Nonary) [reply tools/ddprobe.cpp]: Oh I just reread that jetbrains code issue and it's talking about an entirely different issue.

It warns when you have a completely redundant if/else statement that can be simplified to a single return, without needing an if or else statement entirely.

That's not the same thing as what we were talking about earlier.

Either way all of those are "fixed" now

File: tools/ddprobe.cpp [hunk 6]
```diff
@@ -69,6 +71,123 @@ syncThreadDesktop() {
...
+ */
+HRESULT
+test_frame_capture(dxgi::dup_t &dup, ComPtr<ID3D11Device> device) {
+  for (int i = 0; i < 10; ++i) {
+    std::cout << "Attempting to acquire frame " << (i + 1) << " of 10..." << std::endl;
+
+    ComPtr<IDXGIResource> frameResource;
+    DXGI_OUTDUPL_FRAME_INFO frameInfo;
+    HRESULT status = dup->AcquireNextFrame(500, &frameInfo, &frameResource);
+    auto release_frame = util::fail_guard([&dup]() {
```
Comment (FrogTheFrog) [inline tools/ddprobe.cpp:134]: I think this should created after the `if (FAILED(status)) {` since we could be releasing a non-acquired frame. I dunno if it's safe or not. If it is, then it's fine.

File: tools/ddprobe.cpp [hunk 7]
```diff
@@ -69,6 +71,123 @@ syncThreadDesktop() {
...
+    D3D11_MAPPED_SUBRESOURCE mappedResource;
+    status = context->Map(stagingTexture.Get(), 0, D3D11_MAP_READ, 0, &mappedResource);
+    if (FAILED(status)) {
+      std::cout << "Error: Failed to map the staging texture for inspection [0x"sv << util::hex(status).to_string_view() << ']' << std::endl;
+      return status;
+    }
+
+    if (is_valid_frame(mappedResource, frameDesc)) {
+      std::cout << "Frame " << (i + 1) << " is non-empty (contains visible content)." << std::endl;
+      context->Unmap(stagingTexture.Get(), 0);
```
Comment (FrogTheFrog) [inline tools/ddprobe.cpp:179]: `context->Unmap` could also be put into a guard.

File: tools/ddprobe.cpp (hunk 5 above)
Comment (Nonary) [reply tools/ddprobe.cpp]: I’ve fixed all that by using ComPtr, also just a side note… I don’t like negating Boolean checks. 

example…

if(!isEven) { …} ❌

vs if(is odd){ …} ✅

To me it is more clear to keep checks always test for truths, but that is a completely personal preference in coding styles on my part.

File: tools/ddprobe.cpp (hunk 6 above)
Comment (Nonary) [reply tools/ddprobe.cpp:134]: As far as I am aware, fail guards are executed when the scope ends so its totally safe doing that.

Comment (Nonary) [reply tools/ddprobe.cpp:134]: And that the code is always acquiring a frame, regardless if it succeeds or fails, it always needs to release.

File: tools/ddprobe.cpp (hunk 7 above)
Comment (Nonary) [reply tools/ddprobe.cpp]: I was thinking about that too, but thought it might be overkill since it only saved one line of code… 

but since I already had a guard there, it made more sense to do that so good suggestion

**Comment by ReenigneArcher** [comment]
@paulzzh thanks, I have submitted an issue here: https://github.com/msys2/MINGW-packages/issues/21645

**Comment by Nonary** [comment]
I pretty much guessed it was mingW issue when the header files was in the mingW directories, but their GitHub structure is so convoluted I couldn't figure out how to submit the proper issue...

**Comment by Biswa96** [comment]
> but their GitHub structure is so convoluted I couldn't figure out how to submit the proper issue...

Just FYI, every package page has a "Report Issue" button. For example, https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-headers-git?repo=ucrt64

File: tools/ddprobe.cpp [hunk 8]
```diff
@@ -107,9 +229,24 @@ test_dxgi_duplication(dxgi::adapter_t &adapter, dxgi::output_t &output) {
...
+  HRESULT result = output1->DuplicateOutput(device_ptr.Get(), &dup);
+
+  if (FAILED(result)) {
+    std::cout << "Failed to duplicate output [0x"sv << util::hex(result).to_string_view() << "]" << std::endl;
+    return result;
+  }
+
+  // If duplication is successful, test frame capture
+  HRESULT captureResult = test_frame_capture(dup, device_ptr.Get());
+  if (FAILED(captureResult)) {
```
Comment (cgutman) [inline tools/ddprobe.cpp:244]: `S_FALSE` is a success value, so I'm not sure how this could be working. I think we would just return `S_OK` in the case like we did before?

File: tools/ddprobe.cpp [hunk 9]
```diff
@@ -107,9 +229,24 @@ test_dxgi_duplication(dxgi::adapter_t &adapter, dxgi::output_t &output) {
...
+  ComPtr<ID3D11Device> device_ptr(device.get());
+  HRESULT result = output1->DuplicateOutput(device_ptr.Get(), &dup);
+
+  if (FAILED(result)) {
+    std::cout << "Failed to duplicate output [0x"sv << util::hex(result).to_string_view() << "]" << std::endl;
+    return result;
+  }
+
+  // If duplication is successful, test frame capture
+  HRESULT captureResult = test_frame_capture(dup, device_ptr.Get());
```
Comment (cgutman) [inline tools/ddprobe.cpp:243]: I'm concerned we may generate false negatives for previously working systems. Can we pass a parameter into ddprobe to allow us to do a first pass with your new check followed by a second pass without if the first one finds no matching configurations?

**Review by cgutman — CHANGES_REQUESTED** [review]

File: tools/ddprobe.cpp (hunk 8 above)
Comment (Nonary) [reply tools/ddprobe.cpp]: Nice catch! Did not see that at all, fixed it

File: tools/ddprobe.cpp (hunk 9 above)
Comment (Nonary) [reply tools/ddprobe.cpp]: Updated the code to make the frame capture point optional like you suggested

File: tools/ddprobe.cpp [hunk 10]
```diff
@@ -69,8 +71,128 @@ syncThreadDesktop() {
...
+ *
+ * This function determines if the provided frame is completely dark by analyzing the RGB values of every pixel.
+ * It iterates over all pixels in the frame and compares each pixel's RGB channels to a defined darkness threshold.
+ * If any pixel's RGB values exceed this threshold, the function concludes that the frame is not entirely dark and returns `false`.
+ * If all pixels are below the threshold, indicating a completely dark frame, the function returns `true`.
+ *
+ * @param mappedResource A reference to a `D3D11_MAPPED_SUBRESOURCE` structure containing the mapped subresource data of the frame to be analyzed.
+ * @param frameDesc A reference to a `D3D11_TEXTURE2D_DESC` structure describing the texture properties, including width and height.
+ * @param darknessThreshold A floating-point value representing the threshold above which a pixel's RGB values are considered non-dark. The value ranges from 0.0f to 1.0f, with a default value of 0.1f.
+ * @return bool Returns `true` if the frame is determined to be entirely dark, otherwise returns `false`.
```
Comment (ReenigneArcher) [inline tools/ddprobe.cpp:85]: This doesn't match the comment in the code below.

```cpp
  // Frame is entirely dark
  return false;
```

File: tools/ddprobe.cpp [hunk 11]
```diff
@@ -69,8 +71,128 @@ syncThreadDesktop() {
...
+ */
+bool
+is_valid_frame(const D3D11_MAPPED_SUBRESOURCE &mappedResource, const D3D11_TEXTURE2D_DESC &frameDesc, float darknessThreshold = 0.1f) {
```
Comment (ReenigneArcher) [inline tools/ddprobe.cpp:88]: I'm not sure of the validity of this function. It's perfectly valid (and common for dedicated gamestream servers) to have a perfectly black desktop with no icons or taskbar.

File: tools/ddprobe.cpp [hunk 12]
```diff
@@ -69,8 +71,128 @@ syncThreadDesktop() {
   CloseDesktop(hDesk);
 }
 
+/**
+ * @brief Checks whether a given frame is entirely dark by evaluating the RGB values of each pixel.
+ *
+ * This function determines if the provided frame is completely dark by analyzing the RGB values of every pixel.
+ * It iterates over all pixels in the frame and compares each pixel's RGB channels to a defined darkness threshold.
+ * If any pixel's RGB values exceed this threshold, the function concludes that the frame is not entirely dark and returns `false`.
+ * If all pixels are below the threshold, indicating a completely dark frame, the function returns `true`.
```
Comment (ReenigneArcher) [inline tools/ddprobe.cpp:80]:
```suggestion
 * If all pixels are below the threshold, indicating a completely dark frame, the function returns `false`.
```

Also doesn't match the code.

Comment (Nonary) [reply tools/ddprobe.cpp:80]: Whoops, forget to AI generate the docs after making the changes

File: tools/ddprobe.cpp (hunk 11 above)
Comment (Nonary) [reply tools/ddprobe.cpp:88]: Honestly, that does not matter because the code now defaults to the old behavior if it fails the frame test. The worst that could happen is that the bug will still exist, and that those users might need to disable the iGPU or add a single non-black pixel to their background.

I’d say that situation is extremely rare and unlikely to occur.

File: tools/ddprobe.cpp [hunk 13]
```diff
@@ -69,8 +71,128 @@ syncThreadDesktop() {
...
+  *
+  * This function analyzes the provided frame to determine if it contains any pixels that exceed a specified darkness threshold.
+  * It iterates over all pixels in the frame, comparing each pixel's RGB values to the defined darkness threshold.
+  * If any pixel's RGB values exceed this threshold, the function concludes that the frame is valid (i.e., not entirely dark) and returns `true`.
+  * If all pixels are below or equal to the threshold, indicating a completely dark frame, the function returns `false`.
+
+  * @param mappedResource A reference to a `D3D11_MAPPED_SUBRESOURCE` structure containing the mapped subresource data of the frame to be analyzed.
+  * @param frameDesc A reference to a `D3D11_TEXTURE2D_DESC` structure describing the texture properties, including width and height.
+  * @param darknessThreshold A floating-point value representing the threshold above which a pixel's RGB values are considered dark. The value ranges from 0.0f to 1.0f, with a default value of 0.1f.
+  * @return bool Returns `true` if the frame contains any non-dark pixels, indicating it is valid; otherwise, returns `false`.
```
Comment (ReenigneArcher) [inline tools/ddprobe.cpp:85]:
```suggestion
  * @return Returns `true` if the frame contains any non-dark pixels, indicating it is valid; otherwise, returns `false`.
```

I forgot this in my last review. We don't specify a return type. It's automatic in doxygen and the IDE.

Applies to both cases.

File: src/platform/windows/display_base.cpp [hunk 14]
```diff
@@ -363,8 +364,10 @@ namespace platf::dxgi {
   // we spawn a helper tool to probe for us before we set our own GPU preference.
   bool
   probe_for_gpu_preference(const std::string &display_name) {
-    // If we've already been through here, there's nothing to do this time.
     static bool set_gpu_preference = false;
+    static bool verify_frame_capture = true;
```
Comment (cgutman) [inline src/platform/windows/display_base.cpp:368]: Let's just loop through both `verify_frame_capture == true` and `verify_frame_capture == false` cases here. We can't necessarily assume that the caller will invoke this function again.

**Review by cgutman — CHANGES_REQUESTED** [review]

File: tools/ddprobe.cpp [hunk 15]
```diff
@@ -69,8 +71,128 @@ syncThreadDesktop() {
...
+
+    ComPtr<IDXGIResource> frameResource;
+    DXGI_OUTDUPL_FRAME_INFO frameInfo;
+    ComPtr<ID3D11DeviceContext> context;
+    ComPtr<ID3D11Texture2D> stagingTexture;
+
+    HRESULT status = dup->AcquireNextFrame(500, &frameInfo, &frameResource);
+    device->GetImmediateContext(&context);
+
+    auto cleanup = util::fail_guard([&dup, &context, &stagingTexture]() {
```
[the remark this answers is not in the document]
Comment (Nonary) [reply tools/ddprobe.cpp]: It might be obvious now that I normally work in managed object languages... made those adjustments

File: tools/ddprobe.cpp [hunk 16]
```diff
@@ -69,8 +71,128 @@ syncThreadDesktop() {
...
+      if (stagingTexture) {
```
[the remark this answers is not in the document]
Comment (Nonary) [reply tools/ddprobe.cpp]: I believe I fixed it now

File: src/platform/windows/display_base.cpp (hunk 14 above)
Comment (Nonary) [reply src/platform/windows/display_base.cpp]: created new private method, adjusted original method to call both scenarios like suggested

**Comment by Apprisco** [comment]
Any progress on this fix? Using two RTX quad 6000s now yet still no dice.

**Comment by Nonary** [comment]
> Any progress on this fix? Using two RTX quad 6000s now yet still no dice.

Its already fixed, but not in any sunshine release because this PR has not been merged in.

If you installed a fixed version and still have issues, then it's likely you have a separate issue (such as hybrid GPU laptops), which often require you to restart Sunshine in order for the GPU selection to work again.

**Comment by cgutman** [comment]
@Nonary can you fix the compilation errors?

**Comment by Nonary** [comment]
> @Nonary can you fix the compilation errors?

done

**Comment by ReenigneArcher** [comment]
Also, we now use semantic PRs. Could you make the PR title follow the conventional commit guidelines? https://www.conventionalcommits.org/en/v1.0.0/

**Review by cgutman — APPROVED** [review]
