### PR TITLE
Fix Linux KMS capture on virtual monitors

### LINKED ISSUE #347: Unknown Monitor connector type [Virtual]
### Describe the Bug

sunshine failed to start when using virtual monitor created by amdgpu driver

### Expected Behavior

start normally

### Additional Context

```
modinfo amdgpu 
...
parm:           virtual_display:Enable virtual display feature (the virtual_display will be set like xxxx:xx:xx.x,x;xxxx:xx:xx.x,x) (charp)
...
```

### Host Operating System

Linux

### Operating System Version

linux 5.19.4

### Architecture

x86_64

### Sunshine Version

0.14.1

### GPU Type

amd

### GPU Model

navi

### GPU Driver/Mesa Version

22.3.0

### Capture Method (Linux Only)

_No response_

### Relevant log output

```Shell
Info: Found display [wayland-0]
Info: Found interface: zxdg_output_manager_v1(30) version 3
Info: Found interface: wl_output(42) version 3
Warning: Missing Wayland wire for wlr-export-dmabuf
Info: Found display [wayland-0]
Info: Found display [wayland-0]
Info: Found interface: zxdg_output_manager_v1(30) version 3
Info: Found interface: wl_output(42) version 3
Info: Offset: 0x0
Info: Resolution: 3840x2160
Info: Name: Virtual-1
Info: Found monitor:  Virtual-1-unknown
Info: Virtual-1:  Virtual-1-unknown
Error: Unknown Monitor connector type [Virtual]: Please report this to the Github issue tracker
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
The plane iterator had a bug where it would not reach the final plane in the list of planes, since it always set `plane_p` to the _next_ entry rather than the current entry. This means that `it != std::end(...)` would be false _on_ the last iteration instead of _after_ the final iteration. This bug affected all systems, but it didn't often manifest as a visible issue since the planes we're looking for are rarely the last plane in the list. However, it completely broke VKMS since it only has one plane.

I also updated the mapping of display types to `DRM_MODE_CONNECTOR_` values to silence the (red herring) warning that was also reported in #347.

### Issues Fixed or Closed
Fixes #347

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

File: src/platform/linux/kmsgrab.cpp [hunk 1]
```diff
@@ -164,19 +164,48 @@ namespace platf {
...
+      _CONVERT("VIRTUAL"sv, VIRTUAL);
+      _CONVERT("Virtual"sv, VIRTUAL);
       _CONVERT("DSI"sv, DSI);
+      _CONVERT("DPI"sv, DPI);
+      _CONVERT("WRITEBACK"sv, WRITEBACK);
+      _CONVERT("Writeback"sv, WRITEBACK);
+      _CONVERT("SPI"sv, SPI);
+#ifdef DRM_MODE_CONNECTOR_USB
+      _CONVERT("USB"sv, USB);
+#endif
```
Comment (ReenigneArcher) [inline src/platform/linux/kmsgrab.cpp:198]: Do you have a reference where this list comes from?

Comment (cgutman) [reply src/platform/linux/kmsgrab.cpp:202]: Added a comment in the code linking to the various places these came from.

**Review by ReenigneArcher — APPROVED** [review]
