### PR TITLE
fix(linux): headless monitors on wayland

### LINKED ISSUE #2955: Can't stream a headless monitor created with Hyprland
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

I'm too lazy to test

### Describe the Bug

Virtual outputs created with `hyprctl output create headless` don't seem to be recognized by Sunshine. `Error: Unknown Monitor connector type [HEADLESS]: Please report this to the GitHub issue tracker`\

### Expected Behavior

_No response_

### Additional Context

_No response_

### Host Operating System

Linux

### Operating System Version

6.10.2-arch1-1, Hyprland window manager

### Architecture

64 bit

### Sunshine commit or version

Sunshine version: 0.23.1

### Package

Linux - AUR (Third Party)

### GPU Type

Nvidia

### GPU Model

TU117

### GPU Driver/Mesa Version

nvidia-open 555.58.02-10

### Capture Method

None

### Config

```Shell
output_name = Headless output 2
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    2560x1440,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    1920x1200
]
```

### Apps

_No response_

### Relevant log output

```shell
[resolutions] -- [[
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    2560x1440,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    1920x1200
]]
[output_name] -- [Headless output 2]
[2024:08:03:23:29:21]: Info: Sunshine version: 0.23.1
[2024:08:03:23:29:21]: Info: Found display [wayland-1]
[2024:08:03:23:29:21]: Info: Found interface: zxdg_output_manager_v1(9) version 3
[2024:08:03:23:29:21]: Info: Found interface: wl_output(47) version 4
[2024:08:03:23:29:21]: Info: Found interface: wl_output(48) version 4
[2024:08:03:23:29:21]: Info: Found interface: wl_output(49) version 4
[2024:08:03:23:29:21]: Info: Found interface: wl_output(50) version 4
[2024:08:03:23:29:21]: Warning: Missing Wayland wire for wlr-export-dmabuf
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Info: Found display [wayland-1]
[2024:08:03:23:29:21]: Info: Found display [wayland-1]
[2024:08:03:23:29:21]: Info: Found interface: zxdg_output_manager_v1(9) version 3
[2024:08:03:23:29:21]: Info: Found interface: wl_output(47) version 4
[2024:08:03:23:29:21]: Info: Found interface: wl_output(48) version 4
[2024:08:03:23:29:21]: Info: Found interface: wl_output(49) version 4
[2024:08:03:23:29:21]: Info: Found interface: wl_output(50) version 4
[2024:08:03:23:29:21]: Info: Resolution: 1920x1080
[2024:08:03:23:29:21]: Info: Resolution: 1280x1024
[2024:08:03:23:29:21]: Info: Resolution: 1920x1200
[2024:08:03:23:29:21]: Info: Resolution: 1280x1024
[2024:08:03:23:29:21]: Info: Name: eDP-1
[2024:08:03:23:29:21]: Info: Found monitor: LG Display 0x05E5 (eDP-1)
[2024:08:03:23:29:21]: Info: Offset: 2560x1024
[2024:08:03:23:29:21]: Info: Logical size: 1536x864
[2024:08:03:23:29:21]: Info: Name: HDMI-A-1
[2024:08:03:23:29:21]: Info: Found monitor: BNQ BenQ FP93GS 0x00003760 (HDMI-A-1)
[2024:08:03:23:29:21]: Info: Offset: 1280x0
[2024:08:03:23:29:21]: Info: Logical size: 1280x1024
[2024:08:03:23:29:21]: Info: Name: HEADLESS-2
[2024:08:03:23:29:21]: Info: Found monitor: Headless output 2
[2024:08:03:23:29:21]: Info: Offset: 2560x256
[2024:08:03:23:29:21]: Info: Logical size: 1536x960
[2024:08:03:23:29:21]: Info: Name: HEADLESS-3
[2024:08:03:23:29:21]: Info: Found monitor: Headless output 3
[2024:08:03:23:29:21]: Info: Offset: 3789x0
[2024:08:03:23:29:21]: Info: Logical size: 1280x1024
[2024:08:03:23:29:21]: Info: -------- Start of KMS monitor list --------
[2024:08:03:23:29:21]: Info: Monitor 1 is eDP-1: LG Display 0x05E5 (eDP-1)
[2024:08:03:23:29:21]: Info: Monitor 0 is HDMI-A-1: BNQ BenQ FP93GS 0x00003760 (HDMI-A-1)
[2024:08:03:23:29:21]: Error: Unknown Monitor connector type [HEADLESS]: Please report this to the GitHub issue tracker
[2024:08:03:23:29:21]: Error: Unknown Monitor connector type [HEADLESS]: Please report this to the GitHub issue tracker
[2024:08:03:23:29:21]: Info: --------- End of KMS monitor list ---------
[2024:08:03:23:29:21]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:08:03:23:29:21]: Info: Trying encoder [nvenc]
[2024:08:03:23:29:21]: Info: Screencasting with KMS
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:21]: Info: System tray created
[2024:08:03:23:29:21]: Info: Screencasting with KMS
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:21]: Info: Encoder [nvenc] failed
[2024:08:03:23:29:21]: Info: Trying encoder [vaapi]
[2024:08:03:23:29:21]: Info: Screencasting with KMS
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:21]: Info: Screencasting with KMS
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:21]: Info: Encoder [vaapi] failed
[2024:08:03:23:29:21]: Info: Trying encoder [software]
[2024:08:03:23:29:21]: Info: Screencasting with KMS
[2024:08:03:23:29:21]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:21]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:21]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:22]: Info: Screencasting with KMS
[2024:08:03:23:29:22]: Info: /dev/dri/card0 -> nvidia-drm
[2024:08:03:23:29:22]: Info: /dev/dri/card1 -> amdgpu
[2024:08:03:23:29:22]: Error: Couldn't find monitor [-393538374]
[2024:08:03:23:29:22]: Info: Encoder [software] failed
[2024:08:03:23:29:22]: Fatal: Unable to find display or encoder during startup.
[2024:08:03:23:29:22]: Fatal: Please ensure your manually chosen GPU and monitor are connected and powered on.
[2024:08:03:23:29:22]: Error: Video failed to find working encoder
[2024:08:03:23:29:22]: Error: Failed to create client: Daemon not running
[2024:08:03:23:29:22]: Info: Configuration UI available at [https://localhost:47990]
```

### PR DESCRIPTION
**Pull request by gorgbus**
## Description
This swaps out the wrl-export-dmabuf-unstable-v1 wayland protocol in favor of wlr-screencopy-unstable-v1. Since export-dmabuf is unsupported in newer versions of hyprland and other compositors it prevents the use of headless monitors.

### Issues Fixed or Closed
- Fixes #2955

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

File: src/platform/linux/wayland.h [hunk 1]
```diff
@@ -150,36 +125,32 @@ namespace wl {
 
   public:
     enum interface_e {
-      XDG_OUTPUT,  ///< xdg-output
-      WLR_EXPORT_DMABUF,  ///< Export dmabuf
-      MAX_INTERFACES,  ///< Maximum number of interfaces
+      XDG_OUTPUT,         ///< xdg-output
+      WLR_EXPORT_DMABUF,  ///< screencopy manager
+      LINUX_DMABUF,       ///< linux-dmabuf protocol
+      MAX_INTERFACES
```
Comment (ReenigneArcher) [inline src/platform/linux/wayland.h:131]:
```suggestion
      XDG_OUTPUT,  ///< xdg-output
      WLR_EXPORT_DMABUF,  ///< screencopy manager
      LINUX_DMABUF,  ///< linux-dmabuf protocol
      MAX_INTERFACES,  ///< Maximum number of interfaces
```

We don't use aligned comments. I also know the final comment is redundant; however the docs will fail without a comment here.

**Review by ReenigneArcher — CHANGES_REQUESTED** [review]
Thank you for the PR! This is a very welcomed fix! I have a few initial comments.

There's a good amount of lint errors to be fixed: https://github.com/LizardByte/Sunshine/actions/runs/14275213838/job/40017360396?pr=3783

**Comment by ReenigneArcher** [comment]
To fix ubuntu build I think you can add `libgbm-dev` to https://github.com/LizardByte/Sunshine/blob/498e9cfa61677b51dd92e6aa6613ff3ba1a5b8ac/scripts/linux_build.sh#L94-L127

For Fedora, (I think) add `egl-gbm` here: https://github.com/LizardByte/Sunshine/blob/498e9cfa61677b51dd92e6aa6613ff3ba1a5b8ac/scripts/linux_build.sh#L156-L189

**Comment by ReenigneArcher** [comment]
Thanks for the quick fixes!

The following failures are okay to ignore:

- `CI Copr` ...  only Fedora 42 is failing, not because of this PR
- `codecov/patch` ... unless you want to add unit tests, this would be welcomed, but not required
- `CodeQL / Analyze (cpp, macos-latest)` ... not due to this PR
- `SonarCloud Code Analysis` ... will leave this up to your judgement
- `CI / Linux Flatpak (aarch64, ubuntu-22.04-arm)` ... this just fails randomly, nothing to do with this PR

The `CI / Homebrew (ubuntu-latest)` should probably be fixed though. The only idea I have on how to fix this is to add https://github.com/robclark/libgbm.git as a submodule and update the CMake to handle it, as this does not seem to be available as a homebrew package.

**Comment by gorgbus** [comment]
> The `CI / Homebrew (ubuntu-latest)` should probably be fixed though. The only idea I have on how to fix this is to add https://github.com/robclark/libgbm.git as a submodule and update the CMake to handle it, as this does not seem to be available as a homebrew package.

The gbm is part of mesa, so adding the mesa package from homebrew should be enough.

**Comment by ReenigneArcher** [comment]
@gorgbus ah, nice! In that case you can add it here: https://github.com/LizardByte/Sunshine/blob/498e9cfa61677b51dd92e6aa6613ff3ba1a5b8ac/packaging/sunshine.rb#L41-L59

**Comment by Roger-Roger-debug** [comment]
This makes the wlr capture method work for me but I haven't tried it with a headless display yet.
Is it expected that h265 doesn't work with this method/appimage?

**Comment by Kabouik** [comment]
Works fine for me on Guix with the flatpak, see: https://github.com/LizardByte/Sunshine/issues/2955#issuecomment-2781790939

Thanks!

**Review by ReenigneArcher — APPROVED** [review]

File: src/platform/linux/wayland.cpp [hunk 2]
```diff
@@ -177,106 +201,321 @@ namespace wl {
...
+    if (!init_gbm()) {
+      BOOST_LOG(error) << "Failed to initialize GBM"sv;
+      zwlr_screencopy_frame_v1_destroy(frame);
+      status = REINIT;
+      return;
+    }
+    
+    // Create GBM buffer
+    current_bo = gbm_bo_create(gbm_device, dmabuf_info.width, dmabuf_info.height,
+                             dmabuf_info.format, GBM_BO_USE_LINEAR | GBM_BO_USE_RENDERING);
```
Comment (Clutchnp) [inline src/platform/linux/wayland.cpp]: @gorgbus 
Nvidia dosen't support rendering to a linear buffer, so this will fail there

**Comment by Clutchnp** [comment]
@gorgbus  
https://github.com/LizardByte/Sunshine/blob/df4ef62ef30e8a38d773c7777a01b8df5dbff999/src/platform/linux/wayland.cpp#L379C1-L379C145 
 
 nvidia dosent support rendering to linear buffer, this will fail there, can you check

**Comment by Clutchnp** [comment]
I got to test on nvidia GPUs now and yeah with the latest changes , its working now!!

**Comment by quietvoid** [comment]
This change completely broke the rendering on my side, with Sway/wlroots stable on 10 bit output.

```
[ERROR] [wlr] [render/dmabuf_linux.c:95] drmIoctl(EXPORT_SYNC_FILE) failed: Bad file descriptor
[ERROR] [wlr] [render/vulkan/renderer.c:961] Failed to extract DMA-BUF fence
[ERROR] [wlr] [render/vulkan/pass.c:227] Failed to wait for foreign texture DMA-BUF fence
[ERROR] [wlr] [render/vulkan/texture.c:527] Format XR30 (0x30335258) can't be used with modifier INVALID (0x00FFFFFFFFFFFFFF)
[2025-04-16 09:38:37.286]: Error: Frame capture failed
```

The output in Moonlight is garbage.

**Comment by John-Gee** [comment]
Isn't ext-image-capture-source-v1 superseeding the wlr protocol? That's what I get from https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/124 Plus an official protocol is going to be more used than once originated in wlroot no?

**Comment by Quackdoc** [comment]
> Isn't ext-image-capture-source-v1 superseeding the wlr protocol? T

`ext-image-capture-source-v1` should not replace wlr protocols in the short term, there are still many compositors that will only support the wlr protocols, they should sit side by side until time has been given to allow compositors (and distros) to catch up

**Comment by John-Gee** [comment]
> > Isn't ext-image-capture-source-v1 superseeding the wlr protocol? T
> 
> `ext-image-capture-source-v1` should not replace wlr protocols in the short term, there are still many compositors that will only support the wlr protocols, they should sit side by side until time has been given to allow compositors (and distros) to catch up

I see, I appreciate the quick reply thank you!

**Comment by ReenigneArcher** [comment]
Every build is available in docker hub (pre-releases and stable)
