### PR TITLE
Provide SSSE3, AVX2, and AVX512 optimized Reed-Solomon functions

### LINKED ISSUE #2543: Segfault when connecting from an android moonlight client on Arch Linux when compiled with avx512 support
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When connecting from an android moonlight client over LAN, sunshine segfaults before any video output can occur if it is compiled with avx512f support. The same does not occur if joining from another (linux) desktop moonlight client, or if moonlight is compiled without avx512f support. 
STR:
1) add -mavx512f to the c and cxx compiler flags (CMAKE_C_FLAGS and CMAKE_CXX_FLAGS)  options in cmake
2) setup sunshine
3) (attempt to) join from an android moonlight client
4) segfault

### Expected Behavior

Moonlight should connect normally, and the application should be displayed.

### Additional Context

Looking at the backtrace of the coredump in GDB suggests the problem is in nanors. However, setting the forward error correction percentage to 0 doesn't solve the problem.

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

64 bit

### Sunshine commit or version

373390e771e503e2e2f5318770489297f1d03bbc

### Package

Linux - AUR (Third Party)

### GPU Type

Intel

### GPU Model

Intel Tigerlake (Gen12)

### GPU Driver/Mesa Version

24.0.7

### Capture Method (Linux Only)

wlroots

### Config

```Shell
upnp = enabled
lan_encryption_mode = 1
origin_web_ui_allowed = pc
channels = 3
capture = wlr
address_family = both
encoder = vaapi
```

### Apps

_No response_

### Relevant log output

```shell
[encoder] -- [vaapi ]
[address_family] -- [both]
[capture] -- [wlr]
[channels] -- [3]
[origin_web_ui_allowed] -- [pc]
[lan_encryption_mode] -- [1]
[upnp] -- [enabled]
[2024:05:19:15:11:13]: Info: Sunshine version: 0.23.1.dirty
[2024:05:19:15:11:13]: Info: Found display [wayland-1]
[2024:05:19:15:11:13]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:13]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:13]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:13]: Info: Resolution: 2256x1504
[2024:05:19:15:11:13]: Info: Name: eDP-1
[2024:05:19:15:11:13]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:13]: Info: Offset: 1920x0
[2024:05:19:15:11:13]: Info: Logical size: 1128x752
[2024:05:19:15:11:13]: Info: -------- Start of Wayland monitor list --------
[2024:05:19:15:11:13]: Info: Monitor 0 is eDP-1: BOE 0x095F (eDP-1)
[2024:05:19:15:11:13]: Info: --------- End of Wayland monitor list ---------
[2024:05:19:15:11:13]: Error: Couldn't find any working encoder matching [vaapi ]
[2024:05:19:15:11:13]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:05:19:15:11:13]: Info: Trying encoder [nvenc]
[2024:05:19:15:11:13]: Info: Screencasting with Wayland's protocol
[2024:05:19:15:11:13]: Info: Found display [wayland-1]
[2024:05:19:15:11:13]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:13]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:13]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:13]: Info: Resolution: 2256x1504
[2024:05:19:15:11:13]: Info: Name: eDP-1
[2024:05:19:15:11:13]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:13]: Info: Offset: 1920x0
[2024:05:19:15:11:13]: Info: Logical size: 1128x752
[2024:05:19:15:11:13]: Info: Selected monitor [BOE 0x095F (eDP-1)] for streaming
[2024:05:19:15:11:13]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:13]: Info: Color depth: 8-bit
[2024:05:19:15:11:13]: Info: Color range: [JPEG]
[2024:05:19:15:11:13]: Error: [AVHWDeviceContext @ 0x5e78dbe50640] Cannot load libcuda.so.1
[2024:05:19:15:11:13]: Error: [AVHWDeviceContext @ 0x5e78dbe50640] Could not dynamically load CUDA
[2024:05:19:15:11:13]: Error: Failed to create a CUDA device: Operation not permitted
[2024:05:19:15:11:13]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:13]: Info: Color depth: 8-bit
[2024:05:19:15:11:13]: Info: Color range: [JPEG]
[2024:05:19:15:11:13]: Error: [AVHWDeviceContext @ 0x5e78dbe51d40] Cannot load libcuda.so.1
[2024:05:19:15:11:13]: Error: [AVHWDeviceContext @ 0x5e78dbe51d40] Could not dynamically load CUDA
[2024:05:19:15:11:13]: Error: Failed to create a CUDA device: Operation not permitted
[2024:05:19:15:11:13]: Info: Encoder [nvenc] failed
[2024:05:19:15:11:13]: Info: Trying encoder [vaapi]
[2024:05:19:15:11:13]: Info: Screencasting with Wayland's protocol
[2024:05:19:15:11:13]: Info: Found display [wayland-1]
[2024:05:19:15:11:13]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:13]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:13]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:13]: Info: Resolution: 2256x1504
[2024:05:19:15:11:13]: Info: Name: eDP-1
[2024:05:19:15:11:13]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:13]: Info: Offset: 1920x0
[2024:05:19:15:11:13]: Info: Logical size: 1128x752
[2024:05:19:15:11:13]: Info: Selected monitor [BOE 0x095F (eDP-1)] for streaming
[2024:05:19:15:11:13]: Info: System tray created
[2024:05:19:15:11:13]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:13]: Info: Color depth: 8-bit
[2024:05:19:15:11:13]: Info: Color range: [JPEG]
[2024:05:19:15:11:13]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:13]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:13]: Info: Color depth: 8-bit
[2024:05:19:15:11:13]: Info: Color range: [JPEG]
[2024:05:19:15:11:13]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:13]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:13]: Info: Color depth: 8-bit
[2024:05:19:15:11:13]: Info: Color range: [JPEG]
[2024:05:19:15:11:13]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:13]: Error: [av1_vaapi @ 0x5e78dbf8c340] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:05:19:15:11:13]: Info: Retrying with fallback configuration options for [av1_vaapi] after error: Function not implemented
[2024:05:19:15:11:13]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:13]: Error: [av1_vaapi @ 0x5e78dc8c0680] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:05:19:15:11:13]: Error: Could not open codec [av1_vaapi]: Function not implemented
[2024:05:19:15:11:13]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:13]: Info: Color depth: 8-bit
[2024:05:19:15:11:13]: Info: Color range: [JPEG]
[2024:05:19:15:11:13]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:13]: Error: [av1_vaapi @ 0x5e78dc052b80] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:05:19:15:11:13]: Info: Retrying with fallback configuration options for [av1_vaapi] after error: Function not implemented
[2024:05:19:15:11:13]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:13]: Error: [av1_vaapi @ 0x5e78dc8c0680] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:05:19:15:11:13]: Error: Could not open codec [av1_vaapi]: Function not implemented
[2024:05:19:15:11:13]: Info: Screencasting with Wayland's protocol
[2024:05:19:15:11:13]: Info: Found display [wayland-1]
[2024:05:19:15:11:13]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:13]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:13]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:13]: Info: Resolution: 2256x1504
[2024:05:19:15:11:13]: Info: Name: eDP-1
[2024:05:19:15:11:13]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:13]: Info: Offset: 1920x0
[2024:05:19:15:11:13]: Info: Logical size: 1128x752
[2024:05:19:15:11:13]: Info: Selected monitor [BOE 0x095F (eDP-1)] for streaming
[2024:05:19:15:11:13]: Info: SDR color coding [Rec. 709]
[2024:05:19:15:11:13]: Info: Color depth: 10-bit
[2024:05:19:15:11:13]: Info: Color range: [JPEG]
[2024:05:19:15:11:13]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:13]: Info:
[2024:05:19:15:11:13]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:05:19:15:11:13]: Info:
[2024:05:19:15:11:13]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2024:05:19:15:11:13]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2024:05:19:15:11:13]: Info: Adding avahi service Sunshine
[2024:05:19:15:11:13]: Info: Configuration UI available at [https://localhost:47990]
[2024:05:19:15:11:14]: Info: Avahi service Sunshine successfully established.
[2024:05:19:15:11:15]: Error: Failed to map TCP 48010: 501
[2024:05:19:15:11:15]: Error: Failed to map UDP 47998: 501
[2024:05:19:15:11:15]: Error: Failed to map UDP 48000: 501
[2024:05:19:15:11:15]: Error: Failed to map UDP 47999: 501
[2024:05:19:15:11:15]: Error: Failed to map TCP 47989: 501
[2024:05:19:15:11:15]: Error: Failed to map TCP 47984: 501
[2024:05:19:15:11:15]: Info: Completed UPnP port mappings to 192.168.1.226 via http://192.168.1.1:5000/rootDesc.xml
[2024:05:19:15:11:19]: Error: Couldn't find any working encoder matching [vaapi ]
[2024:05:19:15:11:19]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:05:19:15:11:19]: Info: Trying encoder [nvenc]
[2024:05:19:15:11:19]: Info: Screencasting with Wayland's protocol
[2024:05:19:15:11:19]: Info: Found display [wayland-1]
[2024:05:19:15:11:19]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:19]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:19]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:19]: Info: Resolution: 2256x1504
[2024:05:19:15:11:19]: Info: Name: eDP-1
[2024:05:19:15:11:19]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:19]: Info: Offset: 1920x0
[2024:05:19:15:11:19]: Info: Logical size: 1128x752
[2024:05:19:15:11:19]: Info: Selected monitor [BOE 0x095F (eDP-1)] for streaming
[2024:05:19:15:11:19]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:19]: Info: Color depth: 8-bit
[2024:05:19:15:11:19]: Info: Color range: [JPEG]
[2024:05:19:15:11:19]: Error: [AVHWDeviceContext @ 0x7c47d8032500] Cannot load libcuda.so.1
[2024:05:19:15:11:19]: Error: [AVHWDeviceContext @ 0x7c47d8032500] Could not dynamically load CUDA
[2024:05:19:15:11:19]: Error: Failed to create a CUDA device: Operation not permitted
[2024:05:19:15:11:19]: Info: Encoder [nvenc] failed
[2024:05:19:15:11:19]: Info: Trying encoder [vaapi]
[2024:05:19:15:11:19]: Info: Screencasting with Wayland's protocol
[2024:05:19:15:11:19]: Info: Found display [wayland-1]
[2024:05:19:15:11:19]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:19]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:19]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:19]: Info: Resolution: 2256x1504
[2024:05:19:15:11:19]: Info: Name: eDP-1
[2024:05:19:15:11:19]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:19]: Info: Offset: 1920x0
[2024:05:19:15:11:19]: Info: Logical size: 1128x752
[2024:05:19:15:11:19]: Info: Selected monitor [BOE 0x095F (eDP-1)] for streaming
[2024:05:19:15:11:19]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:19]: Info: Color depth: 8-bit
[2024:05:19:15:11:19]: Info: Color range: [JPEG]
[2024:05:19:15:11:19]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:19]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:19]: Info: Color depth: 8-bit
[2024:05:19:15:11:19]: Info: Color range: [JPEG]
[2024:05:19:15:11:19]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:19]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:19]: Info: Color depth: 8-bit
[2024:05:19:15:11:19]: Info: Color range: [JPEG]
[2024:05:19:15:11:19]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:19]: Error: [av1_vaapi @ 0x7c47d8012380] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:05:19:15:11:19]: Info: Retrying with fallback configuration options for [av1_vaapi] after error: Function not implemented
[2024:05:19:15:11:19]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:19]: Error: [av1_vaapi @ 0x7c47d8e54240] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:05:19:15:11:19]: Error: Could not open codec [av1_vaapi]: Function not implemented
[2024:05:19:15:11:19]: Info: SDR color coding [Rec. 601]
[2024:05:19:15:11:19]: Info: Color depth: 8-bit
[2024:05:19:15:11:19]: Info: Color range: [JPEG]
[2024:05:19:15:11:19]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:19]: Error: [av1_vaapi @ 0x7c47d85b3880] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:05:19:15:11:19]: Info: Retrying with fallback configuration options for [av1_vaapi] after error: Function not implemented
[2024:05:19:15:11:19]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:19]: Error: [av1_vaapi @ 0x7c47d8e54240] No usable encoding entrypoint found for profile VAProfileAV1Profile0 (32).
[2024:05:19:15:11:19]: Error: Could not open codec [av1_vaapi]: Function not implemented
[2024:05:19:15:11:19]: Info: Screencasting with Wayland's protocol
[2024:05:19:15:11:19]: Info: Found display [wayland-1]
[2024:05:19:15:11:19]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:19]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:19]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:19]: Info: Resolution: 2256x1504
[2024:05:19:15:11:19]: Info: Name: eDP-1
[2024:05:19:15:11:19]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:19]: Info: Offset: 1920x0
[2024:05:19:15:11:19]: Info: Logical size: 1128x752
[2024:05:19:15:11:19]: Info: Selected monitor [BOE 0x095F (eDP-1)] for streaming
[2024:05:19:15:11:19]: Info: SDR color coding [Rec. 709]
[2024:05:19:15:11:19]: Info: Color depth: 10-bit
[2024:05:19:15:11:19]: Info: Color range: [JPEG]
[2024:05:19:15:11:19]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
[2024:05:19:15:11:19]: Info:
[2024:05:19:15:11:19]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:05:19:15:11:19]: Info:
[2024:05:19:15:11:19]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2024:05:19:15:11:19]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2024:05:19:15:11:19]: Info: Executing [Desktop]
[2024:05:19:15:11:19]: Info: Video encryption enabled
[2024:05:19:15:11:19]: Info: CLIENT CONNECTED
[2024:05:19:15:11:19]: Info: Found display [wayland-1]
[2024:05:19:15:11:19]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:19]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:19]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:19]: Info: Resolution: 2256x1504
[2024:05:19:15:11:19]: Info: Name: eDP-1
[2024:05:19:15:11:19]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:19]: Info: Offset: 1920x0
[2024:05:19:15:11:19]: Info: Logical size: 1128x752
[2024:05:19:15:11:19]: Info: -------- Start of Wayland monitor list --------
[2024:05:19:15:11:19]: Info: Monitor 0 is eDP-1: BOE 0x095F (eDP-1)
[2024:05:19:15:11:19]: Info: --------- End of Wayland monitor list ---------
[2024:05:19:15:11:19]: Info: Screencasting with Wayland's protocol
[2024:05:19:15:11:19]: Info: Found display [wayland-1]
[2024:05:19:15:11:19]: Info: Found interface: zxdg_output_manager_v1(7) version 3
[2024:05:19:15:11:19]: Info: Found interface: zwlr_export_dmabuf_manager_v1(26) version 1
[2024:05:19:15:11:19]: Info: Found interface: wl_output(48) version 4
[2024:05:19:15:11:19]: Info: Resolution: 2256x1504
[2024:05:19:15:11:19]: Info: Name: eDP-1
[2024:05:19:15:11:19]: Info: Found monitor: BOE 0x095F (eDP-1)
[2024:05:19:15:11:19]: Info: Offset: 1920x0
[2024:05:19:15:11:19]: Info: Logical size: 1128x752
[2024:05:19:15:11:19]: Info: Selected monitor [BOE 0x095F (eDP-1)] for streaming
[2024:05:19:15:11:19]: Info: SDR color coding [Rec. 709]
[2024:05:19:15:11:19]: Info: Color depth: 8-bit
[2024:05:19:15:11:19]: Info: Color range: [MPEG]
[2024:05:19:15:11:19]: Info: vaapi vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
I spun this out of #2803 when it became evident that the simple solution of just adding `-mssse3` wouldn't work.

This implementation uses GCC support for function targets to compile the Reed-Solomon code multiple times for SSSE3, AVX2, AVX512, and the default ISA flags. It provides a faster implementation than just hardcoding `-mssse3` while also not breaking non-x86 architectures or older x86 CPUs without SSSE3. It's definitely more complex than a compiler flag, but I think the performance gain is worth it and the complexity is pretty compartmentalized to `rswrapper.h/c`.

On my Ryzen 5950X, AVX2 is about 2x faster than SSSE3 which is about 4x faster than the C variant.

```
Samples: 3K of event 'cycles:P', 4000 Hz, Event count (approx.): 1243747209 lost: 0/0 drop: 0/0
Overhead  Shared Object                  Symbol
   7.28%  sunshine-0.0.0.29410c64.dirty  [.] obl_axpy_avx2.part.0
```
```
Samples: 9K of event 'cycles:P', 4000 Hz, Event count (approx.): 3392272030 lost: 0/0 drop: 0/0
Overhead  Shared Object                  Symbol
  14.14%  sunshine-0.0.0.29410c64.dirty  [.] reed_solomon_encode_ssse3
```
```
Samples: 5K of event 'cycles:P', 4000 Hz, Event count (approx.): 3762589726 lost: 0/0 drop: 0/0
Overhead  Shared Object                  Symbol
  59.20%  sunshine-0.0.0.29410c64.dirty  [.] reed_solomon_encode_def
```

### Issues Fixed or Closed
Fixes #2543 

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by moi952** [comment]
Hi, I did some research and this ticket helps optimize network encoding and transmission latency?
Thanks

File: src/rswrapper.h [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+#define reed_solomon_release reed_solomon_release_fn
+#define reed_solomon_encode reed_solomon_encode_fn
+#define reed_solomon_decode reed_solomon_decode_fn
+
+/**
+ * @brief This initializes the RS function pointers to the best vectorized version available.
+ * @details The streaming code will directly invoke these function pointers during encoding.
+ */
+void
+reed_solomon_init(void);
```
Comment (ReenigneArcher) [inline src/rswrapper.h:32]: nit:

```suggestion
reed_solomon_init(void);

```

File: cmake/compile_definitions/common.cmake [hunk 2]
```diff
@@ -108,6 +106,8 @@ set(SUNSHINE_TARGET_FILES
         "${CMAKE_SOURCE_DIR}/src/round_robin.h"
         "${CMAKE_SOURCE_DIR}/src/stat_trackers.h"
         "${CMAKE_SOURCE_DIR}/src/stat_trackers.cpp"
+        "${CMAKE_SOURCE_DIR}/src/rswrapper.h"
+        "${CMAKE_SOURCE_DIR}/src/rswrapper.c"
```
Comment (ReenigneArcher) [inline cmake/compile_definitions/common.cmake:110]: nit: Could these be placed alphabetically?

Comment (cgutman) [reply cmake/compile_definitions/common.cmake:110]: Should I reorder them all? The list order currently looks arbitrary.

Comment (ReenigneArcher) [reply cmake/compile_definitions/common.cmake:110]: Oh, I didn't expand the code when I made this comment. It's fine as is. I think we'll do a glob pattern in the future to make it easier.

**Comment by sleepybishop** [comment]
Nice work on the runtime detection. There are better ways to implement axpy in AVX512 with GFNI but I have not done much error correcting work lately. I'm eager to revisit it soon as there's many advancements I'd like to read up on in greater detail.

Would you happen to have any metrics around shard counts ? Eg. A histogram of data and repair shards counts.
