### PR TITLE
bugfix: fixed an issue that caused SUNSHINE_CLIENT_HDR to always be false

### LINKED ISSUE #1536: Client HDR env variable is always false
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The new feature in Sunshine nightly where it passes client information such as HDR is currently bugged and always says HDR is false even when clients have it enabled.

### Expected Behavior

That it matches with the client setting.

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.20

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Capture Method (Linux Only)

_No response_

### Config

```Shell
N/A
```

### Apps

_No response_

### Relevant log output

```shell
N/A
```

### PR DESCRIPTION
**Pull request by Nonary**
## Description
Fixes an issue that caused the SUNSHINE_CLIENT_HDR setting to be always false.

### Issues Fixed or Closed
- Fixes #1536 

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

File: src/nvhttp.cpp [hunk 1]
```diff
@@ -287,7 +287,7 @@ namespace nvhttp {
     launch_session.enable_sops = util::from_view(get_arg(args, "sops", "0"));
     launch_session.surround_info = util::from_view(get_arg(args, "surroundAudioInfo", "196610"));
     launch_session.gcmap = util::from_view(get_arg(args, "gcmap", "0"));
-    launch_session.enable_hdr = util::from_view(get_arg(args, "enableHdr", "0"));
+    launch_session.enable_hdr = util::from_view(get_arg(args, "hdrMode", "0"));
 
     uint32_t prepend_iv = util::endian::big<uint32_t>(util::from_view(get_arg(args, "rikeyid")));
```
Comment (cgutman) [inline src/nvhttp.cpp:292]: Can you remove the error log below while you're making changes here? I think it's a leftover debugging artifact.
