### PR TITLE
fix(linux/xdgportal): Properly support multiple screens by exposing pipewire streams as separate displays

### LINKED ISSUE #4914: XDG portalgrab with multiple displays squishes all into one stream
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

a7ab814f746b932168b90a9a12f61358f4471409 makes XDG Portalgrab unusable with multiple displays (at least on KDE Plasma/KWin 6.6.3, tested on my end) as all of the monitors are streamed at once and squished together aligned with the display configuration (e.g. stretched displays are stream side by side as one monitor). 

Also when initializing a new portal_token (deleting ~/.config/sunshine/portal_token and restarting) now longer brings up a screen selection instead there is just an approve/deny for the whole desktop as it is now remote desktop streaming the whole thing after the changes in a7ab814f746b932168b90a9a12f61358f4471409.

### Expected Behavior

There's two possible options here (the latter being preferable due to making XDG portal grab on-par with KMS capture):
- to be able to select which screen to share as previously in KWin (before a7ab814f746b932168b90a9a12f61358f4471409) 
- to have XDG portal grab behave like KMS capture does and just stream one monitor with the option to select which monitor to stream by using keyboard shortcuts (CTRL-ALT-[1-9]+). This would require the new permissions from a7ab814f746b932168b90a9a12f61358f4471409 for full remote desktop capturing but also to split the captured stream into it's single monitors and just sending the currently selected one which it currently does not.

### Additional Context

Tested on CachyOS latest with sunshine-beta-bin Packages from AUR on KDE Plasma/KWin 6.6.3. 

### Host Operating System

Linux

### Operating System Version

CachyOS

### Architecture

amd64/x86_64

### Package

Linux - AUR (Third Party)

### GPU Type

AMD

### GPU Model

RX9070XT

### GPU Driver/Mesa Version

26.0.3

### Capture Method

XDG Portal Grab (Linux)

### Apps

```json

```

### Log output

```shell
[2026-03-27 08:27:50.093915] [0x00007fcd1d1a1000] [info]    config: 'sunshine_name' = DESKTOP
[2026-03-27 08:27:50.093934] [0x00007fcd1d1a1000] [info]    config: 'minimum_fps_target' = 30
[2026-03-27 08:27:50.093937] [0x00007fcd1d1a1000] [info]    config: 'lan_encryption_mode' = 0
[2026-03-27 08:27:50.093939] [0x00007fcd1d1a1000] [info]    config: 'hevc_mode' = 0
[2026-03-27 08:27:50.093941] [0x00007fcd1d1a1000] [info]    config: 'encoder' = vaapi
[2026-03-27 08:27:50.093943] [0x00007fcd1d1a1000] [info]    config: 'ds5_inputtino_randomize_mac' = false
[2026-03-27 08:27:50.093945] [0x00007fcd1d1a1000] [info]    config: 'av1_mode' = 0
[2026-03-27 08:27:50.093947] [0x00007fcd1d1a1000] [info]    config: 'stream_audio' = true
[2026-03-27 08:27:50.093949] [0x00007fcd1d1a1000] [info]    config: 'capture' = portal
[2026-03-27 08:27:50.093951] [0x00007fcd1d1a1000] [info]    config: 'address_family' = both
[2026-03-27 08:27:50.094]: Info: Sunshine version: 2026.323.224448 commit: 4126e18f20eda8d61a92f51caf8cb6125435b68e
[2026-03-27 08:27:50.094]: Info: Package Publisher: LizardByte
[2026-03-27 08:27:50.094]: Info: Publisher Website: https://app.lizardbyte.dev
[2026-03-27 08:27:50.094]: Info: Get support: https://app.lizardbyte.dev/support
[2026-03-27 08:27:50.094]: Info: config: 'address_family' = both
[2026-03-27 08:27:50.094]: Info: config: 'capture' = portal
[2026-03-27 08:27:50.094]: Info: config: 'stream_audio' = true
[2026-03-27 08:27:50.094]: Info: config: 'av1_mode' = 0
[2026-03-27 08:27:50.094]: Info: config: 'ds5_inputtino_randomize_mac' = false
[2026-03-27 08:27:50.094]: Info: config: 'encoder' = vaapi
[2026-03-27 08:27:50.094]: Info: config: 'hevc_mode' = 0
[2026-03-27 08:27:50.094]: Info: config: 'lan_encryption_mode' = 0
[2026-03-27 08:27:50.094]: Info: config: 'minimum_fps_target' = 30
[2026-03-27 08:27:50.094]: Info: config: 'sunshine_name' = DESKTOP-L
[2026-03-27 08:27:50.094]: Info: Loaded portal restore token from disk
[2026-03-27 08:27:50.204]: Info: Trying encoder [vaapi]
[2026-03-27 08:27:50.204]: Info: Screencasting with XDG portal
[2026-03-27 08:27:50.204]: Info: Requested frame rate [60/1, approx. 60 fps]
[2026-03-27 08:27:50.204]: Info: [wayland] Found display [wayland-0]
[2026-03-27 08:27:50.213]: Info: Loaded portal restore token from disk
[2026-03-27 08:27:50.232]: Info: Connected to pipewire version 1.6.2
[2026-03-27 08:27:50.234]: Info: Video format: 12
[2026-03-27 08:27:50.234]: Info: Size: 3840x1080
[2026-03-27 08:27:50.234]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:50.234]: Info: using DMA-BUF buffers
[2026-03-27 08:27:50.235]: Info: Video format: 12
[2026-03-27 08:27:50.235]: Info: Size: 3840x1080
[2026-03-27 08:27:50.235]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:50.235]: Info: using DMA-BUF buffers
[2026-03-27 08:27:50.242]: Info: Creating encoder [h264_vaapi]
[2026-03-27 08:27:50.242]: Info: Color coding: SDR (Rec. 601)
[2026-03-27 08:27:50.242]: Info: Color depth: 8-bit
[2026-03-27 08:27:50.242]: Info: Color range: JPEG
[2026-03-27 08:27:50.248]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:50.253]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:50.253]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:50.253]: Info: Using normal encoding mode
[2026-03-27 08:27:50.253]: Info: Using default rate control
[2026-03-27 08:27:50.273]: Info: Creating encoder [hevc_vaapi]
[2026-03-27 08:27:50.273]: Info: Color coding: SDR (Rec. 601)
[2026-03-27 08:27:50.273]: Info: Color depth: 8-bit
[2026-03-27 08:27:50.273]: Info: Color range: JPEG
[2026-03-27 08:27:50.280]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:50.286]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:50.286]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:50.286]: Info: Using normal encoding mode
[2026-03-27 08:27:50.286]: Info: Using default rate control
[2026-03-27 08:27:50.301]: Info: Creating encoder [av1_vaapi]
[2026-03-27 08:27:50.301]: Info: Color coding: SDR (Rec. 601)
[2026-03-27 08:27:50.301]: Info: Color depth: 8-bit
[2026-03-27 08:27:50.301]: Info: Color range: JPEG
[2026-03-27 08:27:50.307]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:50.310]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:50.310]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:50.310]: Info: Using normal encoding mode
[2026-03-27 08:27:50.310]: Info: Using VBR with single frame VBV size
[2026-03-27 08:27:50.310]: Warning: [av1_vaapi @ 0x55b819fc2040] Multiple slices were requested but this codec does not support controlling slices.
[2026-03-27 08:27:50.323]: Info: Screencasting with XDG portal
[2026-03-27 08:27:50.323]: Info: Requested frame rate [60/1, approx. 60 fps]
[2026-03-27 08:27:50.323]: Info: [wayland] Found display [wayland-0]
[2026-03-27 08:27:50.332]: Info: Loaded portal restore token from disk
[2026-03-27 08:27:50.350]: Info: Connected to pipewire version 1.6.2
[2026-03-27 08:27:50.352]: Info: Video format: 12
[2026-03-27 08:27:50.352]: Info: Size: 3840x1080
[2026-03-27 08:27:50.352]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:50.352]: Info: using DMA-BUF buffers
[2026-03-27 08:27:50.353]: Info: Video format: 12
[2026-03-27 08:27:50.353]: Info: Size: 3840x1080
[2026-03-27 08:27:50.353]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:50.353]: Info: using DMA-BUF buffers
[2026-03-27 08:27:50.360]: Info: Creating encoder [hevc_vaapi]
[2026-03-27 08:27:50.360]: Info: Color coding: SDR (Rec. 709)
[2026-03-27 08:27:50.360]: Info: Color depth: 10-bit
[2026-03-27 08:27:50.360]: Info: Color range: JPEG
[2026-03-27 08:27:50.366]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:50.370]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:50.371]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:50.371]: Info: Using normal encoding mode
[2026-03-27 08:27:50.371]: Info: Using default rate control
[2026-03-27 08:27:50.385]: Info: Creating encoder [av1_vaapi]
[2026-03-27 08:27:50.385]: Info: Color coding: SDR (Rec. 709)
[2026-03-27 08:27:50.385]: Info: Color depth: 10-bit
[2026-03-27 08:27:50.385]: Info: Color range: JPEG
[2026-03-27 08:27:50.391]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:50.394]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:50.394]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:50.394]: Info: Using normal encoding mode
[2026-03-27 08:27:50.394]: Info: Using VBR with single frame VBV size
[2026-03-27 08:27:50.394]: Warning: [av1_vaapi @ 0x55b819fc2040] Multiple slices were requested but this codec does not support controlling slices.
[2026-03-27 08:27:50.408]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2026-03-27 08:27:50.408]: Info:
[2026-03-27 08:27:50.408]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2026-03-27 08:27:50.408]: Info:
[2026-03-27 08:27:50.408]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2026-03-27 08:27:50.408]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2026-03-27 08:27:50.408]: Info: Found AV1 encoder: av1_vaapi [vaapi]
[2026-03-27 08:27:50.409]: Info: Starting system tray
[2026-03-27 08:27:50.410]: Info: Adding avahi service desktop
[2026-03-27 08:27:50.410]: Info: Configuration UI available at [https://localhost:47990]
libayatana-appindicator is deprecated. Please use libayatana-appindicator-glib in newly written code.
[2026-03-27 08:27:50.434]: Info: System tray created
[2026-03-27 08:27:50.434]: Info: Starting main loop
[2026-03-27 08:27:51.237]: Info: Avahi service desktop successfully established.
[2026-03-27 08:27:59.254]: Info: Trying encoder [vaapi]
[2026-03-27 08:27:59.254]: Info: Screencasting with XDG portal
[2026-03-27 08:27:59.255]: Info: Requested frame rate [60/1, approx. 60 fps]
[2026-03-27 08:27:59.255]: Info: [wayland] Found display [wayland-0]
[2026-03-27 08:27:59.263]: Info: Loaded portal restore token from disk
[2026-03-27 08:27:59.286]: Info: Connected to pipewire version 1.6.2
[2026-03-27 08:27:59.288]: Info: Video format: 12
[2026-03-27 08:27:59.288]: Info: Size: 3840x1080
[2026-03-27 08:27:59.288]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:59.288]: Info: using DMA-BUF buffers
[2026-03-27 08:27:59.289]: Info: Video format: 12
[2026-03-27 08:27:59.289]: Info: Size: 3840x1080
[2026-03-27 08:27:59.289]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:59.289]: Info: using DMA-BUF buffers
[2026-03-27 08:27:59.296]: Info: Creating encoder [h264_vaapi]
[2026-03-27 08:27:59.296]: Info: Color coding: SDR (Rec. 601)
[2026-03-27 08:27:59.296]: Info: Color depth: 8-bit
[2026-03-27 08:27:59.296]: Info: Color range: JPEG
[2026-03-27 08:27:59.302]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:59.306]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:59.306]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:59.306]: Info: Using normal encoding mode
[2026-03-27 08:27:59.306]: Info: Using default rate control
[2026-03-27 08:27:59.324]: Info: Creating encoder [hevc_vaapi]
[2026-03-27 08:27:59.324]: Info: Color coding: SDR (Rec. 601)
[2026-03-27 08:27:59.324]: Info: Color depth: 8-bit
[2026-03-27 08:27:59.324]: Info: Color range: JPEG
[2026-03-27 08:27:59.329]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:59.334]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:59.335]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:59.335]: Info: Using normal encoding mode
[2026-03-27 08:27:59.335]: Info: Using default rate control
[2026-03-27 08:27:59.347]: Info: Creating encoder [av1_vaapi]
[2026-03-27 08:27:59.347]: Info: Color coding: SDR (Rec. 601)
[2026-03-27 08:27:59.347]: Info: Color depth: 8-bit
[2026-03-27 08:27:59.347]: Info: Color range: JPEG
[2026-03-27 08:27:59.352]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:59.355]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:59.355]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:59.355]: Info: Using normal encoding mode
[2026-03-27 08:27:59.355]: Info: Using VBR with single frame VBV size
[2026-03-27 08:27:59.355]: Warning: [av1_vaapi @ 0x7fccc405bcc0] Multiple slices were requested but this codec does not support controlling slices.
[2026-03-27 08:27:59.367]: Info: Screencasting with XDG portal
[2026-03-27 08:27:59.367]: Info: Requested frame rate [60/1, approx. 60 fps]
[2026-03-27 08:27:59.367]: Info: [wayland] Found display [wayland-0]
[2026-03-27 08:27:59.375]: Info: Loaded portal restore token from disk
[2026-03-27 08:27:59.393]: Info: Connected to pipewire version 1.6.2
[2026-03-27 08:27:59.395]: Info: Video format: 12
[2026-03-27 08:27:59.395]: Info: Size: 3840x1080
[2026-03-27 08:27:59.395]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:59.395]: Info: using DMA-BUF buffers
[2026-03-27 08:27:59.395]: Info: Video format: 12
[2026-03-27 08:27:59.395]: Info: Size: 3840x1080
[2026-03-27 08:27:59.395]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:59.395]: Info: using DMA-BUF buffers
[2026-03-27 08:27:59.402]: Info: Creating encoder [hevc_vaapi]
[2026-03-27 08:27:59.402]: Info: Color coding: SDR (Rec. 709)
[2026-03-27 08:27:59.402]: Info: Color depth: 10-bit
[2026-03-27 08:27:59.402]: Info: Color range: JPEG
[2026-03-27 08:27:59.408]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:59.412]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:59.413]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:59.413]: Info: Using normal encoding mode
[2026-03-27 08:27:59.413]: Info: Using default rate control
[2026-03-27 08:27:59.427]: Info: Creating encoder [av1_vaapi]
[2026-03-27 08:27:59.427]: Info: Color coding: SDR (Rec. 709)
[2026-03-27 08:27:59.427]: Info: Color depth: 10-bit
[2026-03-27 08:27:59.427]: Info: Color range: JPEG
[2026-03-27 08:27:59.432]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:59.435]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:59.436]: Info: Streaming bitrate is 1000000
[2026-03-27 08:27:59.436]: Info: Using normal encoding mode
[2026-03-27 08:27:59.436]: Info: Using VBR with single frame VBV size
[2026-03-27 08:27:59.436]: Warning: [av1_vaapi @ 0x7fccc4055000] Multiple slices were requested but this codec does not support controlling slices.
[2026-03-27 08:27:59.447]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2026-03-27 08:27:59.447]: Info:
[2026-03-27 08:27:59.447]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2026-03-27 08:27:59.447]: Info:
[2026-03-27 08:27:59.447]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2026-03-27 08:27:59.447]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2026-03-27 08:27:59.447]: Info: Found AV1 encoder: av1_vaapi [vaapi]
[2026-03-27 08:27:59.447]: Info: Executing [Desktop]
[2026-03-27 08:27:59.514]: Info: New streaming session started [active sessions: 1]
[2026-03-27 08:27:59.536]: Info: CLIENT CONNECTED
[2026-03-27 08:27:59.612]: Info: Loaded portal restore token from disk
[2026-03-27 08:27:59.613]: Info: Screencasting with XDG portal
[2026-03-27 08:27:59.613]: Info: Requested frame rate [60/1, approx. 60 fps]
[2026-03-27 08:27:59.613]: Info: [wayland] Found display [wayland-0]
[2026-03-27 08:27:59.622]: Info: Loaded portal restore token from disk
[2026-03-27 08:27:59.645]: Info: Connected to pipewire version 1.6.2
[2026-03-27 08:27:59.647]: Info: Video format: 12
[2026-03-27 08:27:59.647]: Info: Size: 3840x1080
[2026-03-27 08:27:59.647]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:59.647]: Info: using DMA-BUF buffers
[2026-03-27 08:27:59.648]: Info: Video format: 12
[2026-03-27 08:27:59.648]: Info: Size: 3840x1080
[2026-03-27 08:27:59.648]: Info: Framerate (from compositor): 0/1 (variable rate capture)
[2026-03-27 08:27:59.648]: Info: using DMA-BUF buffers
[2026-03-27 08:27:59.654]: Info: Creating encoder [hevc_vaapi]
[2026-03-27 08:27:59.654]: Info: Color coding: SDR (Rec. 709)
[2026-03-27 08:27:59.654]: Info: Color depth: 8-bit
[2026-03-27 08:27:59.654]: Info: Color range: MPEG
[2026-03-27 08:27:59.661]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:27:59.666]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:27:59.666]: Info: Streaming bitrate is 3428000
[2026-03-27 08:27:59.666]: Info: Using normal encoding mode
[2026-03-27 08:27:59.666]: Info: Using default rate control
[2026-03-27 08:27:59.672]: Info: Minimum FPS target set to ~15fps (66.6667ms)
[2026-03-27 08:28:00.001]: Info: Setting default sink to: [sink-sunshine-stereo]
[2026-03-27 08:28:00.002]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2026-03-27 08:28:00.029]: Info: Opus initialized: 48 kHz, 2 channels, 96 kbps (total), LOWDELAY
[2026-03-27 08:28:10.778]: Info: New streaming session started [active sessions: 2]
[2026-03-27 08:28:10.785]: Info: CLIENT CONNECTED
[2026-03-27 08:28:10.858]: Info: Creating encoder [h264_vaapi]
[2026-03-27 08:28:10.858]: Info: Color coding: SDR (Rec. 709)
[2026-03-27 08:28:10.858]: Info: Color depth: 8-bit
[2026-03-27 08:28:10.858]: Info: Color range: MPEG
[2026-03-27 08:28:10.863]: Warning: EGL: context priority set to HIGH but CAP_SYS_NICE capability is missing
[2026-03-27 08:28:10.867]: Info: vaapi vendor: Mesa Gallium driver 26.0.3-arch2.2 for AMD Radeon RX 9070 XT (radeonsi, gfx1201, ACO, DRM 3.64, 6.19.10-1-cachyos-bore)
[2026-03-27 08:28:10.867]: Info: Streaming bitrate is 78988000
[2026-03-27 08:28:10.867]: Info: Using normal encoding mode
[2026-03-27 08:28:10.867]: Info: Using default rate control
[2026-03-27 08:28:10.868]: Info: Minimum FPS target set to ~15fps (66.6667ms)
[2026-03-27 08:28:11.275]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2026-03-27 08:28:11.293]: Info: Opus initialized: 48 kHz, 2 channels, 512 kbps (total), LOWDELAY
[2026-03-27 08:28:27.389]: Info: CLIENT DISCONNECTED
```

### Online logs

_No response_

### PR DESCRIPTION
**Pull request by Kishi85**
## Description

This PR adds proper multi-monitor support to Sunshine's XDG portal grab by exposing all streams of a capture portal as separate screens (utilizing the multiple capture mode of the screencast portal) with necessary fixes to make things work.

Things this PR does:
- Improve logging done by portalgrab.cpp for easier debugging (could be moved to a separate PR if desired)
- Properly implement XDG stop event based on DBus signal (as doing it based on matching the display resolution will break display switching)
- Remove the (already more or less defunct) session caching.
- Add missing error handling to pipewire code to prevent obvious segfaults
- Fix the (currently broken) keyboard shortcut for the switch_display_event
- Change screencast source selection mode to multiple
- Expose separate displays for each screen stream provided by the screencast portal (ordering streams consistently by screen position) - Note: This is still dependent on the Portal implementation providing streams for each selected source. I've only tested with KDE6.6 in a combined Remotedesktop+Screencast session and it's working fully there.

Known issues:
- ~~Can segfault when trying to switch displays really quickly (by mashing the screen switch shortcut multiple times within a second) and even then it's not fully reproducible. This would have been happening even before this PR when just having a single stream but was masked due to the shortcut handling not being properly implemented in the capture logic (missing return on !push_captured_image_cb).~~ This is a separate issue concerning other capturemethods as well (tested with KMS), see #4943 

### Issues Fixed or Closed

- Fixes #4914 

## Type of Change

- [X] **feat**: New feature (non-breaking change which adds functionality)
- [X] **fix**: Bug fix (non-breaking change which fixes an issue)
- [ ] **docs**: Documentation only changes
- [ ] **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semicolons, etc.)
- [ ] **refactor**: Code change that neither fixes a bug nor adds a feature
- [ ] **perf**: Code change that improves performance
- [ ] **test**: Adding missing tests or correcting existing tests
- [ ] **build**: Changes that affect the build system or external dependencies
- [ ] **ci**: Changes to CI configuration files and scripts
- [ ] **chore**: Other changes that don't modify src or test files
- [ ] **revert**: Reverts a previous commit
- [ ] **BREAKING CHANGE**: Introduces a breaking change (can be combined with any type above)

## Checklist

- [X] Code follows the style guidelines of this project
- [X] Code has been self-reviewed
- [X] Code has been commented, particularly in hard-to-understand areas
- [ ] Code docstring/documentation-blocks for new or existing methods/components have been added or updated
- [ ] Unit tests have been added or updated for any new or modified functionality

### AI Usage

- [X] **None**: No AI tools were used in creating this PR
- [ ] **Light**: AI provided minor assistance (formatting, simple suggestions)
- [ ] **Moderate**: AI helped with code generation or debugging specific parts
- [ ] **Heavy**: AI generated most or all of the code changes

### CODE REVIEW

**Comment by Kishi85** [comment]
@psyke83 Sorry to ping you here but can you think of a reason why the keyboard shortcut to switch displays would not work with portalgrab? 

I've been trying to do so after enumerating them properly for display_names (current state of this PR) but the switch_display_event from video.cpp does not seem to be firing or handled when using portalgrab and I can't figure what I'm missing.

**Comment by psyke83** [comment]
> @psyke83 Sorry to ping you here but can you think of a reason why the keyboard shortcut to switch displays would not work with portalgrab?
> 
> I've been trying to do so after enumerating them properly for display_names (current state of this PR) but the switch_display_event from video.cpp does not seem to be firing or handled when using portalgrab and I can't figure what I'm missing.

If you add some debug to video.cpp you'll see that your current code is hitting the `switch_display_event->peek()` case when the combination is first pressed, but the peek event then repeatedly triggers. The artificial reinit is not completing successfully for some reason.

**Comment by psyke83** [comment]
Look: https://github.com/LizardByte/Sunshine/blob/b172a980fba3e910c9d2b15d457a7995dde5c174/src/platform/linux/kmsgrab.cpp#L1221-L1230

It seems that portalgrab is not checking the push_captured_image_cb callback the same way in the capture loop. The same logic may need to be added. I will look at this further later when I have time, if you don't figure it out.

**Comment by Kishi85** [comment]
> Look:
> 
> https://github.com/LizardByte/Sunshine/blob/b172a980fba3e910c9d2b15d457a7995dde5c174/src/platform/linux/kmsgrab.cpp#L1221-L1230
> 
> It seems that portalgrab is not checking the push_captured_image_cb callback the same way in the capture loop. The same logic may need to be added. I will look at this further later when I have time, if you don't figure it out.

That is exactly what was missing to get the keyboard shortcut to work. Thanks!

**Comment by Kishi85** [comment]
I've got the basic functionality working now and can switch multiple displays using keyboard shortcuts.

The main issue right now is when the same display currently actively streaming is requested to be switched to again (e.g. currently streaming display 0 and trying to switch to it via shortcut) then the stream will disconnect due to https://github.com/Kishi85/Sunshine/blob/6d7942e0c82aeedfca16b77735f0fc6cf716a4ec/src/platform/linux/portalgrab.cpp#L1294-L1309

which is causing the stream to disconnect with ```Warning: PipeWire stream stopped by user.``` in the logs.

Problem here is that this is necessary to detect if the user stopped the stream via the XDG notification (according to @psyke83 notes in https://github.com/LizardByte/Sunshine/issues/4914#issuecomment-4160892107).

Possible solutions that need more research:
- Have the check detect if it is currently handling a switch_display_event. I've already had to extend it by adding the current stream position values to the mix so we can discern switching different screens without disconnecting.

- Figure out another way to detect the user disconnecting the portal manually and change that part of the stream logic.

- Update video.cpp to not reinit if switching to the same display currently active and just keep streaming (might have side-effects I can't assess).

**Comment by Kishi85** [comment]
> The main issue right now is when the same display currently actively streaming is requested to be switched to again (e.g. currently streaming display 0 and trying to switch to it via shortcut) then the stream will disconnect due to https://github.com/Kishi85/Sunshine/blob/6d7942e0c82aeedfca16b77735f0fc6cf716a4ec/src/platform/linux/portalgrab.cpp#L1294-L1309
> 
~~Changing the check to also include currently active switch_display_events directly works (not sure if this is the best way to do it):~~
```cpp
auto switch_display_event = mail::man->event<int>(mail::switch_display);
if (previous_width.load() == width && previous_height.load() == height && previous_pos_x.load() == pos_x && previous_pos_y.load() == pos_y && switch_display_event->peek()) {
```
Next issue is when changing displays via shortcut too quickly there seems to be a possible race condition which can happen that freezes Sunshine hard until it is restarted and then it is exiting with: ```Fatal: 10 seconds passed, yet Sunshine's still running: Forcing shutdown``` or ```Fatal: Hang detected! Session failed to terminate in 10 seconds.``` when the session is closed on the client-side.

**Comment by Kishi85** [comment]
> > The main issue right now is when the same display currently actively streaming is requested to be switched to again (e.g. currently streaming display 0 and trying to switch to it via shortcut) then the stream will disconnect due to https://github.com/Kishi85/Sunshine/blob/6d7942e0c82aeedfca16b77735f0fc6cf716a4ec/src/platform/linux/portalgrab.cpp#L1294-L1309
> 
> Changing the check to also include currently active switch_display_events directly works (not sure if this is the best way to do it):
> 
> ```c++
> auto switch_display_event = mail::man->event<int>(mail::switch_display);
> if (previous_width.load() == width && previous_height.load() == height && previous_pos_x.load() == pos_x && previous_pos_y.load() == pos_y && switch_display_event->peek()) {
> ```
> 
Scratch that solution as I've had a typo (missing inversion) there and didn't realize that the event is already popped when the display gets reset by video.cpp and the portal re-initialzies. Back to square one on that.

> Next issue is when changing displays via shortcut too quickly there seems to be a possible race condition which can happen that freezes Sunshine hard until it is restarted and then it is exiting with: `Fatal: 10 seconds passed, yet Sunshine's still running: Forcing shutdown` or `Fatal: Hang detected! Session failed to terminate in 10 seconds.` when the session is closed on the client-side.

Sunshine hanging when switching too quickly is still an issue. 

UPDATE: This could be related to chosen encoder, having tried vulkan and vaapi yields different results (hang vs. SEGV). 
After running with a debugger I'm seeing the SEGV in https://github.com/FFmpeg/FFmpeg/blob/15504610b0dc12c56e5e9f94ff06c873382368f5/libavcodec/hw_base_encode.c#L508 related to ctx being invalid/missing. Could we have an issue with switching from one pipewire_stream to another upon calling portal_t->init() multiple times? Simply adding a lock mutex for the whole init function does not seem to do the trick. It's likely somewhere in the capture or encoder logic.

UPDATE 2: More or less consistently reproducible when switching screens back and forth without waiting for the stream to update to the new screen. Does not seem to trigger if waiting for the stream to update to the new screen after switching plus a second or two more.

**Comment by psyke83** [comment]
The crashing (whether hang or segfault) may be due to the pipewire loop still being active during fake reinit.

See this block here: https://github.com/LizardByte/Sunshine/blob/b172a980fba3e910c9d2b15d457a7995dde5c174/src/platform/linux/portalgrab.cpp#L1363-L1370

And here: https://github.com/LizardByte/Sunshine/blob/b172a980fba3e910c9d2b15d457a7995dde5c174/src/platform/linux/portalgrab.cpp#L1393-L1399

You may also need to set these same variables when you intend to signal an artificial reinit (i.e., when push_captured_image_cb returns false) to ensure the encoder fully stops.

Regarding the race condition that causes a hang, one of the changes in #4875 resolves a hang after disconnect that happens when there are no screen updates happening. Since the on_process callback doesn't fire, the capture loop gets stuck. I worked around that by checking the [pull_free_image_cb](https://github.com/LizardByte/Sunshine/blob/b172a980fba3e910c9d2b15d457a7995dde5c174/src/platform/linux/portalgrab.cpp#L1401) result during timeout, so you may want to see if you need to do a similar check elsewhere (or perhaps find a better fix).

**Comment by Kishi85** [comment]
I'll stop force-pushing most things im doing right now and will be squashing the whole thing in the end after we've got all the kinks ironed out. A few things I've done and learned now:

- 9146245 Adds a prefix to all log messages from portalgrab.cpp so messages can be easily identified in the log (could do that as a separate PR as well if desired)
- Added a lot more logging on what goes on with pipewire_t and the session cache. Things learned from that: 
  - When video.cpp switches displays it calls reset_display() which in term resets the shared_ptr to the current display implicitly destroying pipewire_t and then reinitialzing a new display from scratch.
  - pipewire_t::cleanup_stream() always invalidates the session cache. Since it is called by the destructor of pipewire_t the session cache is never actually used? (c432cb6 fixes this without any noticable changes in behaviour)
- 20af084 Temporarily disables the session ending logic via XDG notification icon
  - If you try to access an ended session pipewire returns a specific error ```Pipewire Error, id:2 seq:8 message: no target node available``` (causing a green screen on the connected client) that could be used to better track a user ending the session via the xdg notification.

With all these changes I seemingly have managed to get a stable reproducer for the crash (SEGV) by switching to the same display that is currently streaming. This is working on a single monitor setup as well, allowed by the implementation in video.cpp and should just fully reset the display (+pipewire stream) without segfaulting. The crash only occurs when switching to the same display. Switching to another display and then back to the first one does not seem to crash (as easily) unless you're switching very quickly but that might just be resulting in a switch to the same display internally in the end.

~~I'm wondering if this is related to the whole session caching (which is currently more or less defunct on master anyway) and will try to remove the whole session cache to see what happens when this is using a fresh portal every time a new display is constructed. video.cpp already ensures that only one capture is active (due to other capture methods limitations) so multiple XDG notifications should never be an issue in the first place~~ Without session cache the client is just getting a greenscreen.

UPDATE: Testing this again and again leads to the same result: Segfault is only happening when trying to switch to the same screen that is already streaming even though the display reset/initialization looks the same in the log as when switching from one screen to another. It is properly reusing the session cache now and connecting to the same pipewire_node for each display. Could this be some quirk when repeatedly streaming the same node from pipewire? Switching to a different node and then back to the first one does not seem to trigger this issue.

**Comment by Kishi85** [comment]
After a lot of trial and error I've managed to cut the hangs when switching display down to only when very quickly, repeatedly switching (to the same? haven't tried others) display. You have to basically mash the shortcut to get a segfault. My theory for that is that when switching really quickly something in the capture logic combined with pipewire just cannot keep up (some thread sync issue?).

This is still an issue but I'm wondering if it can be mitigated in video.cpp as it seems unreasonable to allow queuing another switch_display_event while the previous one's reset_display has not finished:
https://github.com/LizardByte/Sunshine/blob/b172a980fba3e910c9d2b15d457a7995dde5c174/src/video.cpp#L1478-L1484


All other issues I've had with this are basically ironed out now:
- Hanging issue for switching to the same display is (almost fully) solved.
- XDG notification stream end is implemented via the associated pipewire error and not by matching screen properties
- The session cache is now properly invalidated only when a display_name that is not in the list is requested. This can happen as display_names enumerate directly from a separate portal instance (so that is always the current state). As display_names are just position and resolution values as "x,y,w,h" ```portal->init``` matches pipewire_streams based on those. Also we do not have to invalidate the session cache for removed portals as the related streams will just stay in there unused.

Things still todo before I'm likely to remove the draft status:
- Tone down logging to debug level for most of the newly added messages.

**Comment by Kishi85** [comment]
Squashed, rebased and description+title updated. This is ready for review.

There's still one known issue (that was there before this PR just masked, see description for details) but maybe someone reviewing this has an idea on how to fix or work around that.

**Comment by Kishi85** [comment]
> There's still one known issue (that was there before this PR just masked, see description for details) but maybe someone reviewing this has an idea on how to fix or work around that.

The remaining issue is unrelated to portalgrab and the changes in this PR as I've just tried button mashing to screen switch with KMS capture and that also segfaults (and the Sunshine service gets restarted by systemd). 
I'll open a separate issue for that as it seems to be a more generic problem.

**Comment by Kishi85** [comment]
Linter issues fixed as reported

**Comment by psyke83** [comment]
Apologies, I won't have time to look at the code right now, but I did a quick test on Plasma 6.6.3 and found some issues.

* In single display mode, resolutions switching is broken by this PR; seems to always trigger a green (vulkan) or black (vaapi) screen that requires a service restart to recover from.
* In multi display mode with display 2 set to the left and (primary) display 1 to the right, changing the resolution of display 1 causes it to switch to display 2 on reinit.

When testing resolution changes, I used a simple script like the following for a single monitor:
```
#!/bin/bash

OUTPUT="1"
RES_A="1920x1080@60"
RES_B="3840x2160@60"
TIME=$1

if [[ -z "$TIME" ]]; then
  TIME=5
fi

for i in {1..10}
do
   echo "Iteration $i: Switching to $RES_B"
   kscreen-doctor output.$OUTPUT.mode.$RES_B
   sleep $TIME
   echo "Iteration $i: Switching to $RES_A"
   kscreen-doctor output.$OUTPUT.mode.$RES_A
   sleep $TIME
done

echo "Stress test complete."
```

This doesn't account for multi-monitors, but it can still trigger the issue.

**Comment by Kishi85** [comment]
> * In single display mode, resolutions switching is broken by this PR; seems to always trigger a green (vulkan) or black (vaapi) screen that requires a service restart to recover from.

I can reproduce this and know where it is breaking but without further looking into it this does not make much sense to me but maybe you have an idea. 

Due to the resolution change the display will be seen as a new screen which in term invalidates the session_cache and thereby restarts the portal (also fetching a new pipewire_fd and pipewire_streams vector): https://github.com/Kishi85/Sunshine/blob/d3eb98a2cc4ae095547d6b86447f3468e295397a/src/platform/linux/portalgrab.cpp#L1308-L1314

I've seen similar greenscreen behaviour when disabling the session_cache and trying to use dbus->connect_to_portal directly but couldn't make any sense of it at the time. Since I needed the session_cache anyway for detecting user ending via XDG notification this seems to have slipped during my testing.


> * In multi display mode with display 2 set to the left and (primary) display 1 to the right, changing the resolution of display 1 causes it to switch to display 2 on reinit.

This one could be related to the display_naming scheme being based on both position and resolution. Does the log note falling back to the first stream? 
It might work better if we're matching display streams by only position as the resolution can change and then things won't line up and it would fall back to the first stream in the sorted list.

**Comment by Kishi85** [comment]
> > * In single display mode, resolutions switching is broken by this PR; seems to always trigger a green (vulkan) or black (vaapi) screen that requires a service restart to recover from.
> 
> I can reproduce this and know where it is breaking but without further looking into it this does not make much sense to me but maybe you have an idea.
> 
> Due to the resolution change the display will be seen as a new screen which in term invalidates the session_cache and thereby restarts the portal (also fetching a new pipewire_fd and pipewire_streams vector): https://github.com/Kishi85/Sunshine/blob/d3eb98a2cc4ae095547d6b86447f3468e295397a/src/platform/linux/portalgrab.cpp#L1308-L1314
> 
> I've seen similar greenscreen behaviour when disabling the session_cache and trying to use dbus->connect_to_portal directly but couldn't make any sense of it at the time. Since I needed the session_cache anyway for detecting user ending via XDG notification this seems to have slipped during my testing.
> 

UPDATE: Quick test shows that the pipewire stream does connect like it should do after session_cache invalidation/new cached portal session (so basically the same state as my previous problem when using dbus->connect_to_portal directly) but only gets to stream state paused and does not start streaming hence the green screen. Any quick ideas to why this would happen?

> > * In multi display mode with display 2 set to the left and (primary) display 1 to the right, changing the resolution of display 1 causes it to switch to display 2 on reinit.
> 
> This one could be related to the display_naming scheme being based on both position and resolution. Does the log note falling back to the first stream? It might work better if we're matching display streams by only position as the resolution can change and then things won't line up and it would fall back to the first stream in the sorted list.

UPDATE: This one is a bit tricky as changing resolution is currently seen as removing the screen with its old resolution and adding a new one with the new resolution. This is detected by video.cpp and handled by picking the first display from the displaynames list for re-init: https://github.com/LizardByte/Sunshine/blob/d3eb98a2cc4ae095547d6b86447f3468e295397a/src/video.cpp#L1241-L1251

Unless we find a way to generate persistent display_names here the display switch on resolution change might have to be categorised as expected behaviour. Persistently naming displays is hard when using portals as the streams are sorted by pipewire_node which is literally random so you have to do some sorting to get a consistent list. I'm using screen position in this PR but even position might change here on resolution change if you're on a stretched layout, so leaving the resolution out of the display_name won't help as much (unless its the display at 0,0 but that is picked as the first one anyway). Also since we're using the screencast portal we might not even have all available screens (as they user can select them in a screencast-only session) to map them to real displays and do the display naming/matching based on whatever else which always would be a lot more complicated.

**Comment by psyke83** [comment]
> UPDATE: Quick test shows that the pipewire stream does connect like it should do after session_cache invalidation/new cached portal session (so basically the same state as my previous problem when using dbus->connect_to_portal directly) but only gets to stream state paused and does not start streaming hence the green screen. Any quick ideas to why this would happen?

Is the PR reinitializing to an existing stream? If the pipewire state is set to paused and reconnected with an active stream, [ensure_stream](https://github.com/LizardByte/Sunshine/blob/ba4db46ac0bfbe478ad017f0b388bfcb346ad8ce/src/platform/linux/portalgrab.cpp#L862-L904) will be a no-op. Perhaps you need to add an else clause to the end that resumes the stream via setting `pw_stream_set_active` to true.

> Unless we find a way to generate persistent display_names here the display switch on resolution change might have to be categorised as expected behaviour. Persistently naming displays is hard when using portals as the streams are sorted by pipewire_node which is literally random so you have to do some sorting to get a consistent list. I'm using screen position in this PR but even position might change here on resolution change if you're on a stretched layout, so leaving the resolution out of the display_name won't help as much (unless its the display at 0,0 but that is picked as the first one anyway). Also since we're using the screencast portal we might not even have all available screens (as they user can select them in a screencast-only session) to map them to real displays and do the display naming/matching based on whatever else which always would be a lot more complicated.

The [description](https://github.com/flatpak/xdg-desktop-portal/blob/845290fb539e48adcbe2610c73078cb9f1e9d732/data/org.freedesktop.portal.ScreenCast.xml#L196-L201) for `id` seems to suggest that the order may be stable since we are using a restore token. Have you checked to see if this remains stable when reinitializing? That may not solve Sunshine *starting* to the wrong screen (as we don't persist anything on cold start), but it may help for mid-stream resolution changes, at least.

**Comment by Kishi85** [comment]
> > UPDATE: Quick test shows that the pipewire stream does connect like it should do after session_cache invalidation/new cached portal session (so basically the same state as my previous problem when using dbus->connect_to_portal directly) but only gets to stream state paused and does not start streaming hence the green screen. Any quick ideas to why this would happen?
> 
> Is the PR reinitializing to an existing stream? If the pipewire state is set to paused and reconnected with an active stream, [ensure_stream](https://github.com/LizardByte/Sunshine/blob/ba4db46ac0bfbe478ad017f0b388bfcb346ad8ce/src/platform/linux/portalgrab.cpp#L862-L904) will be a no-op. Perhaps you need to add an else clause to the end that resumes the stream via setting `pw_stream_set_active` to true.
> 

Unfortunately that won't help as the display gets full reset so we're working with a newly initializing portal_display when the stream state gets stuck in paused. There's also no logging for pipewire parameters negotiated (like Video Format and so on) anymore for any capture re-init after the session_cache gets invalidated for the new display. 

> > Unless we find a way to generate persistent display_names here the display switch on resolution change might have to be categorised as expected behaviour. Persistently naming displays is hard when using portals as the streams are sorted by pipewire_node which is literally random so you have to do some sorting to get a consistent list. I'm using screen position in this PR but even position might change here on resolution change if you're on a stretched layout, so leaving the resolution out of the display_name won't help as much (unless its the display at 0,0 but that is picked as the first one anyway). Also since we're using the screencast portal we might not even have all available screens (as they user can select them in a screencast-only session) to map them to real displays and do the display naming/matching based on whatever else which always would be a lot more complicated.
> 
> The [description](https://github.com/flatpak/xdg-desktop-portal/blob/845290fb539e48adcbe2610c73078cb9f1e9d732/data/org.freedesktop.portal.ScreenCast.xml#L196-L201) for `id` seems to suggest that the order may be stable since we are using a restore token. Have you checked to see if this remains stable when reinitializing? That may not solve Sunshine _starting_ to the wrong screen (as we don't persist anything on cold start), but it may help for mid-stream resolution changes, at least.

I'll have a look at this but the descriptors might be initialised in a random order that would shuffle displays around again. I'm also curious what will happen when a screen gets added or removed. It might be consistent and persistent per portal token but might just be that and also not guaranteed to stay that way on resetting the token. Using position to sort the stream list was the most logical choice so far.

**Comment by Kishi85** [comment]
> > The [description](https://github.com/flatpak/xdg-desktop-portal/blob/845290fb539e48adcbe2610c73078cb9f1e9d732/data/org.freedesktop.portal.ScreenCast.xml#L196-L201) for `id` seems to suggest that the order may be stable since we are using a restore token. Have you checked to see if this remains stable when reinitializing? That may not solve Sunshine _starting_ to the wrong screen (as we don't persist anything on cold start), but it may help for mid-stream resolution changes, at least.
> 
> I'll have a look at this but the descriptors might be initialised in a random order that would shuffle displays around again. I'm also curious what will happen when a screen gets added or removed. It might be consistent and persistent per portal token but might just be that and also not guaranteed to stay that way on resetting the token. Using position to sort the stream list was the most logical choice so far.

Could the resolution change be handled without a capture re-init? Because that's what is causing the display switch in the first place.

**Comment by Kishi85** [comment]
> The [description](https://github.com/flatpak/xdg-desktop-portal/blob/845290fb539e48adcbe2610c73078cb9f1e9d732/data/org.freedesktop.portal.ScreenCast.xml#L196-L201) for `id` seems to suggest that the order may be stable since we are using a restore token. Have you checked to see if this remains stable when reinitializing? That may not solve Sunshine _starting_ to the wrong screen (as we don't persist anything on cold start), but it may help for mid-stream resolution changes, at least.

KWIN isn't providing this id value at all in it's Session.Start response (as seen from simple capture with bustle):
```
"streams": <[(uint32 121, {"position": <(1920, 0)>, "size": <(1920, 1080)>, "source_type": <uint32 1>}), (119, {"position": <(0, 0)>, "size": <(1920, 1080)>, "source_type": <uint32 1>})]>
```
It's just providing ```position```, ```size``` and ```source_type``` for each stream on a ```pipewire_node```. We could probably do a differentiated name generation/matching based on what is available but at least for KDE the current behaviour is the only way that can be done consistently with what the Portal Session provides on metadata for streams. 
Only thing (I can think of atm that would be) working for KDE is to not do a capture::re-init in case the resolution changes as that is causing a reset_display (destroying the current portal_display and initializing a new one but since it cannot match the old name it'll fall back to the first one) and just change the parameters for the running stream on the fly but I have no idea if this is possible and/or supported.

I'll continue trying to figure out the pipewire stream paused issue over the weekend when I have time for it and post further updates on my findings.

**Comment by Kishi85** [comment]
Looks like I've found the root of the greenscreen problem with the session invalidation by sheer luck and it's because the pipewire_fd is closed at the wrong point (in session_cache_t instead of dbus_t where it's essentially created by calling open_pipewire_remote). This was not a problem before but since this PR is using a separate dbus_t Portal for the display names enumeration the pipewire_fd's from that enumeration call never get closed and basically block the pipewire_fd that gets created after session cache invalidation.

TODO: Change the Portal call for display enumeration so that it does *not* use open_pipewire_remote (which is totally unnecessary for it as we just need the streamlist from Session.Start).

**Comment by Kishi85** [comment]
> Looks like I've found the root of the greenscreen problem with the session invalidation by sheer luck and it's because the pipewire_fd is closed at the wrong point (in session_cache_t instead of dbus_t where it's essentially created by calling open_pipewire_remote). This was not a problem before but since this PR is using a separate dbus_t Portal for the display names enumeration the pipewire_fd's from that enumeration call never get closed and basically block the pipewire_fd that gets created after session cache invalidation.
> 
This change by itself does not seem to be catching the full issue. Additionally invalidating the cache on every portal_display init so new streams are directly available does fix it however (f01ed84). Doing it this way does not change behaviour compared to current master as there the session cache gets invalidated on every pipewire::cleanup_stream resulting in recreating the session on every portal_display init as well. I'm still curious as to why the issue is occurring if we just invalidate on demand when a display cannot be matched to a stream.

EDIT: Since video.cpp is already ensuring that we only have one display active at the same time (hence never having multiple tray icons and it even destroys the current display for reenumeration of display_names) I'm wondering if we need the session_cache for dbus_t at all. It's currently also tracking if maxFramerate failed and the portal session has been closed by the user and for that it will still be necessary.

> TODO: Change the Portal call for display enumeration so that it does _not_ use open_pipewire_remote (which is totally unnecessary for it as we just need the streamlist from Session.Start).

I've tried this by adding a parameter to connect_portal but doing it that way breaks mouse input? I wonder why this is happening. No issue leaving it the way it is now though as the pipewire_fd will just get closed unused.

**Comment by Kishi85** [comment]
Checking if the session cache and display names from a new portal match and doing the invalidation should they not during the display_names enumeration leads to a working portal_display init with a working cache that is only invalidated when the screen configuration changes.

**Comment by Kishi85** [comment]
> Apologies, I won't have time to look at the code right now, but I did a quick test on Plasma 6.6.3 and found some issues.
> 
> * In single display mode, resolutions switching is broken by this PR; seems to always trigger a green (vulkan) or black (vaapi) screen that requires a service restart to recover from.

I've managed to fix this issue by invalidating the session cache during ```portal_display_names``` enumeration (should live values using a new portal differ from the cache it will be invalidated and re-initialized during next ```portal_display```). 

> * In multi display mode with display 2 set to the left and (primary) display 1 to the right, changing the resolution of display 1 causes it to switch to display 2 on reinit.
> 

Added a correlation of stream position/resolution to the monitors name by matching to ```wl::monitors()``` and if that provides a non-empty result then this value (prefixed with 'n') is used as the display name and later matched to. Should this fail then the old logic will be used and the displayname will be prefixed with a 'p' to clearly distinguish between both modes when matching the name back to a stream. The streams will still be sorted by position to have a consistent order. 

Repeatedly testing both solutions has not shown any errors on my end.

**Comment by psyke83** [comment]
Some notes on the latest PR code:

I'm testing on latest Arch, Plasma 6.6.3, running headless (DP-2 left, DP-1 set to primary on the right) via an EDID dump extracted from a HDMI dummy dongle inserted into the initramfs and using these kernel parameters to expose them to two DisplayPort outputs on my RX 6600:
```
drm.edid_firmware=DP-1:edid/HDMI4KHDR.edid,DP-2:edid/HDMI4KHDR.edid video=DP-1:e video=DP-2:e
```

* Monitor switch is working great via the hotkeys.
* The green/black screen is solved on resolution change, but...
* When multiple screens are enabled, the stream is still starting on the wrong monitor (DP-2) and changing resolution of DP-1 always causes it to switch back to DP-2.
* I don't think the monitor name is getting picked up on my configuration:

```
Apr 06 01:22:17 archlinux sunshine[14754]: [2026-04-06 01:22:17.880]: Info: [portalgrab] Loaded portal restore token from disk
Apr 06 01:22:17 archlinux sunshine[14754]: [2026-04-06 01:22:17.909]: Info: [portalgrab] Found stream for display: '' position: 0x0 resolution: 1536x864
Apr 06 01:22:17 archlinux sunshine[14754]: [2026-04-06 01:22:17.909]: Info: [portalgrab] Found stream for display: '' position: 1536x0 resolution: 1536x864
Apr 06 01:22:17 archlinux sunshine[14754]: [2026-04-06 01:22:17.910]: Info: [portalgrab] Loaded portal restore token from disk
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.028]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.040]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.040]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.042]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.045]: Info: [portalgrab] Video format: 12
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.045]: Info: [portalgrab] Size: 1920x1080
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.045]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.045]: Info: [portalgrab] using DMA-BUF buffers
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.045]: Info: [portalgrab] Video format: 12
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.045]: Info: [portalgrab] Size: 1920x1080
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.045]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.045]: Info: [portalgrab] using DMA-BUF buffers
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.052]: Info: [portalgrab] Using negotiated resolution 1920x1080
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.117]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.126]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.126]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.128]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.133]: Info: [portalgrab] Video format: 12
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.133]: Info: [portalgrab] Size: 1920x1080
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.133]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.133]: Info: [portalgrab] using DMA-BUF buffers
Apr 06 01:22:18 archlinux sunshine[14754]: [2026-04-06 01:22:18.138]: Info: [portalgrab] Using negotiated resolution 1920x1080
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.070]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.081]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.081]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.084]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.088]: Info: [portalgrab] Video format: 12
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.088]: Info: [portalgrab] Size: 1920x1080
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.088]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.088]: Info: [portalgrab] using DMA-BUF buffers
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.093]: Info: [portalgrab] Using negotiated resolution 1920x1080
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.158]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.167]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.167]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.169]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.174]: Info: [portalgrab] Video format: 12
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.174]: Info: [portalgrab] Size: 1920x1080
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.174]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.174]: Info: [portalgrab] using DMA-BUF buffers
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.178]: Info: [portalgrab] Using negotiated resolution 1920x1080
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.256]: Info: [portalgrab] Loaded portal restore token from disk
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.278]: Info: [portalgrab] Found stream for display: '' position: 0x0 resolution: 1536x864
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.278]: Info: [portalgrab] Found stream for display: '' position: 1536x0 resolution: 1536x864
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.278]: Info: [portalgrab] Requested frame rate [60fps]
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.291]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.294]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.298]: Info: [portalgrab] Video format: 12
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.298]: Info: [portalgrab] Size: 1920x1080
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.298]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.298]: Info: [portalgrab] using DMA-BUF buffers
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.303]: Info: [portalgrab] Using negotiated resolution 1920x1080
```

Have you looked at the [xdg_listener](https://github.com/LizardByte/Sunshine/blob/ba4db46ac0bfbe478ad017f0b388bfcb346ad8ce/src/platform/linux/wayland.cpp#L118-L124) entries? The `xdg_name` seems to pick up stable connector names that can be used:

```
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.277]: Info: [wayland] Name: DP-1
Apr 06 01:22:27 archlinux sunshine[14754]: [2026-04-06 01:22:27.277]: Info: [wayland] Name: DP-2
```

For context, the monitor name is also detected via wayland.cpp, but the string it prints is actually the [description](https://github.com/LizardByte/Sunshine/blob/ba4db46ac0bfbe478ad017f0b388bfcb346ad8ce/src/platform/linux/wayland.cpp#L136) and not the name:
```
Apr 06 01:13:48 archlinux sunshine[10168]: [2026-04-06 01:13:48.463]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
Apr 06 01:13:48 archlinux sunshine[10168]: [2026-04-06 01:13:48.490]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
```

Edit: I see that [name and description](https://wayland.app/protocols/xdg-output-unstable-v1) are considered deprecated, so wl_output should by used instead. But it seems that something is not working correctly with the monitor name detection implemented in portalgrab for my configuration.

**Comment by Kishi85** [comment]
> Edit: I see that [name and description](https://wayland.app/protocols/xdg-output-unstable-v1) are considered deprecated, so wl_output should by used instead. But it seems that something is not working correctly with the monitor name detection implemented in portalgrab for my configuration.

From your logs it seems that the correlation with ```wl::monitors()``` does not work as you're getting no matching names back:
```
Apr 06 01:22:17 archlinux sunshine[14754]: [2026-04-06 01:22:17.909]: Info: [portalgrab] Found stream for display: '' position: 0x0 resolution: 1536x864
Apr 06 01:22:17 archlinux sunshine[14754]: [2026-04-06 01:22:17.909]: Info: [portalgrab] Found stream for display: '' position: 1536x0 resolution: 1536x864
```
Then it's falling back to position/resolution matching and the already known behaviour. Could you check if in the wayland output just before those lines the viewport information is matching to the screen position/resolution information you see for the pipewire streams found? 

For comparison here's a working example (with bold/italic highlights) using my config (also Arch-based but CachyOS with Plasma 6.6.3, Fake-EDID is on HDMI-A-1 of my RX9070XT and taken from https://github.com/linuxhw/EDID, DP-1/2 are real monitors with DP-1 mirrored to HDMI-A-1 therefore not in the list):

[2026-04-06 07:28:40.719]: Info: [wayland] Offset: **1920x0**
[2026-04-06 07:28:40.719]: Info: [wayland] Logical size: **1920x1080**
[2026-04-06 07:28:40.719]: Info: [wayland] Name: **DP-2**
[2026-04-06 07:28:40.719]: Info: [wayland] Found monitor: Samsung Electric Company LS24AG30x
[2026-04-06 07:28:40.719]: Info: [wayland] Offset: _0x0_
[2026-04-06 07:28:40.719]: Info: [wayland] Logical size: _1920x1080_
[2026-04-06 07:28:40.719]: Info: [wayland] Name: _HDMI-A-1_
[2026-04-06 07:28:40.719]: Info: [wayland] Found monitor: BNQ BenQ XL2411Z
[2026-04-06 07:28:40.720]: Info: [portalgrab] Found stream for display: '_HDMI-A-1_' position: _0x0_ resolution: _1920x1080_
[2026-04-06 07:28:40.720]: Info: [portalgrab] Found stream for display: '**DP-2**' position: **1920x0** resolution: **1920x1080**


The name correlation code (see https://github.com/Kishi85/Sunshine/blob/96bdcf1d1fc893aab4e95415b7402f9f1c2be3b9/src/platform/linux/portalgrab.cpp#L585-L609) is just reusing data from the same code that kmsgrab is during it's monitor correlation: https://github.com/LizardByte/Sunshine/blob/ba4db46ac0bfbe478ad017f0b388bfcb346ad8ce/src/platform/linux/wayland.cpp#L541

Correlation is done during ```start_portal_session``` so the both information sets (```wl::monitors()``` and listed portal streams) are sure to match as close as possible. It's using the (connector) name of monitor_t (stored as part of pipewire_streaminfo_t) as it is a unique identifier per system to match streams to later with a fallback to position/resolution matching in case the name is empty.

@psyke83  It's interesting to see that the correlation does not work on your setup and I'm curious to see if matching up wayland log output to the streams found can help identify the issue here.

**Comment by psyke83** [comment]
I'll provide some more detailed logs when I have access to the host pc later today.

Regarding the default monitor selection, KDE has a dbus call you can use to get the active output display:

```
qdbus org.kde.KWin /KWin org.kde.KWin.activeOutputName
```

I can't verify right now, but some Googling shows a similar method for GNOME: https://wiki.gnome.org/Initiatives(2f)Wayland(2f)Gaps(2f)DisplayConfig.html (there's a primary bool in the properties array).

I'm not saying that you have to implement these (as it seems quite annoying to tailor detection to specific compositors), but I'm not aware of any generic methods to get the primary (or even just currently active) screen on Wayland.

**Comment by psyke83** [comment]
Perhaps we shouldn't worry about the primary monitor, but instead try to determine the active monitor from the pointer position provided by [spa_meta_cursor](https://docs.pipewire.org/structspa__meta__cursor.html) metadata? From that we may be able to determine the position data and which screen it is currently active on.

**Comment by Kishi85** [comment]
> I'll provide some more detailed logs when I have access to the host pc later today.
> 
> Regarding the default monitor selection, KDE has a dbus call you can use to get the active output display:
> 
> ```
> qdbus org.kde.KWin /KWin org.kde.KWin.activeOutputName
> ```
> 
> I can't verify right now, but some Googling shows a similar method for GNOME: https://wiki.gnome.org/Initiatives(2f)Wayland(2f)Gaps(2f)DisplayConfig.html (there's a primary bool in the properties array).
> 

It's not just a bool if you're using more than 2 screens, then there's a whole screen priority list of monitors that you can modify (at least in KDE display settings) and the first in the list is considered primary.

> I'm not saying that you have to implement these (as it seems quite annoying to tailor detection to specific compositors), but I'm not aware of any generic methods to get the primary (or even just currently active) screen on Wayland.

I agree that using screen priorites would be good way to sort streams but is only feasible if we can leverage wayland.h/cpp to get those priorities from a standardized interface. I'll have a look into it when I find some time.

But even if possible that should be done in a separate PR. It's big enough as it is now and I'd like to fix any remaining issues first and get this PR merged before improving on functionality further.

**Comment by Kishi85** [comment]
> Perhaps we shouldn't worry about the primary monitor, but instead try to determine the active monitor from the pointer position provided by [spa_meta_cursor](https://docs.pipewire.org/structspa__meta__cursor.html) metadata? From that we may be able to determine the position data and which screen it is currently active on.

Not sure why you would want to add pointer correlation here?

The main problem is that video.cpp is doing the switching based on the display_name selected by index based on the F-key you press from the display_names vector. In case of a capture re-init due to resolution change it'll try to find the last selected display_name from the new display_names vector and if that fails it falls back with the first element of said vector. To make this work on resolution change we need to use a resolution/position independent display_name like the (connector) name from wl::monitors().
That also means you have to do the correlation for all entries/streams that portal_display_names can return every time the portal session is started. Otherwise the video.cpp will not be able to find the last display_name and switch to it again causing the fallback.

EDIT: To clarify what this PR does is that it provides all portal_display_names for video.cpp so that can call portal_display with the name it intends to switch to and initialize the correct stream for what is requested. The whole logic as to what is switched to is done by video.cpp. It also ensures things don't break by destroying the old display before it even enumerates display_names again and then initializing a new display based on what shortcut is pressed. Similar things happen for a capture::re-init due to resolution change. See [video.cpp](https://github.com/LizardByte/Sunshine/blob/master/src/video.cpp) for details.

**Comment by Kishi85** [comment]
I've taken the time to cleanup the commits a bit and update a few commit messages with more detail to make them easier to understand. I can do another squash if necessary before this gets merged and/or put 69c05b175d6e8d47364a5f08b59ec40373e2f8c3 into a separate PR.

**Comment by psyke83** [comment]
Here's a full log taken from the latest PR changes:

```
[2026-04-06 16:37:57.387]: Info: Package Publisher: LizardByte
[2026-04-06 16:37:57.387]: Info: Publisher Website: https://app.lizardbyte.dev
[2026-04-06 16:37:57.387]: Info: Get support: https://app.lizardbyte.dev/support
[2026-04-06 16:37:57.387]: Info: config: 'vaapi_strict_rc_buffer' = enabled
[2026-04-06 16:37:57.387]: Info: config: 'min_threads' = 2
[2026-04-06 16:37:57.387]: Info: config: 'system_tray' = disabled
[2026-04-06 16:37:57.387]: Info: config: 'vk_rc_mode' = 4
[2026-04-06 16:37:57.387]: Info: config: 'minimum_fps_target' = 1
[2026-04-06 16:37:57.387]: Info: config: 'encoder' = vulkan
[2026-04-06 16:37:57.387]: Info: config: 'capture' = portal
[2026-04-06 16:37:57.388]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-06 16:37:57.408]: Info: [wayland] Found display [wayland-0]
[2026-04-06 16:37:57.410]: Info: [wayland] Found interface: zxdg_output_manager_v1(31) version 3
[2026-04-06 16:37:57.410]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(57) version 5
[2026-04-06 16:37:57.410]: Info: [wayland] Found interface: wl_output(65) version 4
[2026-04-06 16:37:57.410]: Info: [wayland] Found interface: wl_output(66) version 4
[2026-04-06 16:37:57.410]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 16:37:57.410]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 16:37:57.410]: Info: [wayland] Offset: 1536x0
[2026-04-06 16:37:57.410]: Info: [wayland] Logical size: 1536x864
[2026-04-06 16:37:57.410]: Info: [wayland] Name: DP-1
[2026-04-06 16:37:57.410]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 16:37:57.410]: Info: [wayland] Offset: 0x0
[2026-04-06 16:37:57.410]: Info: [wayland] Logical size: 1536x864
[2026-04-06 16:37:57.410]: Info: [wayland] Name: DP-2
[2026-04-06 16:37:57.410]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 16:37:57.411]: Info: [portalgrab] Found stream for display: '' position: 0x0 resolution: 1536x864
[2026-04-06 16:37:57.411]: Info: [portalgrab] Found stream for display: '' position: 1536x0 resolution: 1536x864
[2026-04-06 16:37:57.412]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-06 16:37:57.428]: Info: [wayland] Found display [wayland-0]
[2026-04-06 16:37:57.429]: Info: [wayland] Found interface: zxdg_output_manager_v1(31) version 3
[2026-04-06 16:37:57.429]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(57) version 5
[2026-04-06 16:37:57.429]: Info: [wayland] Found interface: wl_output(65) version 4
[2026-04-06 16:37:57.429]: Info: [wayland] Found interface: wl_output(66) version 4
[2026-04-06 16:37:57.429]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 16:37:57.429]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 16:37:57.429]: Info: [wayland] Offset: 1536x0
[2026-04-06 16:37:57.429]: Info: [wayland] Logical size: 1536x864
[2026-04-06 16:37:57.429]: Info: [wayland] Name: DP-1
[2026-04-06 16:37:57.429]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 16:37:57.429]: Info: [wayland] Offset: 0x0
[2026-04-06 16:37:57.429]: Info: [wayland] Logical size: 1536x864
[2026-04-06 16:37:57.429]: Info: [wayland] Name: DP-2
[2026-04-06 16:37:57.429]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 16:37:57.526]: Info: Trying encoder [vulkan]
[2026-04-06 16:37:57.526]: Info: Screencasting with XDG portal
[2026-04-06 16:37:57.526]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
[2026-04-06 16:37:57.526]: Info: [wayland] Found display [wayland-0]
[2026-04-06 16:37:57.538]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
[2026-04-06 16:37:57.538]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
[2026-04-06 16:37:57.539]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 16:37:57.542]: Info: [portalgrab] Video format: 12
[2026-04-06 16:37:57.542]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 16:37:57.542]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 16:37:57.542]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 16:37:57.542]: Info: [portalgrab] Video format: 12
[2026-04-06 16:37:57.542]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 16:37:57.542]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 16:37:57.542]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 16:37:57.549]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 16:37:57.549]: Info: Creating encoder [h264_vulkan]
[2026-04-06 16:37:57.549]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 16:37:57.549]: Info: Color depth: 8-bit
[2026-04-06 16:37:57.549]: Info: Color range: JPEG
[2026-04-06 16:37:57.569]: Info: Streaming bitrate is 1000000
[2026-04-06 16:37:57.569]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 16:37:57.588]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 16:37:57.588]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 16:37:57.588]: Info: Color depth: 8-bit
[2026-04-06 16:37:57.588]: Info: Color range: JPEG
[2026-04-06 16:37:57.603]: Info: Streaming bitrate is 1000000
[2026-04-06 16:37:57.605]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 16:37:57.622]: Info: Creating encoder [av1_vulkan]
[2026-04-06 16:37:57.622]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 16:37:57.622]: Info: Color depth: 8-bit
[2026-04-06 16:37:57.622]: Info: Color range: JPEG
[2026-04-06 16:37:57.636]: Info: Streaming bitrate is 1000000
[2026-04-06 16:37:57.636]: Error: [av1_vulkan @ 0x564cc3ff6640] Device does not support encoding av1!
[2026-04-06 16:37:57.642]: Error: Could not open codec [av1_vulkan]: Function not implemented
[2026-04-06 16:37:57.642]: Info: Screencasting with XDG portal
[2026-04-06 16:37:57.642]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
[2026-04-06 16:37:57.642]: Info: [wayland] Found display [wayland-0]
[2026-04-06 16:37:57.652]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
[2026-04-06 16:37:57.652]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
[2026-04-06 16:37:57.654]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 16:37:57.657]: Info: [portalgrab] Video format: 12
[2026-04-06 16:37:57.657]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 16:37:57.657]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 16:37:57.657]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 16:37:57.663]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 16:37:57.663]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 16:37:57.663]: Info: Color coding: SDR (Rec. 709)
[2026-04-06 16:37:57.663]: Info: Color depth: 10-bit
[2026-04-06 16:37:57.663]: Info: Color range: JPEG
[2026-04-06 16:37:57.679]: Info: Streaming bitrate is 1000000
[2026-04-06 16:37:57.681]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 16:37:57.690]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2026-04-06 16:37:57.690]: Info: 
[2026-04-06 16:37:57.690]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2026-04-06 16:37:57.690]: Info: 
[2026-04-06 16:37:57.690]: Info: Found H.264 encoder: h264_vulkan [vulkan]
[2026-04-06 16:37:57.690]: Info: Found HEVC encoder: hevc_vulkan [vulkan]
[2026-04-06 16:37:57.690]: Info: No main thread features enabled, skipping event loop
[2026-04-06 16:37:57.691]: Error: Failed to create client: Daemon not running
[2026-04-06 16:37:57.691]: Info: Configuration UI available at [https://localhost:47990]
[2026-04-06 16:38:05.683]: Info: Trying encoder [vulkan]
[2026-04-06 16:38:05.683]: Info: Screencasting with XDG portal
[2026-04-06 16:38:05.683]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
[2026-04-06 16:38:05.683]: Info: [wayland] Found display [wayland-0]
[2026-04-06 16:38:05.694]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
[2026-04-06 16:38:05.694]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
[2026-04-06 16:38:05.695]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 16:38:05.699]: Info: [portalgrab] Video format: 12
[2026-04-06 16:38:05.699]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 16:38:05.699]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 16:38:05.699]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 16:38:05.705]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 16:38:05.705]: Info: Creating encoder [h264_vulkan]
[2026-04-06 16:38:05.705]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 16:38:05.705]: Info: Color depth: 8-bit
[2026-04-06 16:38:05.705]: Info: Color range: JPEG
[2026-04-06 16:38:05.720]: Info: Streaming bitrate is 1000000
[2026-04-06 16:38:05.721]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 16:38:05.739]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 16:38:05.739]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 16:38:05.739]: Info: Color depth: 8-bit
[2026-04-06 16:38:05.739]: Info: Color range: JPEG
[2026-04-06 16:38:05.755]: Info: Streaming bitrate is 1000000
[2026-04-06 16:38:05.756]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 16:38:05.772]: Info: Creating encoder [av1_vulkan]
[2026-04-06 16:38:05.772]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 16:38:05.772]: Info: Color depth: 8-bit
[2026-04-06 16:38:05.772]: Info: Color range: JPEG
[2026-04-06 16:38:05.786]: Info: Streaming bitrate is 1000000
[2026-04-06 16:38:05.787]: Error: [av1_vulkan @ 0x7fd764207000] Device does not support encoding av1!
[2026-04-06 16:38:05.792]: Error: Could not open codec [av1_vulkan]: Function not implemented
[2026-04-06 16:38:05.793]: Info: Screencasting with XDG portal
[2026-04-06 16:38:05.793]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
[2026-04-06 16:38:05.793]: Info: [wayland] Found display [wayland-0]
[2026-04-06 16:38:05.803]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
[2026-04-06 16:38:05.803]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
[2026-04-06 16:38:05.805]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 16:38:05.808]: Info: [portalgrab] Video format: 12
[2026-04-06 16:38:05.808]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 16:38:05.808]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 16:38:05.808]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 16:38:05.815]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 16:38:05.815]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 16:38:05.815]: Info: Color coding: SDR (Rec. 709)
[2026-04-06 16:38:05.815]: Info: Color depth: 10-bit
[2026-04-06 16:38:05.815]: Info: Color range: JPEG
[2026-04-06 16:38:05.829]: Info: Streaming bitrate is 1000000
[2026-04-06 16:38:05.830]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 16:38:05.851]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2026-04-06 16:38:05.851]: Info: 
[2026-04-06 16:38:05.851]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2026-04-06 16:38:05.851]: Info: 
[2026-04-06 16:38:05.851]: Info: Found H.264 encoder: h264_vulkan [vulkan]
[2026-04-06 16:38:05.851]: Info: Found HEVC encoder: hevc_vulkan [vulkan]
[2026-04-06 16:38:05.851]: Info: Executing [Desktop]
[2026-04-06 16:38:05.892]: Info: New streaming session started [active sessions: 1]
[2026-04-06 16:38:05.903]: Info: CLIENT CONNECTED
[2026-04-06 16:38:05.905]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-06 16:38:05.924]: Info: [wayland] Found display [wayland-0]
[2026-04-06 16:38:05.926]: Info: [wayland] Found interface: zxdg_output_manager_v1(31) version 3
[2026-04-06 16:38:05.926]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(57) version 5
[2026-04-06 16:38:05.926]: Info: [wayland] Found interface: wl_output(65) version 4
[2026-04-06 16:38:05.926]: Info: [wayland] Found interface: wl_output(66) version 4
[2026-04-06 16:38:05.926]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 16:38:05.926]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 16:38:05.926]: Info: [wayland] Offset: 1536x0
[2026-04-06 16:38:05.926]: Info: [wayland] Logical size: 1536x864
[2026-04-06 16:38:05.926]: Info: [wayland] Name: DP-1
[2026-04-06 16:38:05.926]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 16:38:05.926]: Info: [wayland] Offset: 0x0
[2026-04-06 16:38:05.926]: Info: [wayland] Logical size: 1536x864
[2026-04-06 16:38:05.926]: Info: [wayland] Name: DP-2
[2026-04-06 16:38:05.926]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 16:38:05.927]: Info: [portalgrab] Found stream for display: '' position: 0x0 resolution: 1536x864
[2026-04-06 16:38:05.927]: Info: [portalgrab] Found stream for display: '' position: 1536x0 resolution: 1536x864
[2026-04-06 16:38:05.927]: Info: Screencasting with XDG portal
[2026-04-06 16:38:05.927]: Info: [portalgrab] Requested frame rate [60fps]
[2026-04-06 16:38:05.927]: Info: [wayland] Found display [wayland-0]
[2026-04-06 16:38:05.938]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
[2026-04-06 16:38:05.939]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 16:38:05.943]: Info: [portalgrab] Video format: 12
[2026-04-06 16:38:05.943]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 16:38:05.943]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 16:38:05.943]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 16:38:05.949]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 16:38:05.949]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 16:38:05.949]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 16:38:05.949]: Info: Color depth: 8-bit
[2026-04-06 16:38:05.949]: Info: Color range: MPEG
[2026-04-06 16:38:05.966]: Info: Streaming bitrate is 59788000
[2026-04-06 16:38:05.968]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 16:38:05.968]: Info: Minimum FPS target set to ~0.5fps (2000ms)
[2026-04-06 16:38:06.386]: Info: Setting default sink to: [sink-sunshine-stereo]
[2026-04-06 16:38:06.386]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2026-04-06 16:38:06.402]: Info: Opus initialized: 48 kHz, 2 channels, 512 kbps (total), LOWDELAY
```

My comments regarding the pointer location was aimed at figuring out which monitor is to be selected on first connect and persisted on resolution change. Perhaps that won't be needed when the display names are detected correctly? As-is, my setup is still not detecting the name correctly, defaults to the wrong monitor (DP-2), and resolution change on DP-1 still causes it to switch to DP-2.

File: src/platform/linux/portalgrab.cpp [hunk 1]
```diff
@@ -570,12 +621,38 @@ namespace portal {
...
+
+        int out_pos_x;
+        int out_pos_y;
+        g_variant_lookup(value, "position", "(ii)", &out_pos_x, &out_pos_y, nullptr);
+
+        auto stream = pipewire_streaminfo_t {out_pipewire_node, out_width, out_height, out_pos_x, out_pos_y};
+
+        // Try to match the stream to a monitor_name by position/resolution and update stream info
+        for (const auto &monitor : wl_monitors) {
+          if (monitor->viewport.offset_x == out_pos_x && monitor->viewport.offset_y == out_pos_y && monitor->viewport.width == out_width && monitor->viewport.height == out_height) {
```
Comment (psyke83) [inline src/platform/linux/portalgrab.cpp]: When fractional scaling is active, this check will not succeed as expected.

Quick debug:
```
diff --git a/src/platform/linux/portalgrab.cpp b/src/platform/linux/portalgrab.cpp
index 70acaef3..9c39fd67 100644
--- a/src/platform/linux/portalgrab.cpp
+++ b/src/platform/linux/portalgrab.cpp
@@ -641,6 +641,10 @@ namespace portal {
           if (monitor->viewport.offset_x == out_pos_x && monitor->viewport.offset_y == out_pos_y && monitor->viewport.width == out_width && monitor->viewport.height == out_height) {
             stream.monitor_name = monitor->name;
             break;
+          } else {
+            BOOST_LOG(error) << "[portalgrab]: '" << monitor->name << "' X offset: " << monitor->viewport.offset_x <<" vs " << out_pos_x << ", Y: " << monitor->viewport.offset_y << " vs " << out_pos_y;
+            BOOST_LOG(error) << "[portalgrab]: '" << monitor->name << "' width: " << monitor->viewport.width << " vs " << out_width;
+            BOOST_LOG(error) << "[portalgrab]: '" << monitor->name << "' height: " << monitor->viewport.height << " vs " << out_height;
           }
         }
 
```

Results when both screens are at 125% scale:
```
[2026-04-06 17:17:13.370]: Info: Package Publisher: LizardByte
[2026-04-06 17:17:13.370]: Info: Publisher Website: https://app.lizardbyte.dev
[2026-04-06 17:17:13.370]: Info: Get support: https://app.lizardbyte.dev/support
[2026-04-06 17:17:13.370]: Info: config: 'vaapi_strict_rc_buffer' = enabled
[2026-04-06 17:17:13.370]: Info: config: 'min_threads' = 2
[2026-04-06 17:17:13.370]: Info: config: 'system_tray' = disabled
[2026-04-06 17:17:13.370]: Info: config: 'vk_rc_mode' = 4
[2026-04-06 17:17:13.370]: Info: config: 'minimum_fps_target' = 1
[2026-04-06 17:17:13.370]: Info: config: 'encoder' = vulkan
[2026-04-06 17:17:13.370]: Info: config: 'capture' = portal
[2026-04-06 17:17:13.370]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-06 17:17:13.388]: Info: [wayland] Found display [wayland-0]
[2026-04-06 17:17:13.390]: Info: [wayland] Found interface: zxdg_output_manager_v1(31) version 3
[2026-04-06 17:17:13.390]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(57) version 5
[2026-04-06 17:17:13.390]: Info: [wayland] Found interface: wl_output(65) version 4
[2026-04-06 17:17:13.390]: Info: [wayland] Found interface: wl_output(66) version 4
[2026-04-06 17:17:13.390]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 17:17:13.390]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 17:17:13.390]: Info: [wayland] Offset: 1536x0
[2026-04-06 17:17:13.390]: Info: [wayland] Logical size: 1536x864
[2026-04-06 17:17:13.390]: Info: [wayland] Name: DP-1
[2026-04-06 17:17:13.390]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 17:17:13.390]: Info: [wayland] Offset: 0x0
[2026-04-06 17:17:13.390]: Info: [wayland] Logical size: 1536x864
[2026-04-06 17:17:13.390]: Info: [wayland] Name: DP-2
[2026-04-06 17:17:13.390]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 17:17:13.390]: Error: [portalgrab]: 'DP-1' X offset: 1536 vs 1536, Y: 0 vs 0
[2026-04-06 17:17:13.390]: Error: [portalgrab]: 'DP-1' width: 1920 vs 1536
[2026-04-06 17:17:13.390]: Error: [portalgrab]: 'DP-1' height: 1080 vs 864
[2026-04-06 17:17:13.390]: Error: [portalgrab]: 'DP-2' X offset: 0 vs 1536, Y: 0 vs 0
[2026-04-06 17:17:13.390]: Error: [portalgrab]: 'DP-2' width: 1920 vs 1536
[2026-04-06 17:17:13.390]: Error: [portalgrab]: 'DP-2' height: 1080 vs 864
[2026-04-06 17:17:13.391]: Error: [portalgrab]: 'DP-1' X offset: 1536 vs 0, Y: 0 vs 0
[2026-04-06 17:17:13.391]: Error: [portalgrab]: 'DP-1' width: 1920 vs 1536
[2026-04-06 17:17:13.391]: Error: [portalgrab]: 'DP-1' height: 1080 vs 864
[2026-04-06 17:17:13.391]: Error: [portalgrab]: 'DP-2' X offset: 0 vs 0, Y: 0 vs 0
[2026-04-06 17:17:13.391]: Error: [portalgrab]: 'DP-2' width: 1920 vs 1536
[2026-04-06 17:17:13.391]: Error: [portalgrab]: 'DP-2' height: 1080 vs 864
[2026-04-06 17:17:13.392]: Info: [portalgrab] Found stream for display: '' position: 0x0 resolution: 1536x864
[2026-04-06 17:17:13.392]: Info: [portalgrab] Found stream for display: '' position: 1536x0 resolution: 1536x864
[2026-04-06 17:17:13.392]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-06 17:17:13.408]: Info: [wayland] Found display [wayland-0]
[2026-04-06 17:17:13.409]: Info: [wayland] Found interface: zxdg_output_manager_v1(31) version 3
[2026-04-06 17:17:13.409]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(57) version 5
[2026-04-06 17:17:13.410]: Info: [wayland] Found interface: wl_output(65) version 4
[2026-04-06 17:17:13.410]: Info: [wayland] Found interface: wl_output(66) version 4
[2026-04-06 17:17:13.410]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 17:17:13.410]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 17:17:13.410]: Info: [wayland] Offset: 1536x0
[2026-04-06 17:17:13.410]: Info: [wayland] Logical size: 1536x864
[2026-04-06 17:17:13.410]: Info: [wayland] Name: DP-1
[2026-04-06 17:17:13.410]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 17:17:13.410]: Info: [wayland] Offset: 0x0
[2026-04-06 17:17:13.410]: Info: [wayland] Logical size: 1536x864
[2026-04-06 17:17:13.410]: Info: [wayland] Name: DP-2
[2026-04-06 17:17:13.410]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-1' X offset: 1536 vs 1536, Y: 0 vs 0
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-1' width: 1920 vs 1536
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-1' height: 1080 vs 864
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-2' X offset: 0 vs 1536, Y: 0 vs 0
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-2' width: 1920 vs 1536
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-2' height: 1080 vs 864
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-1' X offset: 1536 vs 0, Y: 0 vs 0
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-1' width: 1920 vs 1536
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-1' height: 1080 vs 864
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-2' X offset: 0 vs 0, Y: 0 vs 0
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-2' width: 1920 vs 1536
[2026-04-06 17:17:13.410]: Error: [portalgrab]: 'DP-2' height: 1080 vs 864
[2026-04-06 17:17:13.509]: Info: Trying encoder [vulkan]
[2026-04-06 17:17:13.509]: Info: Screencasting with XDG portal
[2026-04-06 17:17:13.509]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
[2026-04-06 17:17:13.509]: Info: [wayland] Found display [wayland-0]
[2026-04-06 17:17:13.521]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
[2026-04-06 17:17:13.521]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
[2026-04-06 17:17:13.522]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 17:17:13.525]: Info: [portalgrab] Video format: 12
[2026-04-06 17:17:13.525]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 17:17:13.525]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 17:17:13.525]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 17:17:13.525]: Info: [portalgrab] Video format: 12
[2026-04-06 17:17:13.525]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 17:17:13.525]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 17:17:13.525]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 17:17:13.532]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 17:17:13.532]: Info: Creating encoder [h264_vulkan]
[2026-04-06 17:17:13.532]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 17:17:13.532]: Info: Color depth: 8-bit
[2026-04-06 17:17:13.532]: Info: Color range: JPEG
[2026-04-06 17:17:13.550]: Info: Streaming bitrate is 1000000
[2026-04-06 17:17:13.551]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 17:17:13.557]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 17:17:13.557]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 17:17:13.557]: Info: Color depth: 8-bit
[2026-04-06 17:17:13.557]: Info: Color range: JPEG
[2026-04-06 17:17:13.572]: Info: Streaming bitrate is 1000000
[2026-04-06 17:17:13.573]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 17:17:13.581]: Info: Creating encoder [av1_vulkan]
[2026-04-06 17:17:13.581]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 17:17:13.581]: Info: Color depth: 8-bit
[2026-04-06 17:17:13.581]: Info: Color range: JPEG
[2026-04-06 17:17:13.595]: Info: Streaming bitrate is 1000000
[2026-04-06 17:17:13.595]: Error: [av1_vulkan @ 0x55fc6d9b5440] Device does not support encoding av1!
[2026-04-06 17:17:13.596]: Error: Could not open codec [av1_vulkan]: Function not implemented
[2026-04-06 17:17:13.597]: Info: Screencasting with XDG portal
[2026-04-06 17:17:13.597]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
[2026-04-06 17:17:13.597]: Info: [wayland] Found display [wayland-0]
[2026-04-06 17:17:13.607]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
[2026-04-06 17:17:13.607]: Info: [portalgrab] Streaming display '' at position: 0x0 resolution: 1536x864
[2026-04-06 17:17:13.608]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 17:17:13.612]: Info: [portalgrab] Video format: 12
[2026-04-06 17:17:13.612]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 17:17:13.612]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 17:17:13.612]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 17:17:13.618]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 17:17:13.618]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 17:17:13.618]: Info: Color coding: SDR (Rec. 709)
[2026-04-06 17:17:13.618]: Info: Color depth: 10-bit
[2026-04-06 17:17:13.618]: Info: Color range: JPEG
[2026-04-06 17:17:13.634]: Info: Streaming bitrate is 1000000
[2026-04-06 17:17:13.636]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 17:17:13.644]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2026-04-06 17:17:13.644]: Info: 
[2026-04-06 17:17:13.644]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2026-04-06 17:17:13.644]: Info: 
[2026-04-06 17:17:13.644]: Info: Found H.264 encoder: h264_vulkan [vulkan]
[2026-04-06 17:17:13.644]: Info: Found HEVC encoder: hevc_vulkan [vulkan]
[2026-04-06 17:17:13.644]: Info: No main thread features enabled, skipping event loop
[2026-04-06 17:17:13.645]: Error: Failed to create client: Daemon not running
[2026-04-06 17:17:13.646]: Info: Configuration UI available at [https://localhost:47990]
```

Comment (psyke83) [reply src/platform/linux/portalgrab.cpp]: Is this enough to resolve the issue?

```
diff --git a/src/platform/linux/portalgrab.cpp b/src/platform/linux/portalgrab.cpp
index 70acaef3..66cba12e 100644
--- a/src/platform/linux/portalgrab.cpp
+++ b/src/platform/linux/portalgrab.cpp
@@ -638,7 +638,7 @@ namespace portal {
 
         // Try to match the stream to a monitor_name by position/resolution and update stream info
         for (const auto &monitor : wl_monitors) {
-          if (monitor->viewport.offset_x == out_pos_x && monitor->viewport.offset_y == out_pos_y && monitor->viewport.width == out_width && monitor->viewport.height == out_height) {
+          if (monitor->viewport.offset_x == out_pos_x && monitor->viewport.offset_y == out_pos_y && monitor->viewport.logical_width == out_width && monitor->viewport.logical_height == out_height) {
             stream.monitor_name = monitor->name;
             break;
           }
```

```
[2026-04-06 17:33:28.547]: Info: Package Publisher: LizardByte
[2026-04-06 17:33:28.547]: Info: Publisher Website: https://app.lizardbyte.dev
[2026-04-06 17:33:28.547]: Info: Get support: https://app.lizardbyte.dev/support
[2026-04-06 17:33:28.547]: Info: config: 'vaapi_strict_rc_buffer' = enabled
[2026-04-06 17:33:28.547]: Info: config: 'min_threads' = 2
[2026-04-06 17:33:28.547]: Info: config: 'system_tray' = disabled
[2026-04-06 17:33:28.547]: Info: config: 'vk_rc_mode' = 4
[2026-04-06 17:33:28.547]: Info: config: 'minimum_fps_target' = 1
[2026-04-06 17:33:28.547]: Info: config: 'encoder' = vulkan
[2026-04-06 17:33:28.547]: Info: config: 'capture' = portal
[2026-04-06 17:33:28.547]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-06 17:33:28.570]: Info: [wayland] Found display [wayland-0]
[2026-04-06 17:33:28.572]: Info: [wayland] Found interface: zxdg_output_manager_v1(31) version 3
[2026-04-06 17:33:28.572]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(57) version 5
[2026-04-06 17:33:28.572]: Info: [wayland] Found interface: wl_output(65) version 4
[2026-04-06 17:33:28.572]: Info: [wayland] Found interface: wl_output(66) version 4
[2026-04-06 17:33:28.572]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 17:33:28.572]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 17:33:28.572]: Info: [wayland] Offset: 1536x0
[2026-04-06 17:33:28.572]: Info: [wayland] Logical size: 1536x864
[2026-04-06 17:33:28.572]: Info: [wayland] Name: DP-1
[2026-04-06 17:33:28.572]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 17:33:28.573]: Info: [wayland] Offset: 0x0
[2026-04-06 17:33:28.573]: Info: [wayland] Logical size: 1536x864
[2026-04-06 17:33:28.573]: Info: [wayland] Name: DP-2
[2026-04-06 17:33:28.573]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 17:33:28.573]: Error: [portalgrab]: 'DP-1' X offset: 1536 vs 0, Y: 0 vs 0
[2026-04-06 17:33:28.573]: Error: [portalgrab]: 'DP-1' width: 1536 vs 1536
[2026-04-06 17:33:28.573]: Error: [portalgrab]: 'DP-1' height: 864 vs 864
[2026-04-06 17:33:28.574]: Info: [portalgrab] Found stream for display: 'DP-2' position: 0x0 resolution: 1536x864
[2026-04-06 17:33:28.574]: Info: [portalgrab] Found stream for display: 'DP-1' position: 1536x0 resolution: 1536x864
[2026-04-06 17:33:28.574]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-06 17:33:28.600]: Info: [wayland] Found display [wayland-0]
[2026-04-06 17:33:28.601]: Info: [wayland] Found interface: zxdg_output_manager_v1(31) version 3
[2026-04-06 17:33:28.601]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(57) version 5
[2026-04-06 17:33:28.601]: Info: [wayland] Found interface: wl_output(65) version 4
[2026-04-06 17:33:28.602]: Info: [wayland] Found interface: wl_output(66) version 4
[2026-04-06 17:33:28.602]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 17:33:28.602]: Info: [wayland] Resolution: 1920x1080
[2026-04-06 17:33:28.602]: Info: [wayland] Offset: 1536x0
[2026-04-06 17:33:28.602]: Info: [wayland] Logical size: 1536x864
[2026-04-06 17:33:28.602]: Info: [wayland] Name: DP-1
[2026-04-06 17:33:28.602]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 17:33:28.602]: Info: [wayland] Offset: 0x0
[2026-04-06 17:33:28.602]: Info: [wayland] Logical size: 1536x864
[2026-04-06 17:33:28.602]: Info: [wayland] Name: DP-2
[2026-04-06 17:33:28.602]: Info: [wayland] Found monitor: Hisense Electric Co., Ltd. HDMI4KHDR
[2026-04-06 17:33:28.602]: Error: [portalgrab]: 'DP-1' X offset: 1536 vs 0, Y: 0 vs 0
[2026-04-06 17:33:28.602]: Error: [portalgrab]: 'DP-1' width: 1536 vs 1536
[2026-04-06 17:33:28.602]: Error: [portalgrab]: 'DP-1' height: 864 vs 864
[2026-04-06 17:33:28.726]: Info: Trying encoder [vulkan]
[2026-04-06 17:33:28.726]: Info: Screencasting with XDG portal
[2026-04-06 17:33:28.726]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
[2026-04-06 17:33:28.726]: Info: [wayland] Found display [wayland-0]
[2026-04-06 17:33:28.738]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
[2026-04-06 17:33:28.738]: Info: [portalgrab] Streaming display 'DP-2' at position: 0x0 resolution: 1536x864
[2026-04-06 17:33:28.740]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 17:33:28.743]: Info: [portalgrab] Video format: 12
[2026-04-06 17:33:28.743]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 17:33:28.743]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 17:33:28.743]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 17:33:28.743]: Info: [portalgrab] Video format: 12
[2026-04-06 17:33:28.743]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 17:33:28.743]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 17:33:28.743]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 17:33:28.750]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 17:33:28.750]: Info: Creating encoder [h264_vulkan]
[2026-04-06 17:33:28.750]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 17:33:28.750]: Info: Color depth: 8-bit
[2026-04-06 17:33:28.750]: Info: Color range: JPEG
[2026-04-06 17:33:28.769]: Info: Streaming bitrate is 1000000
[2026-04-06 17:33:28.769]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 17:33:28.776]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 17:33:28.776]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 17:33:28.776]: Info: Color depth: 8-bit
[2026-04-06 17:33:28.776]: Info: Color range: JPEG
[2026-04-06 17:33:28.791]: Info: Streaming bitrate is 1000000
[2026-04-06 17:33:28.792]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 17:33:28.800]: Info: Creating encoder [av1_vulkan]
[2026-04-06 17:33:28.800]: Info: Color coding: SDR (Rec. 601)
[2026-04-06 17:33:28.800]: Info: Color depth: 8-bit
[2026-04-06 17:33:28.800]: Info: Color range: JPEG
[2026-04-06 17:33:28.814]: Info: Streaming bitrate is 1000000
[2026-04-06 17:33:28.814]: Error: [av1_vulkan @ 0x56292f3fb840] Device does not support encoding av1!
[2026-04-06 17:33:28.814]: Error: Could not open codec [av1_vulkan]: Function not implemented
[2026-04-06 17:33:28.815]: Info: Screencasting with XDG portal
[2026-04-06 17:33:28.815]: Info: [portalgrab] Requested frame rate [60/1, approx. 60 fps]
[2026-04-06 17:33:28.815]: Info: [wayland] Found display [wayland-0]
[2026-04-06 17:33:28.824]: Info: [portalgrab] Using first available stream as no matching stream was found for: ''
[2026-04-06 17:33:28.824]: Info: [portalgrab] Streaming display 'DP-2' at position: 0x0 resolution: 1536x864
[2026-04-06 17:33:28.826]: Info: [portalgrab] Connected to pipewire version 1.6.2
[2026-04-06 17:33:28.830]: Info: [portalgrab] Video format: 12
[2026-04-06 17:33:28.830]: Info: [portalgrab] Size: 1920x1080
[2026-04-06 17:33:28.830]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
[2026-04-06 17:33:28.830]: Info: [portalgrab] using DMA-BUF buffers
[2026-04-06 17:33:28.836]: Info: [portalgrab] Using negotiated resolution 1920x1080
[2026-04-06 17:33:28.836]: Info: Creating encoder [hevc_vulkan]
[2026-04-06 17:33:28.836]: Info: Color coding: SDR (Rec. 709)
[2026-04-06 17:33:28.836]: Info: Color depth: 10-bit
[2026-04-06 17:33:28.836]: Info: Color range: JPEG
[2026-04-06 17:33:28.851]: Info: Streaming bitrate is 1000000
[2026-04-06 17:33:28.852]: Info: Vulkan encode using GPU: AMD Radeon RX 6600 (RADV NAVI23)
[2026-04-06 17:33:28.864]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2026-04-06 17:33:28.864]: Info: 
[2026-04-06 17:33:28.864]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2026-04-06 17:33:28.864]: Info: 
[2026-04-06 17:33:28.864]: Info: Found H.264 encoder: h264_vulkan [vulkan]
[2026-04-06 17:33:28.864]: Info: Found HEVC encoder: hevc_vulkan [vulkan]
[2026-04-06 17:33:28.864]: Info: No main thread features enabled, skipping event loop
[2026-04-06 17:33:28.865]: Error: Failed to create client: Daemon not running
[2026-04-06 17:33:28.866]: Info: Configuration UI available at [https://localhost:47990]
```

This resolves the screen switching to DP-2 on resolution change, but still has the issue of starting the stream on the wrong display.

Comment (Kishi85) [reply src/platform/linux/portalgrab.cpp]: That's exactly what I've just come with after reading your log. I'll fix it and push the changes.

Comment (Kishi85) [reply src/platform/linux/portalgrab.cpp]: As for starting the stream on the wrong monitor this is due to the position sorting. I've not fully checked the screen priorities I've mentioned earlier but that will require further changes to wayland.h/cpp as we need to likely check another interface for that there, so I'd rather do this in a follow-up PR.

**Comment by Kishi85** [comment]
The wl::monitors() correlation wasn't using logical_width/logical_height to match against so scaled displays wouldn't work correctly but after seeing @psyke83's first comment I've started looking and in the meantime we both came up with the same solution. So this is fixed now as well.

The only remaining feature that would be nice to have is to do stream sorting additionally based on screen priorities (mainly to have the stream start on the primary screen) but that'll need changes to wayland.cpp/h to expose the necessary information (mainly the preferred/primary indicator). I'll try to implement this but might move it to a follow-up PR if it's a larger change as this PR is already doing quite a lot of things (although all are related to and necessary to make this feature work properly). 

UPDATE: From looking at other capture methods it looks like those have similar sorting issues (e.g. wlgrab takes the displays in the order that wl::monitors() provides them, which seems to be sorted alphabetically by wl_name). There also does not seem to be a unified Wayland interface for screen priorities/primary monitor (at least I've not found one so far). Adding sorting based on additional parameters is trivial but we have to get those parameters somehow and that's IMHO something for a follow-up PR as it will be a bit more involved.

**Comment by psyke83** [comment]
I agree with your assessment that primary/active detection is out of scope. I don't think Wayland has a direct method to probe the primary monitor, hence the suggestion to query the pipewire cursor position. But if it is feasible to do generically via Wayland, it belongs in a separate PR as it that could also be leveraged by kmsgrab. Until then, users can just arrange their displays so that the primary is leftmost.

I'm seeing an issue with the xdg stop event. When stopping the stream via the xdg notification icon, it can't resume the session. Log is [here](https://gist.github.com/psyke83/b2aeaa85d143acc76239e93a14716792); happens on KDE and GNOME.

**Comment by Kishi85** [comment]
> I'm seeing an issue with the xdg stop event. When stopping the stream via the xdg notification icon, it can't resume the session. Log is [here](https://gist.github.com/psyke83/b2aeaa85d143acc76239e93a14716792); happens on KDE and GNOME.

This is a tricky one and I might have an idea on how to handle this. I'll try to explain the issue here, maybe you have an idea:

- The way of handling this was to check if current stream resolution and previous stream resolution match but that would break things here as video.cpp allows you to switch to the same screen (basically doing a re-init of the portal_display).

- Currently its checking if the pipewire stream errors out with "no target node" and stores that state in the session_cache. Stopping the stream and subsequent display init's until the session_cache invalidates (and the portal re-initialises). Not ideal but it's what I've come up with so far.

- Ideally we could leverage the XDG stop signal from the Screencast.Session (https://github.com/flatpak/xdg-desktop-portal/blob/845290fb539e48adcbe2610c73078cb9f1e9d732/data/org.freedesktop.portal.ScreenCast.xml#L36-L39) and instead of doing a capture::re-init for that stream error/pause case just error out once, like is done for stream_stopped (which could IMHO be fully removed if that works). I haven't had time to look into this, but doing it that way seems to be the most correct way.

**Comment by Kishi85** [comment]
@psyke83 I've changed the current implementation of XDG stop and made it so that it invalidates the session_cache after the capture errors out, making it possible to connect again without restarting sunshine. It's not the ideal solution I've described but should fix the immediate problem you noted.

**Comment by Kishi85** [comment]
I've refined the fix for detecting closed portals a bit more as I can't seem to figure out that whole portal closed detection for dbus right now. The basic flow when closing the portal session is now:

1. Pipewire stream goes to paused -> Mark stream_dead -> Capture logic forces re-init due to stream_dead
2. Pipewire stream will error out due to "no target node" on re-init -> Set portal closed indicator on session_cache
3. portal_display init detects closed portal on session_cache -> Sets existing stream_stopped to true
4. Capture will error out (as before) but additionally set needs invalidation on session_cache
5. Next init/display_names will invalidate the session_cache first thing due to indicator fully restarting the portal.

As I can't figure out the Session::Closed signal handling right now I'd rather move that optimization to a follow-up PR as well. This flow is stable (after some testing) and good enough to handle the case.

**Comment by psyke83** [comment]
Everything is working fine (including the XDG stop case) with the latest changes on KDE.

GNOME is another story, unfortunately. If multiple screens are selected, only one stream is detected by Sunshine. The more critical issue, however, is that changing the resolution is broken, triggering the stream to disconnect no matter whether one or two screens are selected for use by the remote portal or if the second screen is disabled via GNOME display settings.

Log taken when just DP-1 is selected by the portal and DP-2 is disabled via GNOME's display settings, after trying to change the resolution of DP-1: https://gist.github.com/psyke83/dd95c00b814996868cba6dcdacdb02e4 

Apart from Sunshine's log, this warning is printed on mode change:
```
Apr 07 23:30:34 archlinux xdg-desktop-portal-gnome[12770]: Monitor 'Hisense Electric Co., Ltd. 52"' has no configuration which is-current!
```

(As a sanity check since this is not my preferred DE, I verified that resolution change is working OK with GNOME on the current master branch.)

**Comment by Kishi85** [comment]
> Everything is working fine (including the XDG stop case) with the latest changes on KDE.
> 
> GNOME is another story, unfortunately. If multiple screens are selected, only one stream is detected by Sunshine. The more critical issue, however, is that changing the resolution is broken, triggering the stream to disconnect no matter whether one or two screens are selected for use by the remote portal or if the second screen is disabled via GNOME display settings.
> 
The logical reason here is that the 'multiple' option of the Screencast portal does not work (properly or at all) with xdg-desktop-portal-gnome, which is unfortunate.

> Log taken when just DP-1 is selected by the portal and DP-2 is disabled via GNOME's display settings, after trying to change the resolution of DP-1: https://gist.github.com/psyke83/dd95c00b814996868cba6dcdacdb02e4
> 
> Apart from Sunshine's log, this warning is printed on mode change:
> 
> ```
> Apr 07 23:30:34 archlinux xdg-desktop-portal-gnome[12770]: Monitor 'Hisense Electric Co., Ltd. 52"' has no configuration which is-current!
> ```
> 
> (As a sanity check since this is not my preferred DE, I verified that resolution change is working OK with GNOME on the current master branch.)

From the logs it seems that the Screencast Portal closes on Gnome when the resolution changes which would trigger the new logic for the XDG stop event. On master everything's working as the portal will get invalidated on pipewire::cleanup_stream making it reload on every session_cache::get_or_create_session anyway likely masking the issue (due to the pipewire_fd from the newer portal_session). 
I might be able to fix this if I can detect/somehow check if the portal closed in dbus_t. Any ideas on/code snippets for that?

**Comment by Kishi85** [comment]
So I've just forced myself to bend my head around that XDG stop signal handling on the portal (which took me 2 hours in the end) and managed to implement it and reduce complexity for that case by a lot (see 910b2ce). I'm still testing if everything works as it should as I had to rip out the old stream_stopped logic in the process because now that was breaking display switching.

**Comment by Kishi85** [comment]
With the working session_cache I've noted that the XDG notification is always present while Sunshine is running which is not really desirable. So 57534af cuts that feature out (not really necessary as Sunshine ensures there's just one active display anyway) and by doing that the XDG notification only appears when Sunshine has an active Display that is using portalgrab (like on current master due to cleanup_stream including session_cache::invalidate).

This was not possible before as the XDG stop event needed to be implemented properly via the DBus signal first. Removing the session caching reduces complexity further and ensures clean states on the pipewire end. This might also fix the issues with resolution changing on GNOME but I've currently no way to test it.

I'm really curious on your opinion on this one @psyke83 as I'm sure you had implemented the cache for reasons.

**Comment by psyke83** [comment]
I'm not the original author of portalgrab or responsible for the session cache code; I only contributed small changes such as variable rate capture support before it was merged to master, so I'm not really the person to answer your question. I wasn't aware that the XDG icon was persisting after disconnect; stuff like that is harder for me to see when running exclusively headless, so that seems like a positive change.

The latest PR has an improvement: resolution change appears to be working properly on GNOME, but stopping via the XDG icon on both GNOME and KDE has regressed again. Relevant debug logs taken from moment XDG is clicked until stream unpauses/reinits on KDE:
```
Apr 08 17:19:15 archlinux sunshine[10211]: [2026-04-08 17:19:15.431]: Debug: [portalgrab] PipeWire stream state: streaming -> paused
Apr 08 17:19:16 archlinux sunshine[10211]: [2026-04-08 17:19:16.447]: Warning: [portalgrab] PipeWire stream disconnected. Forcing session reset.
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] Destroying pipewire_t
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] Stop PW thread loop
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] Cleaning up stream
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] Stop fill_img
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] Disconnect stream
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] PipeWire stream state: paused -> unconnected
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] Destroy stream
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] Disconnect PW core
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.470]: Debug: [portalgrab] Destroy PW context
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.471]: Debug: [portalgrab] Close pipewire_fd
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.471]: Debug: [portalgrab] Stop PW thread loop
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.471]: Debug: [portalgrab] Destroy PW thread loop
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.471]: Warning: [portalgrab] Failed to explicitly close portal session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/session/1_105/Sunshine11”
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.471]: Info: [portalgrab] Loaded portal restore token from disk
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.471]: Debug: [portalgrab] Finalizing Portal security: dropping capabilities and resetting dumpable
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.472]: Warning: [portalgrab] Portalsession closed due to signal: /org/freedesktop/portal/desktop/session/1_105/Sunshine11:org.freedesktop.portal.Session::Closed from :1.9
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.473]: Debug: [portalgrab] RemoteDesktop CreateSession response_code: 0
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.473]: Debug: [portalgrab] RemoteDesktop CreateSession: got session handle: /org/freedesktop/portal/desktop/session/1_105/Sunshine12
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.479]: Debug: [portalgrab] SelectDevices response_code: 0
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.479]: Debug: [portalgrab] SelectSources response_code: 0
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.486]: Debug: [portalgrab] RemoteDesktop Start response_code: 0
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.490]: Info: [portalgrab] Found stream for display: 'DP-1' position: 0x0 resolution: 1536x864
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.490]: Debug: [portalgrab] Explicitly closed portal session: /org/freedesktop/portal/desktop/session/1_105/Sunshine12
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.490]: Debug: [portalgrab] Start PW thread loop
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.490]: Info: [portalgrab] Requested frame rate [60fps]
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.500]: Info: [portalgrab] Loaded portal restore token from disk
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.500]: Debug: [portalgrab] Finalizing Portal security: dropping capabilities and resetting dumpable
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.502]: Debug: [portalgrab] RemoteDesktop CreateSession response_code: 0
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.502]: Debug: [portalgrab] RemoteDesktop CreateSession: got session handle: /org/freedesktop/portal/desktop/session/1_111/Sunshine13
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.508]: Debug: [portalgrab] SelectDevices response_code: 0
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.508]: Debug: [portalgrab] SelectSources response_code: 0
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.515]: Debug: [portalgrab] RemoteDesktop Start response_code: 0
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.518]: Info: [portalgrab] Streaming display 'DP-1' from position: 0x0 resolution: 1536x864
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.518]: Debug: [portalgrab] Setup PW context
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.519]: Debug: [portalgrab] Connect PW context to fd
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.519]: Debug: [portalgrab] Create PW stream
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.519]: Debug: [portalgrab] Connect PW stream - fd 41 node 66
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.519]: Debug: [portalgrab] PipeWire stream state: unconnected -> connecting
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.520]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.520]: Debug: [portalgrab] PipeWire stream state: connecting -> paused
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.522]: Info: [portalgrab] Video format: 12
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.522]: Info: [portalgrab] Size: 1920x1080
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.522]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.522]: Info: [portalgrab] using DMA-BUF buffers
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.523]: Info: [portalgrab] Video format: 12
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.523]: Info: [portalgrab] Size: 1920x1080
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.523]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.523]: Info: [portalgrab] using DMA-BUF buffers
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.523]: Debug: [portalgrab] PipeWire stream state: paused -> streaming
Apr 08 17:19:17 archlinux sunshine[10211]: [2026-04-08 17:19:17.530]: Info: [portalgrab] Using negotiated resolution 1920x1080
```

On GNOME:
```
Apr 08 17:48:31 archlinux sunshine[23362]: [2026-04-08 17:48:31.169]: Debug: [portalgrab] PipeWire stream state: streaming -> paused
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.169]: Warning: [portalgrab] PipeWire stream disconnected. Forcing session reset.
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.189]: Debug: [portalgrab] Destroying pipewire_t
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.189]: Debug: [portalgrab] Stop PW thread loop
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.189]: Debug: [portalgrab] Cleaning up stream
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.189]: Debug: [portalgrab] Stop fill_img
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.189]: Debug: [portalgrab] Disconnect stream
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.189]: Debug: [portalgrab] PipeWire stream state: paused -> unconnected
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.190]: Debug: [portalgrab] Destroy stream
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.190]: Debug: [portalgrab] Disconnect PW core
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.190]: Debug: [portalgrab] Destroy PW context
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.190]: Debug: [portalgrab] Close pipewire_fd
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.190]: Debug: [portalgrab] Stop PW thread loop
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.190]: Debug: [portalgrab] Destroy PW thread loop
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.190]: Warning: [portalgrab] Failed to explicitly close portal session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/session/1_110/Sunshine7”
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.190]: Info: [portalgrab] Loaded portal restore token from disk
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.191]: Debug: [portalgrab] Finalizing Portal security: dropping capabilities and resetting dumpable
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.192]: Warning: [portalgrab] Portalsession closed due to signal: /org/freedesktop/portal/desktop/session/1_110/Sunshine7:org.freedesktop.portal.Session::Closed from :1.45
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.192]: Debug: [portalgrab] RemoteDesktop CreateSession response_code: 0
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.192]: Debug: [portalgrab] RemoteDesktop CreateSession: got session handle: /org/freedesktop/portal/desktop/session/1_110/Sunshine8
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.199]: Debug: [portalgrab] SelectDevices response_code: 0
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.200]: Debug: [portalgrab] SelectSources response_code: 0
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.210]: Debug: [portalgrab] RemoteDesktop Start response_code: 0
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.212]: Info: [portalgrab] Found stream for display: 'DP-1' position: 0x0 resolution: 1920x1080
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.213]: Debug: [portalgrab] Explicitly closed portal session: /org/freedesktop/portal/desktop/session/1_110/Sunshine8
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.213]: Debug: [portalgrab] Start PW thread loop
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.213]: Info: [portalgrab] Requested frame rate [60fps]
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.221]: Info: [portalgrab] Loaded portal restore token from disk
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.222]: Debug: [portalgrab] Finalizing Portal security: dropping capabilities and resetting dumpable
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.224]: Debug: [portalgrab] RemoteDesktop CreateSession response_code: 0
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.224]: Debug: [portalgrab] RemoteDesktop CreateSession: got session handle: /org/freedesktop/portal/desktop/session/1_116/Sunshine9
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.229]: Debug: [portalgrab] SelectDevices response_code: 0
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.230]: Debug: [portalgrab] SelectSources response_code: 0
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.238]: Debug: [portalgrab] RemoteDesktop Start response_code: 0
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.240]: Info: [portalgrab] Streaming display 'DP-1' from position: 0x0 resolution: 1920x1080
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.240]: Debug: [portalgrab] Setup PW context
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.241]: Debug: [portalgrab] Connect PW context to fd
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.241]: Debug: [portalgrab] Create PW stream
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.241]: Debug: [portalgrab] Connect PW stream - fd 41 node 100
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.241]: Debug: [portalgrab] PipeWire stream state: unconnected -> connecting
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.241]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.241]: Debug: [portalgrab] PipeWire stream state: connecting -> paused
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] Video format: 12
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] Size: 1920x1080
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] Framerate (from compositor): 0/1
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] Framerate (from compositor, max): 60/1
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] using DMA-BUF buffers
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] Video format: 12
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] Size: 1920x1080
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] Framerate (from compositor): 0/1
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] Framerate (from compositor, max): 60/1
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.244]: Info: [portalgrab] using DMA-BUF buffers
Apr 08 17:48:32 archlinux sunshine[23362]: [2026-04-08 17:48:32.246]: Debug: [portalgrab] PipeWire stream state: paused -> streaming
```

**Comment by Kishi85** [comment]
I'll put this back into a draft state while I'm reworking the commit structure as it is just all over the place right now. 

From your logs it looks like the end signal isn't working properly. It should look something like this with the latest changes when you do XDG end:
```
[2026-04-08 19:09:02.315]: Warning: [portalgrab] Portalsession closed due to signal: /org/freedesktop/portal/desktop/session/1_79/Sunshine7:org.freedesktop.portal.Session::Closed from :1.6
[2026-04-08 19:09:03.321]: Warning: [portalgrab] PipeWire stream stopped by closed portal session.
```

On your logs it's still doing a session reset (which it shouldn't really do now, as the stop is based on the proper DBus signal)

**Comment by Kishi85** [comment]
I've reworked the commit structure into 5 distinct commits and will try to do all further changes by updating a related commit. I'm also marking this ready for review again.

@psyke83 I've added a 100ms delay to the dead stream handling in the capture code as your logs show that the portal closed signaling from DBUS was too late for the portal to be regarded in time before forcing the re-init. I'm unsure why this happend but there's likely nothing we can do to speed things up. It would be better to have a sync-way of querying the portal status but so far I've not found anything related to that.

UPDATE: It's sometimes simpler than one thinks. I've updated the ```is_session_closed``` on dbus_t to try to retrieve the property "org.freedestkop.portal.Session::version" with a sync blocking dbus call (like closing the session does in the destructor). If that fails the portal was closed and the capture will error out properly now independent of dbus signaling.

**Comment by psyke83** [comment]
Unfortunately the XDG stop still doesn't stop for me on KDE or GNOME. My CPU should not be excessively slow (5700X), but I tried bumping the wait time to eliminate the possibility:

```
diff --git a/src/platform/linux/portalgrab.cpp b/src/platform/linux/portalgrab.cpp
index b7ff3100..2076d535 100644
--- a/src/platform/linux/portalgrab.cpp
+++ b/src/platform/linux/portalgrab.cpp
@@ -1431,8 +1431,9 @@ namespace portal {
       while (true) {
         // Check if PipeWire signaled a dead stream
         if (shared_state->stream_dead.exchange(false)) {
+          BOOST_LOG(warning) << "[portalgrab]: wait for dbus";
           // Wait 100ms so the portal session closed signal can catch up if it's late. Not sure if this can be handled better...
-          std::this_thread::sleep_for(std::chrono::milliseconds(100));
+          std::this_thread::sleep_for(std::chrono::milliseconds(2000));
           // If the pipewire stream stopped due to closed portal session stop the capture with an error
           if (dbus.is_session_closed()) {
             BOOST_LOG(warning) << "[portalgrab] PipeWire stream stopped by closed portal session."sv;
```

Still unsuccessful:
```
Apr 08 22:10:04 archlinux sunshine[10402]: [2026-04-08 22:10:04.826]: Debug: [portalgrab] PipeWire stream state: streaming -> paused
Apr 08 22:10:05 archlinux sunshine[10402]: [2026-04-08 22:10:05.836]: Warning: [portalgrab]: wait for dbus
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.836]: Warning: [portalgrab] PipeWire stream disconnected. Forcing session reset.
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.856]: Debug: [portalgrab] Destroying pipewire_t
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.856]: Debug: [portalgrab] Stop PW thread loop
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.856]: Debug: [portalgrab] Cleaning up stream
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.856]: Debug: [portalgrab] Stop fill_img
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.856]: Debug: [portalgrab] Disconnect stream
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.856]: Debug: [portalgrab] PipeWire stream state: paused -> unconnected
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.857]: Debug: [portalgrab] Destroy stream
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.857]: Debug: [portalgrab] Disconnect PW core
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.857]: Debug: [portalgrab] Destroy PW context
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.857]: Debug: [portalgrab] Close pipewire_fd
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.857]: Debug: [portalgrab] Stop PW thread loop
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.857]: Debug: [portalgrab] Destroy PW thread loop
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.857]: Debug: [portalgrab] Unsubscribing closed session signal: 77
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.858]: Warning: [portalgrab] Failed to explicitly close portal session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/session/1_128/Sunshine7”
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.858]: Info: [portalgrab] Loaded portal restore token from disk
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.858]: Debug: [portalgrab] Finalizing Portal security: dropping capabilities and resetting dumpable
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.860]: Debug: [portalgrab] RemoteDesktop CreateSession response_code: 0
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.860]: Debug: [portalgrab] RemoteDesktop CreateSession: got session handle: /org/freedesktop/portal/desktop/session/1_128/Sunshine8
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.866]: Debug: [portalgrab] SelectDevices response_code: 0
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.866]: Debug: [portalgrab] SelectSources response_code: 0
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.873]: Debug: [portalgrab] RemoteDesktop Start response_code: 0
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.876]: Debug: [portalgrab] Subscribed closed session signal: 88
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.877]: Info: [portalgrab] Found stream for display: 'DP-1' position: 0x0 resolution: 1536x864
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.877]: Debug: [portalgrab] Unsubscribing closed session signal: 88
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.877]: Debug: [portalgrab] Explicitly closed portal session: /org/freedesktop/portal/desktop/session/1_128/Sunshine8
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.877]: Debug: [portalgrab] Start PW thread loop
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.877]: Info: [portalgrab] Requested frame rate [60fps]
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.888]: Info: [portalgrab] Loaded portal restore token from disk
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.889]: Debug: [portalgrab] Finalizing Portal security: dropping capabilities and resetting dumpable
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.890]: Debug: [portalgrab] RemoteDesktop CreateSession response_code: 0
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.890]: Debug: [portalgrab] RemoteDesktop CreateSession: got session handle: /org/freedesktop/portal/desktop/session/1_135/Sunshine9
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.896]: Debug: [portalgrab] SelectDevices response_code: 0
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.897]: Debug: [portalgrab] SelectSources response_code: 0
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.904]: Debug: [portalgrab] RemoteDesktop Start response_code: 0
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.906]: Debug: [portalgrab] Subscribed closed session signal: 99
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.907]: Info: [portalgrab] Streaming display 'DP-1' from position: 0x0 resolution: 1536x864
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.907]: Debug: [portalgrab] Setup PW context
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.908]: Debug: [portalgrab] Connect PW context to fd
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.908]: Debug: [portalgrab] Create PW stream
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.908]: Debug: [portalgrab] Connect PW stream - fd 41 node 68
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.908]: Debug: [portalgrab] PipeWire stream state: unconnected -> connecting
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.909]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.909]: Debug: [portalgrab] PipeWire stream state: connecting -> paused
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.911]: Info: [portalgrab] Video format: 12
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.911]: Info: [portalgrab] Size: 1920x1080
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.911]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.911]: Info: [portalgrab] using DMA-BUF buffers
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.912]: Info: [portalgrab] Video format: 12
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.912]: Info: [portalgrab] Size: 1920x1080
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.912]: Info: [portalgrab] Framerate (from compositor): 0/1 (variable rate capture)
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.912]: Info: [portalgrab] using DMA-BUF buffers
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.912]: Debug: [portalgrab] PipeWire stream state: paused -> streaming
Apr 08 22:10:07 archlinux sunshine[10402]: [2026-04-08 22:10:07.918]: Info: [portalgrab] Using negotiated resolution 1920x1080
```

Same issue on GNOME:

```
Apr 08 22:14:05 archlinux sunshine[13437]: [2026-04-08 22:14:05.326]: Debug: [portalgrab] PipeWire stream state: streaming -> paused
Apr 08 22:14:06 archlinux sunshine[13437]: [2026-04-08 22:14:06.328]: Warning: [portalgrab]: wait for dbus
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.328]: Warning: [portalgrab] PipeWire stream disconnected. Forcing session reset.
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.348]: Debug: [portalgrab] Destroying pipewire_t
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.348]: Debug: [portalgrab] Stop PW thread loop
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.348]: Debug: [portalgrab] Cleaning up stream
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.348]: Debug: [portalgrab] Stop fill_img
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.348]: Debug: [portalgrab] Disconnect stream
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.348]: Debug: [portalgrab] PipeWire stream state: paused -> unconnected
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Debug: [portalgrab] Destroy stream
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Debug: [portalgrab] Disconnect PW core
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Debug: [portalgrab] Destroy PW context
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Debug: [portalgrab] Close pipewire_fd
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Debug: [portalgrab] Stop PW thread loop
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Debug: [portalgrab] Destroy PW thread loop
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Debug: [portalgrab] Unsubscribing closed session signal: 77
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Warning: [portalgrab] Failed to explicitly close portal session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/session/1_116/Sunshine7”
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.349]: Info: [portalgrab] Loaded portal restore token from disk
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.350]: Debug: [portalgrab] Finalizing Portal security: dropping capabilities and resetting dumpable
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.351]: Debug: [portalgrab] RemoteDesktop CreateSession response_code: 0
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.351]: Debug: [portalgrab] RemoteDesktop CreateSession: got session handle: /org/freedesktop/portal/desktop/session/1_116/Sunshine8
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.357]: Debug: [portalgrab] SelectDevices response_code: 0
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.357]: Debug: [portalgrab] SelectSources response_code: 0
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.367]: Debug: [portalgrab] RemoteDesktop Start response_code: 0
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.368]: Debug: [portalgrab] Subscribed closed session signal: 88
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.369]: Info: [portalgrab] Found stream for display: 'DP-1' position: 0x0 resolution: 1920x1080
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.369]: Debug: [portalgrab] Unsubscribing closed session signal: 88
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.370]: Debug: [portalgrab] Explicitly closed portal session: /org/freedesktop/portal/desktop/session/1_116/Sunshine8
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.370]: Debug: [portalgrab] Start PW thread loop
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.370]: Info: [portalgrab] Requested frame rate [60fps]
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.378]: Info: [portalgrab] Loaded portal restore token from disk
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.379]: Debug: [portalgrab] Finalizing Portal security: dropping capabilities and resetting dumpable
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.381]: Debug: [portalgrab] RemoteDesktop CreateSession response_code: 0
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.381]: Debug: [portalgrab] RemoteDesktop CreateSession: got session handle: /org/freedesktop/portal/desktop/session/1_122/Sunshine9
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.387]: Debug: [portalgrab] SelectDevices response_code: 0
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.387]: Debug: [portalgrab] SelectSources response_code: 0
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.395]: Debug: [portalgrab] RemoteDesktop Start response_code: 0
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.396]: Debug: [portalgrab] Subscribed closed session signal: 99
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.397]: Info: [portalgrab] Streaming display 'DP-1' from position: 0x0 resolution: 1920x1080
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.397]: Debug: [portalgrab] Setup PW context
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.398]: Debug: [portalgrab] Connect PW context to fd
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.398]: Debug: [portalgrab] Create PW stream
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.398]: Debug: [portalgrab] Connect PW stream - fd 41 node 100
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.398]: Debug: [portalgrab] PipeWire stream state: unconnected -> connecting
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.398]: Info: [portalgrab] Connected to pipewire version 1.6.2
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.398]: Debug: [portalgrab] PipeWire stream state: connecting -> paused
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.401]: Info: [portalgrab] Video format: 12
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.401]: Info: [portalgrab] Size: 1920x1080
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.401]: Info: [portalgrab] Framerate (from compositor): 0/1
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.401]: Info: [portalgrab] Framerate (from compositor, max): 60/1
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.401]: Info: [portalgrab] using DMA-BUF buffers
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.402]: Info: [portalgrab] Video format: 12
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.402]: Info: [portalgrab] Size: 1920x1080
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.402]: Info: [portalgrab] Framerate (from compositor): 0/1
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.402]: Info: [portalgrab] Framerate (from compositor, max): 60/1
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.402]: Info: [portalgrab] using DMA-BUF buffers
Apr 08 22:14:08 archlinux sunshine[13437]: [2026-04-08 22:14:08.403]: Debug: [portalgrab] PipeWire stream state: paused -> streaming
```

I also checked to see if it's an issue related to an idle desktop not firing callbacks, but keeping 60fps content running on the desktop while clicking the XDG icon has the same result.

**Comment by Kishi85** [comment]
> Unfortunately the XDG stop still doesn't stop for me on KDE or GNOME. My CPU should not be excessively slow (5700X), but I tried bumping the wait time to eliminate the possibility:
...
> 
> I also checked to see if it's an issue related to an idle desktop not firing callbacks, but keeping 60fps content running on the desktop while clicking the XDG icon has the same result.

I've changed the check to do a synchronized call (that fetches the version property of the portal.Session) and if that one fails then the portal must have closed.

Could you try with the latest version of this PR? It should work there, if it's still broken then something very weird is going on and the pipewire stream pauses/stops before the portal closed.

**Comment by psyke83** [comment]
It's working now! The previous iteration of your PR was failing on my setup due to my `system_tray = disabled` config seemingly interfering with the `g_dbus_connection_signal_subscribe` call persisting. I didn't have time to check any deeper due to your refresh; the latest changes have correct XDG stop behaviour when `system_tray` is enabled or disabled. I also checked resolution change and it's still working fine on GNOME and KDE.

Apologies for not specifying my config earlier; I didn't expect that the systray setting would have such an interaction with portalgrab that we were seeing here.

**Comment by Kishi85** [comment]
All good. Honestly I'd never have guessed that the system tray would have interacted with the signaling. It's still better to do it with a calling a DBus Method on the session anyway as that gives an immediate and correct result without having to worry about synchronizing states between DBus and Pipewire. Also less complexity to understand if someone else has to look at it again.

**Comment by ReenigneArcher** [comment]
> system_tray = disabled

FYI, I believe the original cause (crashing) for people disabling the tray was resolved in the following PRs

- https://github.com/LizardByte/tray/pull/86 (also resolved random unit test failures in the tray library)
- https://github.com/LizardByte/Sunshine/pull/4894

I'm also moving to a new tray backend on Linux in https://github.com/LizardByte/Sunshine/pull/4907

**Comment by Kishi85** [comment]
@ReenigneArcher Since we've fixed all fixable issues @psyke83 had so far this PR it should be good to go (at least for another CI run).

Would it be possible to do the final merge without squashing the commits? or should I consider putting them into separate PRs? 
I've tried to fix pre-requisite issues in separate commits (with proper semantic commit messages) so the final one can implement the feature in a working condition and I think it would be helpful (for future referencing) not to squash everything into one huge commit.

**Comment by ReenigneArcher** [comment]
> Would it be possible to do the final merge without squashing the commits? or should I consider putting them into separate PRs?

Unfortunately not, the repo forces squash and merge, because the date of the commit will be used for the newly created pre-release. If we use the original commits instead of squashing then the new pre-release would end up being a lower version than the current pre-release

**Comment by Kishi85** [comment]
I see. Thanks for the explanation. Also since the squashed commit seems to reference back to this PR with the separate commits that should be sufficient anyway.

**Review by ReenigneArcher — APPROVED** [review]
