### PR TITLE
fix(confighttp): do not return 200 on errors

### LINKED ISSUE #3384: Beta API: POST /api/apps returns 200 OK on invalid input JSON
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

I'm too lazy to test

### Describe the Bug

When using the Beta API, a POST request to /api/apps with invalid input JSON will return a response of 200 OK, with a JSON document that describes the error. It should respond with 400 Bad Request.

### Expected Behavior

Invalid POST request to /api/apps should return 400 Bad Request

### Additional Context

_No response_

### Host Operating System

Linux

### Operating System Version

Linux aizen 6.11.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:35 +0000 x86_64 GNU/Linux

### Architecture

amd64/x86_64

### Sunshine commit or version

0.23.1

### Package

Linux - AUR (Third Party)

### GPU Type

n/a

### GPU Model

n/a

### GPU Driver/Mesa Version

n/a

### Capture Method

None

### Config

_No response_

### Apps

_No response_

### Relevant log output

```shell
n/a
```

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

- Return 400 status code on config API errors
- Add `default_resource` for requests that are not `GET`
- Remove trailing commas in API examples
- Clarify how `index` works when saving an app
- Change xml responses to json
- Add grouped tab code examples to API docs

TODO:

- [x] fix fail guards, per `@FrogTheFrog`
- [x] add tabbed examples for each endpoint in docs. e.g. curl, python, javascript, powershell
- [x] trying to delete app way out of index range shows as success
  ```
  >curl -u user:pass -X DELETE -k https://localhost:47990/api/apps/5000
  {
      "status": "true"
  }
  ```
  Note: existing check was useless since it could never actually be fired ( < 0 is not possible due to the regex of the endpoint), instead changed it to a clamp and checked the upper bounds.

### Screenshot

image
image
image

### Issues Fixed or Closed

- Fixes #3384

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385) **Quality Gate failed**
> 
> Failed conditions  [1 New issue](https://sonarcloud.io/project/issues?id=LizardByte_Sunshine&pullRequest=3385&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)  [1 New Code Smells](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385) (required ≤ 0)
> 
> [See analysis details on SonarQube Cloud](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385)
> 
>  Catch issues before they fail your Quality Gate with our IDE extension  [SonarQube for IDE](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=pull-request)

Code doesn't compile with suggested change.

File: src/confighttp.cpp [hunk 1]
```diff
@@ -501,33 +554,32 @@ namespace confighttp {
...
     catch (std::exception &e) {
       BOOST_LOG(warning) << "DeleteApp: "sv << e.what();
-      outputTree.put("status", "false");
-      outputTree.put("error", "Invalid File JSON");
+      bad_request(response, request, e.what());
       return;
     }
 
     outputTree.put("status", "true");
+    outputTree.put("result", "application " + request->path_match[1] + " deleted");
```
Comment (ReenigneArcher) [inline src/confighttp.cpp:582]: This fails on Unix

File: src/confighttp.cpp [hunk 2]
```diff
@@ -501,33 +554,32 @@ namespace confighttp {
       auto &apps_node = fileTree.get_child("apps"s);
       int index = stoi(request->path_match[1]);
 
-      if (index < 0) {
-        outputTree.put("status", "false");
-        outputTree.put("error", "Invalid Index");
+      if (std::clamp(index, 0, static_cast<int>(apps_node.size()) - 1) != index) {
+        bad_request(response, request, "index out of range, max index is "s + std::to_string(apps_node.size() - 1));
```
Comment (ReenigneArcher) [inline src/confighttp.cpp:558]: use `std::format`

File: src/confighttp.cpp [hunk 3]
```diff
@@ -142,18 +142,65 @@ namespace confighttp {
...
+   * @brief Send a 400 Bad Request response.
+   * @param response The original response object.
+   * @param request The original request object.
+   * @param error_message The error message to include in the response.
+   */
+  void
+  bad_request(resp_https_t response, [[maybe_unused]] req_https_t request, const std::string &error_message) {
+    pt::ptree tree;
+    tree.put("status_code", 400);
+    tree.put("error", error_message);
```
Comment (ReenigneArcher) [inline src/confighttp.cpp:195]:
```suggestion
    tree.put("status_code", 400);
    tree.put("status", false);
    tree.put("error", error_message);
```

File: src/confighttp.cpp [hunk 4]
```diff
@@ -501,33 +554,32 @@ namespace confighttp {
...
     }
     catch (std::exception &e) {
       BOOST_LOG(warning) << "DeleteApp: "sv << e.what();
-      outputTree.put("status", "false");
-      outputTree.put("error", "Invalid File JSON");
+      bad_request(response, request, e.what());
       return;
     }
 
     outputTree.put("status", "true");
```
Comment (ReenigneArcher) [inline src/confighttp.cpp:581]:
```suggestion
    outputTree.put("status", true);
```

File: docs/api.js [hunk 5]
```diff
@@ -0,0 +1,130 @@
+function generateExamples(endpoint, method, body = null) {
+  let curlBodyString = '';
+  let psBodyString = '';
+
+  if (body) {
+    const jsonString = JSON.stringify(body).replace(/"/g, '\\"');
+    curlBodyString = ` -d "${jsonString}"`;
```
Comment (ReenigneArcher) [inline docs/api.js:7]:
```suggestion
    const curlJsonString = JSON.stringify(body).replace(/"/g, '\\"');
    curlBodyString = ` -d "${curlJsonString}"`;
```

**Comment by ReenigneArcher** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385) **Quality Gate failed**
> 
> Failed conditions  [2 New issues](https://sonarcloud.io/project/issues?id=LizardByte_Sunshine&pullRequest=3385&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)  [2 New Code Smells](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385) (required ≤ 0)
> 
> [See analysis details on SonarQube Cloud](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385)
> 
>  Catch issues before they fail your Quality Gate with our IDE extension  [SonarQube for IDE](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=pull-request)

`std::format` is not available in gcc 11

**Comment by ReenigneArcher** [comment]
I guess we can't return valid int/boolean json?

```json
{
    "status_code": 400,
    "status": false,
    "error": "index out of range, max index is 1"
}
```

instead of:
```json
{
    "status_code": "400",
    "status": "false",
    "error": "index out of range, max index is 1"
}
```

File: src/confighttp.cpp [hunk 6]
```diff
@@ -142,21 +176,78 @@ namespace confighttp {
...
   }
 
   /**
+   * @brief Send a 400 Bad Request response.
+   * @param response The HTTP response object.
+   * @param request The HTTP request object.
+   * @param error_message The error message to include in the response.
+   */
+  void
+  bad_request(resp_https_t response, [[maybe_unused]] req_https_t request, const std::string &error_message) {
```
Comment (FrogTheFrog) [inline src/confighttp.cpp:230]:
```suggestion
  bad_request(resp_https_t response, [[maybe_unused]] req_https_t request, const std::string &error_message = "Invalid Request") {
```

If we do this, could we perhaps get rid of `bad_request_default`?

File: src/confighttp.cpp [hunk 7]
```diff
@@ -285,12 +417,23 @@ namespace confighttp {
...
     return *(relPath.begin()) != fs::path("..");
   }
 
+  /**
+   * @brief Get an asset from the node_modules directory.
+   * @param response The HTTP response object.
+   * @param request The HTTP request object.
+   */
   void
   getNodeModules(resp_https_t response, req_https_t request) {
```
Comment (FrogTheFrog) [inline src/confighttp.cpp:438]: This function returns `bad_request` and could use your function perhaps? In one case it does not return anything so maybe it should also return bad request n that case?

File: src/confighttp.cpp [hunk 8]
```diff
@@ -399,18 +548,13 @@ namespace confighttp {
...
     pt::ptree outputTree;
-    auto g = util::fail_guard([&]() {
-      std::ostringstream data;
-
-      pt::write_json(data, outputTree);
-      response->write(data.str());
-    });
-
-    pt::ptree inputTree, fileTree;
+    send_response(response, outputTree);
```
Comment (FrogTheFrog) [inline src/confighttp.cpp:551]: This should be at the very back of the function

File: src/confighttp.cpp [hunk 9]
```diff
@@ -467,67 +611,63 @@ namespace confighttp {
...
-      outputTree.put("status", "false");
-      outputTree.put("error", "Invalid File JSON");
+      bad_request(response, request, e.what());
       return;
     }
 
-    outputTree.put("status", "true");
+    outputTree.put("status", true);
+    outputTree.put("result", "application "s + std::to_string(index) + " deleted");
+    send_response(response, outputTree);
```
Comment (FrogTheFrog) [inline src/confighttp.cpp:670]: To follow the previous logic, this should be at the very end of the function.

File: src/confighttp.cpp [hunk 10]
```diff
@@ -551,6 +693,16 @@ namespace confighttp {
...
+    try {
+      pt::read_json(ss, inputTree);
+    }
+    catch (std::exception &e) {
+      BOOST_LOG(warning) << "UploadCover: "sv << e.what();
+      bad_request(response, request, e.what());
+      return;
+    }
+
     auto g = util::fail_guard([&]() {
```
Comment (FrogTheFrog) [inline src/confighttp.cpp:706]: Perhaps this one also should be removed by calling `bad_request` where the `outputTree.put("error", "...");` is used instead? Also sending a normal response in the end.

File: src/confighttp.cpp [hunk 11]
```diff
@@ -467,67 +611,63 @@ namespace confighttp {
...
     }
     catch (std::exception &e) {
       BOOST_LOG(warning) << "DeleteApp: "sv << e.what();
-      outputTree.put("status", "false");
-      outputTree.put("error", "Invalid File JSON");
+      bad_request(response, request, e.what());
       return;
     }
 
-    outputTree.put("status", "true");
```
Comment (FrogTheFrog) [inline src/confighttp.cpp:530]: This exclusion from the try...catch block seems strange. Could we move it at the end of the try block? Then in the catch block we would need to return.

This applies everywhere and also is just a personal preference, so this point can be ignored.

**Review by FrogTheFrog — CHANGES_REQUESTED** [review]
I mostly looked at `cpp` code. Other files seem fine.

File: src/confighttp.cpp (hunk 11 above)
Comment (ReenigneArcher) [reply src/confighttp.cpp:530]: Yes, although I didn't because I didn't think it would be likely/possible to cause an exception. I am used to more explicit try/catches instead of these huge ones though.

File: src/confighttp.cpp [hunk 12]
```diff
@@ -464,71 +587,66 @@ namespace confighttp {
...
+      pt::ptree newApps;
       pt::read_json(config::stream.file_apps, fileTree);
       auto &apps_node = fileTree.get_child("apps"s);
-      int index = stoi(request->path_match[1]);
+      index = stoi(request->path_match[1]);
 
-      if (index < 0) {
-        outputTree.put("status", "false");
-        outputTree.put("error", "Invalid Index");
+      if (std::clamp(index, 0, static_cast<int>(apps_node.size()) - 1) != index) {
```
Comment (FrogTheFrog) [inline src/confighttp.cpp:624]:
```suggestion
      if (index < 0 && index >= static_cast<int>(apps_node.size())) {
```

Congrats, c++ standard sends love!
"If `lo` is greater than `hi`, the behavior is undefined."

This will be the case when `size()` returns `0`.

**Review by FrogTheFrog — CHANGES_REQUESTED** [review]

File: src/confighttp.cpp [hunk 13]
```diff
@@ -464,71 +586,66 @@ namespace confighttp {
...
+      pt::ptree newApps;
       pt::read_json(config::stream.file_apps, fileTree);
       auto &apps_node = fileTree.get_child("apps"s);
-      int index = stoi(request->path_match[1]);
+      index = stoi(request->path_match[1]);
 
-      if (index < 0) {
-        outputTree.put("status", "false");
-        outputTree.put("error", "Invalid Index");
+      if (index < 0 && index >= static_cast<int>(apps_node.size())) {
```
Comment (FrogTheFrog) [inline src/confighttp.cpp:623]:
```suggestion
      if (index < 0 || index >= static_cast<int>(apps_node.size())) {
```
