### PR TITLE
Add workaround for RTX HDR driver bug

### LINKED ISSUE #2163: After enabling RTX HDR globally on 551.61 drivers, Sunshine cannot start.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Today, after updating to the beta version of the driver, Sunshine cannot start after modifying the Alt key to replace the Win key and allowing local network connections in the web UI.

### Expected Behavior

_No response_

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

windows11

### Architecture

64 bit

### Sunshine commit or version

v0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3060

### GPU Driver/Mesa Version

551.61

### Capture Method (Linux Only)

_No response_

### Config

```Shell
channels = 2
address_family = both
min_log_level = 0
origin_web_ui_allowed = wan
upnp = enabled
key_rightalt_to_key_win = enabled
```

### Apps

_No response_

### Relevant log output

```shell
+ System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-02-23T09:27:46.2384765Z 
 
   EventRecordID 7880 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  6368 
   [ ThreadID]  1056 
 
   Channel Application 
 
   Computer DESKTOP-DQ5R9CA 
 
  - Security 

   [ UserID]  S-1-5-18 
 

- EventData 

  AppName Sunshine.exe 
  AppVersion 0.21.0.0 
  AppTimeStamp 652ca473 
  ModuleName nvwgf2umx.dll 
  ModuleVersion 31.0.15.5161 
  ModuleTimeStamp 65cdf06b 
  ExceptionCode c0000005 
  FaultingOffset 000000000139e799 
  ProcessId 0x9f0 
  ProcessCreationTime 0x1da663a8ecad17a 
  AppPath C:\Program Files\Sunshine\Sunshine.exe 
  ModulePath C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_830091b3ebd4b98a\nvwgf2umx.dll 
  IntegratorReportId 1e8136f1-2bf7-44c7-8705-4a4bf12e2f15 
  PackageFullName  
  PackageRelativeAppId
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
This reworks our dummy image handling to avoid triggering a driver bug with 551.61 drivers and RTX HDR enabled. It also provides a small performance improvement for that (uncommon) case of interacting with dummy image textures.

### Issues Fixed or Closed
Fixes #2163

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by robbiered** [comment]
As a note, a temporary workaround for the repeat crashing is disable HDR in windows.

**Comment by ChrisBln2302** [comment]
Does this also fix the issue that HDR is not streamed properly when RTX-HDR is enabled for a game?

File: src/platform/windows/display_vram.cpp [hunk 1]
```diff
@@ -1458,8 +1458,13 @@ namespace platf::dxgi {
 
     HRESULT status;
     if (dummy) {
-      auto dummy_data = std::make_unique<std::uint8_t[]>(img->row_pitch * img->height);
-      std::fill_n(dummy_data.get(), img->row_pitch * img->height, 0);
+      // To avoid crashing with RTX HDR enabled on version 551.61 of the Nvidia drivers, we double the
+      // size of the dummy data allocation. The driver appears to be internally adjusting our texture
+      // to be FP16 (probably due to D3D11_BIND_RENDER_TARGET), but it forgets that the amount of data
+      // we provided corresponds to the original texture format, not the new one it upconverted to.
+      auto dummy_data_size = img->row_pitch * img->height * 2;
```
Comment (RStanbouly) [inline src/platform/windows/display_vram.cpp:1465]: Nit : put img->row_pitch wave img->height in parenthesis to make it clear that you're doubling everything, not just the height, but otherwise LGTM

**Review by RStanbouly — APPROVED** [review]
Nit is relatively minor, otherwise lgtm and it doesn't seem to be failing any checks.

File: src/platform/windows/display_vram.cpp (hunk 1 above)
Comment (ReenigneArcher) [reply src/platform/windows/display_vram.cpp:1465]: I think it's already clear that everything is doubled, since everything here is multiplied together. Not to mention the comment above clearly suggests that it's being doubled.

Comment (RStanbouly) [reply src/platform/windows/display_vram.cpp:1465]: Like I said, minor nit, personally I feel like (x * y) * 2 reads better, but I'm fine with what currently exists.

**Comment by cgutman** [comment]
The minimal workaround turned out to not really be suitable as there were still some major stability issues with this texture upload codepath in the driver, even when it didn't crash by overreading our buffer (the event log was full of GPU error logs from nvlddmkm). I had to resort to a more complex fix, but it at least provides (small) performance benefits for all cases.
