### PR TITLE
fix(linux): multi-GPU segfault + wlr GPU auto selection, DMA-BUF metadata planes and revert wlr vulkan support

### LINKED ISSUE #5018: Broken capture method: wlroots
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

I'm on Arch Linux, using hyprland. I use the wlroots capture method (to be able to stream virtual displays, but the issue occurs with real displays too). When starting a stream with Moonlight, I get a black screen, connection terminated with error code -1. Sunshine does not crash, and I still have to manually stop the session.

### Expected Behavior

Streaming from Sunshine to Moonlight works.

### Additional Context

I have tested some older verions a still had in my pacman cache. The last working version of `sunshine-git` is `2026.330.150440-1`, the first broken one `2026.407.170539-1` (So the problem was introduced inbetween, and this is not a hyprland issue, since current hyprland works with older Sunshine version). The issue still persists with the latest version (`2026.415.34134-1`) installed.

### Host Operating System

Linux

### Operating System Version

Arch Linux; full system upgrade on 2026-04-17

### Architecture

amd64/x86_64

### Package

Linux - LizardByte/pacman-repo

### GPU Type

NVIDIA

### GPU Model

NVIDIA GeForce RTX 3060

### GPU Driver/Mesa Version

nvidia-open-dkms 595.58.03-2

### Capture Method

wlroots (Linux)

### Apps

```json
issue persist on all apps (including just Desktop without prep scripts)
```

### Log output

```shell
see gist
```

### Online logs

https://gist.github.com/tm-frs/1db4c749bf258e2d12aeea21eb961689

### LINKED ISSUE #5023: wlr-screencopy capture targets wrong render node on multi-GPU NVIDIA systems, causing FD leak and VRAM exhaustion via failed dmabuf imports
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Summary
On a system with two NVIDIA GPUs and a wlroots-based compositor (Hyprland), Sunshine's `capture = wlr` path attempts dmabuf imports on a render node different from the one the compositor rendered to. Cross-device dmabuf imports fail on the NVIDIA open driver. The failure path leaks the imported FD and the kernel-side buffer allocation, and the import is retried in a tight loop with no backoff. Within ~20 seconds, GPU memory on the wrong card is fully exhausted (32 GB), and Sunshine accumulates ~1000 open FDs against `/dev/dri/renderD129`.

Setting `adapter_name = /dev/dri/renderD128` in `sunshine.conf` resolves the issue, suggesting `adapter_name` steers capture-side device selection but is not the default and is not documented as required for multi-GPU setups.

### Environment
- Sunshine: 2025.924.154138 (nixpkgs build, NVENC + CUDA enabled)
- OS: NixOS 25.11 (Xantusia), kernel 6.19.10
- Driver: NVIDIA 595.58.03 (open modules), CUDA 13.2
- GPUs: 2× RTX 5090 (GB202)
  - GPU 0: bus 0x41, card1, renderD128 (x16, has connected display)
  - GPU 1: bus 0x42, card0, renderD129 (x4, no display)
- Compositor: Hyprland (uwsm session via GDM autologin)
- Hyprland pinned to GPU 0 via `AQ_DRM_DEVICES=/dev/dri/card1`
- Sunshine env has `DRI_PRIME=pci-0000_41_00_0` and `CUDA_VISIBLE_DEVICES` pinned to GPU 0 — both ignored by the wlr capture path

### Reproduction
1. Multi-GPU NVIDIA system with `nvidia-drm.modeset=1`, open driver
2. wlroots-based compositor pinned to one GPU
3. Sunshine config: `capture = wlr`, `encoder = nvenc`, no `adapter_name`
4. Connect a Moonlight client

### Actual behavior
- Sunshine logs `Error: Failed to create buffer from params` repeatedly (multiple times per second)
- Stream never starts (black screen on client, eventually times out)
- FD count on Sunshine process climbs from ~30 to ~1000 within seconds, all targeting the wrong render node
- VRAM on the wrong GPU climbs to 32 GB
- Kernel logs: `[drm] [nvidia-drm] [GPU ID 0x00004200] Failed to allocate NVKMS video memory for GEM object, trying to fall back to sysmem` (repeated)

### FD breakdown during leak (Sunshine PID, ~30s into Moonlight connect)
Total FDs: ~1000
DRI device usage:
~990 /dev/dri/renderD129    ← wrong GPU
~5 /dev/dri/renderD128    ← correct GPU (compositor's device)

### Workaround
Add to `sunshine.conf`:
adapter_name = /dev/dri/renderD128   # path to the render node of the GPU running the compositor
With this set, FDs stay flat (~99), VRAM on the secondary GPU stays at 2 MB, stream works correctly.

### Suspected root cause
The wlr-screencopy capture code path appears to auto-select a render device for dmabuf import without consulting `adapter_name`, `DRI_PRIME`, or the device the compositor advertises in the dmabuf feedback. When the auto-selected device differs from the compositor's device, every import fails on NVIDIA (cross-device dmabuf isn't supported with these modifiers), and the failure path doesn't release the FD or the speculative kernel-side buffer allocation. Tight retry without backoff turns the per-frame leak into rapid VRAM exhaustion.

Two distinct issues, both worth addressing:
1. **Device selection**: capture should honor `adapter_name` (or auto-detect from the compositor's dmabuf feedback) — this is the primary fix
2. **Cleanup on failure**: the dmabuf import failure path should release resources before retrying, and the retry should have backoff

Happy to file (2) as a separate issue if preferred.

### Expected Behavior

Stream starts. FDs and VRAM on the non-capture GPU stay near zero.

### Additional Context

_No response_

### Host Operating System

Linux

### Operating System Version

NixOS 25.11 (Xantusia), kernel 6.19.10

### Architecture

amd64/x86_64

### Package

Linux - nixpkgs (Third Party)

### GPU Type

NVIDIA

### GPU Model

Dual RTX 5090

### GPU Driver/Mesa Version

NVIDIA 595.58.03 (open modules), CUDA 13.2

### Capture Method

wlroots (Linux)

### Apps

```json

```

### Log output

```shell

```

### Online logs

_No response_

### LINKED ISSUE #5034: DMA-BUF Failed
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

1. Run Sunshine flatpak
2. Connect (in my case from OSX)
3. Quickly start game and enjoy several hours of gaming or switch between multiple applications and be disconnected within seconds.

Sunshine errors and kills itself, could be after a few seconds, could be after a 3 hours gaming sessions, often it happens when you quit an application on the host.

```log
[2026-04-20 08:26:37.071]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:37.071]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:37.071]: Info: Color depth: 8-bit
[2026-04-20 08:26:37.071]: Info: Color range: MPEG
[2026-04-20 08:26:37.095]: Info: Streaming bitrate is 14988000
[2026-04-20 08:26:37.096]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:37.096]: Info: Minimum FPS target set to ~30fps (33.3333ms)
[2026-04-20 08:26:37.097]: Error: vkCreateImage for DMA-BUF failed: -1000158000 (modifier=0x200000028a01f04, pitch=24, offset=772)
[2026-04-20 08:26:37.097]: Error: Failed to import DMA-BUF
[2026-04-20 08:26:37.097]: Error: Could not convert image
```

### Expected Behavior

Ideally Sunshine doesn't error out and exit.

### Additional Context

I'm on an immutable distro, maybe it's causing additional issues I don't know but XDG Portal via flatpak finally works for me (KMS was a real pain to get working at times).

Using Steam Remote Play does not show any issues (maybe it's using a different capture altogether I don't know) but I'd prefer Sunshine over it.

Here is a video showcasing the error.
I'm remote into my host (RDP), start Sunshine flatpak, disconnect RDP, connect via Moonlight instead, Sunshine crashes almost immediately. (There is no difference if do all of this locally and not via RDP)

https://github.com/user-attachments/assets/2599813e-0396-4429-be8f-3a55a367f6b3

### Host Operating System

Linux

### Operating System Version

OpenSUSE Aeon

### Architecture

amd64/x86_64

### Package

Linux - flathub/flatpak

### GPU Type

AMD

### GPU Model

AMD Radeon RX 7900 XT (RADV NAVI31)

### GPU Driver/Mesa Version

26.0.4-1.1

### Capture Method

XDG Portal Grab (Linux)

### Apps

```json

```

### Log output

```shell
[2026-04-20 08:26:19.207465] [0x00007f4da0e9f000] [info]    config: 'upnp' = enabled
[2026-04-20 08:26:19.207486] [0x00007f4da0e9f000] [info]    config: 'output_name' = 0
[2026-04-20 08:26:19.207]: Info: Sunshine version: 2026.419.214410 commit: a5af790710b646c9a31e1f47ccabc31ff5d7f796
[2026-04-20 08:26:19.207]: Info: Package Publisher: LizardByte
[2026-04-20 08:26:19.207]: Info: Publisher Website: https://app.lizardbyte.dev
[2026-04-20 08:26:19.207]: Info: Get support: https://app.lizardbyte.dev/support
[2026-04-20 08:26:19.207]: Info: config: 'output_name' = 0
[2026-04-20 08:26:19.207]: Info: config: 'upnp' = enabled
Cannot load libcuda.so.1
[2026-04-20 08:26:19.208]: Error: Couldn't load cuda: -1
[2026-04-20 08:26:19.208]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:19.208]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:19.208]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:19.208]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:19.208]: Warning: [wlgrab] Missing Wayland wire for wlr-export-dmabuf
[2026-04-20 08:26:19.208]: Error: Failed to gain CAP_SYS_ADMIN
[2026-04-20 08:26:19.208]: Info: /dev/dri/card0 -> amdgpu
[2026-04-20 08:26:19.209]: Error: Failed to gain CAP_SYS_ADMIN
[2026-04-20 08:26:19.209]: Info: /dev/dri/card1 -> amdgpu
[2026-04-20 08:26:19.209]: Error: Failed to gain CAP_SYS_ADMIN
[2026-04-20 08:26:19.209]: Error: Couldn't get handle for DRM Framebuffer [385]: Probably not permitted
[2026-04-20 08:26:19.209]: Error: AppImage and Flatpak do not support KMS capture. Use another capture method.
[2026-04-20 08:26:19.209]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:19.209]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:19.209]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:19.209]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:19.209]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:19.210]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:19.210]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:19.210]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:19.210]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:19.210]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:19.210]: Info: -------- Start of KMS monitor list --------
[2026-04-20 08:26:19.210]: Info: --------- End of KMS monitor list ---------
[2026-04-20 08:26:19.210]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:19.273]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2026-04-20 08:26:19.273]: Info: Trying encoder [nvenc]
[2026-04-20 08:26:19.273]: Info: Screencasting with XDG portal
[2026-04-20 08:26:19.274]: Info: [pipewire] Requested frame rate [60/1, approx. 60 fps]
[2026-04-20 08:26:19.274]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:19.281]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:19.303]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:19.303]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:19.303]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:19.303]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:19.303]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:19.303]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:19.303]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:19.303]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:19.303]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:19.304]: Info: [portalgrab] Using first available stream as no matching stream was found for: '0'
[2026-04-20 08:26:19.304]: Info: [pipewire] Streaming display '0' from position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:19.305]: Info: [pipewire] Connected to pipewire version 1.6.2
[2026-04-20 08:26:19.310]: Info: [pipewire] Pipewire Error, id:2 seq:13 message: no more input formats
[2026-04-20 08:26:20.813]: Info: Creating encoder [h264_nvenc]
[2026-04-20 08:26:20.813]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:20.813]: Info: Color depth: 8-bit
Cannot load libcuda.so.1
[2026-04-20 08:26:20.813]: Info: Color range: JPEG
[2026-04-20 08:26:20.813]: Error: Couldn't load cuda: -1
Cannot load libcuda.so.1
[2026-04-20 08:26:20.813]: Info: Creating encoder [h264_nvenc]
[2026-04-20 08:26:20.813]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:20.813]: Info: Color depth: 8-bit
[2026-04-20 08:26:20.813]: Info: Color range: JPEG
[2026-04-20 08:26:20.813]: Error: Couldn't load cuda: -1
[2026-04-20 08:26:20.813]: Info: Encoder [nvenc] failed
[2026-04-20 08:26:20.815]: Info: Trying encoder [vulkan]
[2026-04-20 08:26:20.815]: Info: Screencasting with XDG portal
[2026-04-20 08:26:20.815]: Info: [pipewire] Requested frame rate [60/1, approx. 60 fps]
[2026-04-20 08:26:20.815]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:20.820]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:20.847]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:20.848]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:20.848]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:20.848]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:20.848]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:20.848]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:20.848]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:20.848]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:20.848]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:20.849]: Info: [portalgrab] Using first available stream as no matching stream was found for: '0'
[2026-04-20 08:26:20.849]: Info: [pipewire] Streaming display '0' from position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:20.850]: Info: [pipewire] Connected to pipewire version 1.6.2
[2026-04-20 08:26:20.854]: Info: [pipewire] Pipewire Error, id:2 seq:13 message: no more input formats
[2026-04-20 08:26:22.358]: Info: Creating encoder [h264_vulkan]
[2026-04-20 08:26:22.358]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:22.358]: Info: Color depth: 8-bit
[2026-04-20 08:26:22.358]: Info: Color range: JPEG
[2026-04-20 08:26:22.383]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:22.383]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:22.394]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:22.394]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:22.394]: Info: Color depth: 8-bit
[2026-04-20 08:26:22.394]: Info: Color range: JPEG
[2026-04-20 08:26:22.416]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:22.417]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:22.427]: Info: Creating encoder [av1_vulkan]
[2026-04-20 08:26:22.427]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:22.427]: Info: Color depth: 8-bit
[2026-04-20 08:26:22.427]: Info: Color range: JPEG
[2026-04-20 08:26:22.449]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:22.449]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:22.459]: Info: Screencasting with XDG portal
[2026-04-20 08:26:22.459]: Info: [pipewire] Requested frame rate [60/1, approx. 60 fps]
[2026-04-20 08:26:22.459]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:22.464]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:22.498]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:22.498]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:22.498]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:22.498]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:22.498]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:22.498]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:22.498]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:22.498]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:22.498]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:22.499]: Info: [portalgrab] Using first available stream as no matching stream was found for: '0'
[2026-04-20 08:26:22.499]: Info: [pipewire] Streaming display '0' from position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:22.500]: Info: [pipewire] Connected to pipewire version 1.6.2
[2026-04-20 08:26:22.502]: Info: [pipewire] Pipewire Error, id:2 seq:13 message: no more input formats
[2026-04-20 08:26:24.008]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:24.008]: Info: Color coding: SDR (Rec. 709)
[2026-04-20 08:26:24.008]: Info: Color depth: 10-bit
[2026-04-20 08:26:24.008]: Info: Color range: JPEG
[2026-04-20 08:26:24.033]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:24.033]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:24.047]: Info: Creating encoder [av1_vulkan]
[2026-04-20 08:26:24.047]: Info: Color coding: SDR (Rec. 709)
[2026-04-20 08:26:24.047]: Info: Color depth: 10-bit
[2026-04-20 08:26:24.047]: Info: Color range: JPEG
[2026-04-20 08:26:24.070]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:24.070]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:24.082]: Info: 
[2026-04-20 08:26:24.082]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2026-04-20 08:26:24.082]: Info: 
[2026-04-20 08:26:24.082]: Info: Found H.264 encoder: h264_vulkan [vulkan]
[2026-04-20 08:26:24.082]: Info: Found HEVC encoder: hevc_vulkan [vulkan]
[2026-04-20 08:26:24.082]: Info: Found AV1 encoder: av1_vulkan [vulkan]
[2026-04-20 08:26:24.083]: Info: Starting system tray
[2026-04-20 08:26:24.084]: Info: Configuration UI available at [https://localhost:47990]
[2026-04-20 08:26:24.084]: Info: Adding avahi service basement

(sunshine:2): libayatana-appindicator-WARNING **: 08:26:24.099: libayatana-appindicator is deprecated. Please use libayatana-appindicator-glib in newly written code.
[2026-04-20 08:26:24.100]: Info: System tray created
[2026-04-20 08:26:24.100]: Info: Starting main loop

(sunshine:2): Gtk-CRITICAL **: 08:26:24.202: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[2026-04-20 08:26:24.952]: Info: Avahi service basement successfully established.
[2026-04-20 08:26:26.385]: Info: Completed UPnP port mappings to 192.168.111.10 via http://192.168.111.1:5000/rootDesc.xml
[2026-04-20 08:26:29.359]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2026-04-20 08:26:29.359]: Info: Trying encoder [nvenc]
[2026-04-20 08:26:29.359]: Info: Screencasting with XDG portal
[2026-04-20 08:26:29.359]: Info: [pipewire] Requested frame rate [60/1, approx. 60 fps]
[2026-04-20 08:26:29.359]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:29.365]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:29.398]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:29.398]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:29.398]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:29.398]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:29.398]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:29.398]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:29.398]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:29.398]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:29.398]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:29.399]: Info: [portalgrab] Using first available stream as no matching stream was found for: '0'
[2026-04-20 08:26:29.399]: Info: [pipewire] Streaming display '0' from position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:29.400]: Info: [pipewire] Connected to pipewire version 1.6.2
[2026-04-20 08:26:29.403]: Info: [pipewire] Pipewire Error, id:2 seq:13 message: no more input formats
[2026-04-20 08:26:30.909]: Info: Creating encoder [h264_nvenc]
[2026-04-20 08:26:30.909]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:30.909]: Info: Color depth: 8-bit
[2026-04-20 08:26:30.909]: Info: Color range: JPEG
Cannot load libcuda.so.1
[2026-04-20 08:26:30.909]: Error: Couldn't load cuda: -1
[2026-04-20 08:26:30.909]: Info: Encoder [nvenc] failed
[2026-04-20 08:26:30.911]: Info: Trying encoder [vulkan]
[2026-04-20 08:26:30.911]: Info: Screencasting with XDG portal
[2026-04-20 08:26:30.911]: Info: [pipewire] Requested frame rate [60/1, approx. 60 fps]
[2026-04-20 08:26:30.911]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:30.917]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:30.949]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:30.949]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:30.949]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:30.949]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:30.949]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:30.949]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:30.949]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:30.949]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:30.949]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:30.950]: Info: [portalgrab] Using first available stream as no matching stream was found for: '0'
[2026-04-20 08:26:30.950]: Info: [pipewire] Streaming display '0' from position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:30.951]: Info: [pipewire] Connected to pipewire version 1.6.2
[2026-04-20 08:26:30.953]: Info: [pipewire] Pipewire Error, id:2 seq:13 message: no more input formats
[2026-04-20 08:26:32.459]: Info: Creating encoder [h264_vulkan]
[2026-04-20 08:26:32.459]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:32.459]: Info: Color depth: 8-bit
[2026-04-20 08:26:32.459]: Info: Color range: JPEG
[2026-04-20 08:26:32.484]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:32.485]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:32.495]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:32.495]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:32.495]: Info: Color depth: 8-bit
[2026-04-20 08:26:32.495]: Info: Color range: JPEG
[2026-04-20 08:26:32.518]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:32.519]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:32.528]: Info: Creating encoder [av1_vulkan]
[2026-04-20 08:26:32.528]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:32.528]: Info: Color depth: 8-bit
[2026-04-20 08:26:32.528]: Info: Color range: JPEG
[2026-04-20 08:26:32.551]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:32.551]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:32.561]: Info: Screencasting with XDG portal
[2026-04-20 08:26:32.562]: Info: [pipewire] Requested frame rate [60/1, approx. 60 fps]
[2026-04-20 08:26:32.562]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:32.566]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:32.599]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:32.599]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:32.599]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:32.599]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:32.599]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:32.599]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:32.599]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:32.599]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:32.599]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:32.600]: Info: [portalgrab] Using first available stream as no matching stream was found for: '0'
[2026-04-20 08:26:32.600]: Info: [pipewire] Streaming display '0' from position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:32.601]: Info: [pipewire] Connected to pipewire version 1.6.2
[2026-04-20 08:26:32.603]: Info: [pipewire] Pipewire Error, id:2 seq:13 message: no more input formats
[2026-04-20 08:26:34.109]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:34.109]: Info: Color coding: SDR (Rec. 709)
[2026-04-20 08:26:34.109]: Info: Color depth: 10-bit
[2026-04-20 08:26:34.109]: Info: Color range: JPEG
[2026-04-20 08:26:34.134]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:34.135]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:34.149]: Info: Creating encoder [av1_vulkan]
[2026-04-20 08:26:34.149]: Info: Color coding: SDR (Rec. 709)
[2026-04-20 08:26:34.149]: Info: Color depth: 10-bit
[2026-04-20 08:26:34.149]: Info: Color range: JPEG
[2026-04-20 08:26:34.171]: Info: Streaming bitrate is 1000000
[2026-04-20 08:26:34.171]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:34.183]: Info: 
[2026-04-20 08:26:34.183]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2026-04-20 08:26:34.183]: Info: 
[2026-04-20 08:26:34.183]: Info: Found H.264 encoder: h264_vulkan [vulkan]
[2026-04-20 08:26:34.183]: Info: Found HEVC encoder: hevc_vulkan [vulkan]
[2026-04-20 08:26:34.183]: Info: Found AV1 encoder: av1_vulkan [vulkan]
[2026-04-20 08:26:34.183]: Info: Executing [Desktop]
[2026-04-20 08:26:34.298]: Info: New streaming session started [active sessions: 1]

(sunshine:2): Gtk-CRITICAL **: 08:26:34.298: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[2026-04-20 08:26:34.299]: Warning: setpriority failed for nice -15: Permission denied
[2026-04-20 08:26:34.299]: Warning: setpriority failed for nice -10: Permission denied
[2026-04-20 08:26:34.299]: Warning: setpriority failed for nice -10: Permission denied

(sunshine:2): libnotify-WARNING **: 08:26:34.299: Running in confined mode, using Portal notifications. Some features and hints won't be supported
[2026-04-20 08:26:34.326]: Info: CLIENT CONNECTED
[2026-04-20 08:26:34.328]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:34.328]: Warning: setpriority failed for nice -10: Permission denied
[2026-04-20 08:26:34.352]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:34.352]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:34.352]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:34.352]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:34.352]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:34.352]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:34.352]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:34.352]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:34.352]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:34.353]: Info: [portalgrab] Found stream for display: 'DP-1' position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:34.355]: Info: Screencasting with XDG portal
[2026-04-20 08:26:34.355]: Info: [pipewire] Requested frame rate [60fps]
[2026-04-20 08:26:34.355]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:34.360]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:34.383]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:34.383]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:34.383]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:34.383]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:34.383]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:34.383]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:34.383]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:34.383]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:34.383]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:34.384]: Info: [pipewire] Streaming display 'nDP-1' from position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:34.385]: Info: [pipewire] Connected to pipewire version 1.6.2
[2026-04-20 08:26:34.387]: Info: [pipewire] Pipewire Error, id:2 seq:13 message: no more input formats
[2026-04-20 08:26:34.803]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2026-04-20 08:26:34.807]: Warning: setpriority failed for nice -15: Permission denied
[2026-04-20 08:26:34.807]: Warning: setpriority failed for nice -10: Permission denied
[2026-04-20 08:26:34.807]: Info: Opus initialized: 48 kHz, 2 channels, 512 kbps (total), LOWDELAY
[2026-04-20 08:26:35.892]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:35.892]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:35.892]: Info: Color depth: 8-bit
[2026-04-20 08:26:35.892]: Info: Color range: MPEG
[2026-04-20 08:26:35.892]: Warning: setpriority failed for nice -15: Permission denied
[2026-04-20 08:26:35.893]: Warning: [portalgrab] Negotiation failed, will retry without maxFramerate
[2026-04-20 08:26:35.918]: Info: Streaming bitrate is 14988000
[2026-04-20 08:26:35.919]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:35.919]: Info: Minimum FPS target set to ~30fps (33.3333ms)
[2026-04-20 08:26:35.935]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:35.960]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:35.960]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:35.960]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:35.960]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:35.960]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:35.960]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:35.960]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:35.961]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:35.961]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:35.962]: Info: [portalgrab] Found stream for display: 'DP-1' position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:35.963]: Info: Screencasting with XDG portal
[2026-04-20 08:26:35.963]: Info: [pipewire] Requested frame rate [60fps]
[2026-04-20 08:26:35.963]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:35.968]: Info: [portalgrab] Loaded portal restore token from disk
[2026-04-20 08:26:35.990]: Info: [wayland] Found display [wayland-0]
[2026-04-20 08:26:35.990]: Info: [wayland] Found interface: wl_output(3) version 4
[2026-04-20 08:26:35.990]: Info: [wayland] Found interface: zxdg_output_manager_v1(4) version 3
[2026-04-20 08:26:35.990]: Info: [wayland] Found interface: zwp_linux_dmabuf_v1(23) version 5
[2026-04-20 08:26:35.990]: Info: [wayland] Resolution: 2560x1440
[2026-04-20 08:26:35.990]: Info: [wayland] Offset: 0x0
[2026-04-20 08:26:35.990]: Info: [wayland] Logical size: 2560x1440
[2026-04-20 08:26:35.990]: Info: [wayland] Name: DP-1
[2026-04-20 08:26:35.990]: Info: [wayland] Found monitor: AOC 34"
[2026-04-20 08:26:35.991]: Info: [pipewire] Streaming display 'nDP-1' from position: 0x0 resolution: 2560x1440
[2026-04-20 08:26:35.993]: Info: [pipewire] Connected to pipewire version 1.6.2
[2026-04-20 08:26:35.994]: Info: [pipewire] Video format: 12
[2026-04-20 08:26:35.994]: Info: [pipewire] Size: 2560x1440
[2026-04-20 08:26:35.994]: Info: [pipewire] Framerate (from compositor): 0/1
[2026-04-20 08:26:35.994]: Info: [pipewire] Framerate (from compositor, max): 9431487/65536
[2026-04-20 08:26:35.994]: Info: [pipewire] using DMA-BUF buffers
[2026-04-20 08:26:35.994]: Info: [pipewire] Video format: 12
[2026-04-20 08:26:35.994]: Info: [pipewire] Size: 2560x1440
[2026-04-20 08:26:35.994]: Info: [pipewire] Framerate (from compositor): 0/1
[2026-04-20 08:26:35.994]: Info: [pipewire] Framerate (from compositor, max): 9431487/65536
[2026-04-20 08:26:35.994]: Info: [pipewire] using DMA-BUF buffers
[2026-04-20 08:26:36.013]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:36.013]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:36.013]: Info: Color depth: 8-bit
[2026-04-20 08:26:36.013]: Info: Color range: MPEG
[2026-04-20 08:26:36.036]: Info: Streaming bitrate is 14988000
[2026-04-20 08:26:36.037]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:36.037]: Info: Minimum FPS target set to ~30fps (33.3333ms)
[2026-04-20 08:26:36.312]: Error: vkCreateImage for DMA-BUF failed: -1000158000 (modifier=0x200000028a01f04, pitch=1139, offset=108)
[2026-04-20 08:26:36.312]: Error: Failed to import DMA-BUF
[2026-04-20 08:26:36.312]: Error: Could not convert image
[2026-04-20 08:26:36.319]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:36.319]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:36.319]: Info: Color depth: 8-bit
[2026-04-20 08:26:36.319]: Info: Color range: MPEG
[2026-04-20 08:26:36.343]: Info: Streaming bitrate is 14988000
[2026-04-20 08:26:36.344]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:36.344]: Info: Minimum FPS target set to ~30fps (33.3333ms)
[2026-04-20 08:26:36.486]: Error: vkCreateImage for DMA-BUF failed: -1000158000 (modifier=0x200000028a01f04, pitch=24, offset=688)
[2026-04-20 08:26:36.486]: Error: Failed to import DMA-BUF
[2026-04-20 08:26:36.486]: Error: Could not convert image
[2026-04-20 08:26:36.493]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:36.493]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:36.493]: Info: Color depth: 8-bit
[2026-04-20 08:26:36.493]: Info: Color range: MPEG
[2026-04-20 08:26:36.517]: Info: Streaming bitrate is 14988000
[2026-04-20 08:26:36.518]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:36.518]: Info: Minimum FPS target set to ~30fps (33.3333ms)
[2026-04-20 08:26:37.069]: Error: vkCreateImage for DMA-BUF failed: -1000158000 (modifier=0x200000028a01f04, pitch=24, offset=761)
[2026-04-20 08:26:37.069]: Error: Failed to import DMA-BUF
[2026-04-20 08:26:37.069]: Error: Could not convert image
[2026-04-20 08:26:37.071]: Info: Creating encoder [hevc_vulkan]
[2026-04-20 08:26:37.071]: Info: Color coding: SDR (Rec. 601)
[2026-04-20 08:26:37.071]: Info: Color depth: 8-bit
[2026-04-20 08:26:37.071]: Info: Color range: MPEG
[2026-04-20 08:26:37.095]: Info: Streaming bitrate is 14988000
[2026-04-20 08:26:37.096]: Info: Vulkan encode using GPU: AMD Radeon RX 7900 XT (RADV NAVI31)
[2026-04-20 08:26:37.096]: Info: Minimum FPS target set to ~30fps (33.3333ms)
[2026-04-20 08:26:37.097]: Error: vkCreateImage for DMA-BUF failed: -1000158000 (modifier=0x200000028a01f04, pitch=24, offset=772)
[2026-04-20 08:26:37.097]: Error: Failed to import DMA-BUF
[2026-04-20 08:26:37.097]: Error: Could not convert image
```

### Online logs

_No response_

### PR DESCRIPTION
**Pull request by neatnoise**
## Description

Fixed a crash on multi-GPU systems when Sunshine tries to detect which GPU to use for Vulkan encoding.

Fixed wlr capture picking the wrong GPU on multi-GPU systems, which caused failed imports and memory leaks.

Fixed Vulkan encoding failing after long streaming sessions on AMD GPUs. The compositor can add extra buffer planes for compression, and the encoder now correctly ignores them.

Removed Vulkan encoder support from wlr capture. The buffer formats (linear, non-linear) for various drivers/gpus break wlr screencopy. Vulkan encoding still works with KMS capture and portal.

### Issues Fixed or Closed

- Fixes #5018
- Fixes #5023
- Fixes #5034

## Type of Change

- [ ] **feat**: New feature (non-breaking change which adds functionality)
- [x] **fix**: Bug fix (non-breaking change which fixes an issue)
- [ ] **docs**: Documentation only changes
- [ ] **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semicolons, etc.)
- [ ] **refactor**: Code change that neither fixes a bug nor adds a feature
- [ ] **perf**: Code change that improves performance
- [ ] **test**: Adding missing tests or correcting existing tests
- [ ] **build**: Changes that affect the build system or external dependencies
- [ ] **ci**: Changes to CI configuration files and scripts
- [ ] **chore**: Other changes that don't modify src or test files
- [ ] **revert**: Reverts a previous commit
- [ ] **BREAKING CHANGE**: Introduces a breaking change (can be combined with any type above)

## Checklist

- [x] Code follows the style guidelines of this project
- [x] Code has been self-reviewed
- [x] Code has been commented, particularly in hard-to-understand areas
- [ ] Code docstring/documentation-blocks for new or existing methods/components have been added or updated
- [ ] Unit tests have been added or updated for any new or modified functionality

### AI Usage

- [ ] **None**: No AI tools were used in creating this PR
- [ ] **Light**: AI provided minor assistance (formatting, simple suggestions)
- [x] **Moderate**: AI helped with code generation or debugging specific parts
- [ ] **Heavy**: AI generated most or all of the code changes

### CODE REVIEW

File: src/platform/linux/vulkan_encode.cpp [hunk 1]
```diff
@@ -489,6 +489,8 @@ namespace vk {
       img_ci.usage = VK_IMAGE_USAGE_SAMPLED_BIT;
       img_ci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
 
+      BOOST_LOG(info) << "DMA-BUF import: "sv << sd.width << 'x' << sd.height << " fourcc=0x"sv << std::hex << sd.fourcc << " modifier=0x"sv << sd.modifier << std::dec << " planes="sv << drm_ci.drmFormatModifierPlaneCount << " pitch="sv << sd.pitches[0];
```
Comment (Kishi85) [inline src/platform/linux/vulkan_encode.cpp]: This should be set to debug or be removed as it's spamming the log while streaming.

Comment (neatnoise) [reply src/platform/linux/vulkan_encode.cpp]: Removed it, it was for debug, now it logs only in case of failure

**Comment by kabooHD** [comment]
Tested build-Linux-AppImage from the CI artifacts (commit 5d68c4b) against my original reproducer — dual RTX 5090, NixOS 25.11, Hyprland, NVIDIA 595.58.03 open driver, kernel 6.19.10.
Ran via appimage-run (and separately via steam-run — same result). used build app image from here: https://github.com/LizardByte/Sunshine/actions/runs/24646068696?pr=5030#artifacts
Two issues observed:

NVENC path fails immediately with Couldn't initialize EGL display: [00003001] (EGL_NOT_INITIALIZED). Likely a NixOS + AppImage runtime quirk around EGL exposure rather than your code.
Sunshine falls through to Vulkan encoder. h264_vulkan initializes, reports Streaming bitrate is 1000000, then segfaults before reaching the main loop.

Backtrace from the Vulkan segfault:
Stack trace of thread 4592:
#0  0x00007f8ab898f918 __strchrnul_evex (/nix/store/km4g87jxsqxvcq344ncyb8h1i6f3cqxh-glibc-2.40-218/lib/libc.so.6 + 0x18f918)
#1  0x00007f8ab886778e __printf_buffer (/nix/store/km4g87jxsqxvcq344ncyb8h1i6f3cqxh-glibc-2.40-218/lib/libc.so.6 + 0x6778e)
#2  0x00007f8ab888ead3 __vsnprintf_internal (/nix/store/km4g87jxsqxvcq344ncyb8h1i6f3cqxh-glibc-2.40-218/lib/libc.so.6 + 0x8ead3)
#3  0x00007f8ab95d3841 n/a (libvulkan.so.1 + 0x2e841)
#4  0x00007f8ab95ed5da vkPhysDevExtTermin95 (libvulkan.so.1 + 0x485da)
ELF object binary architecture: AMD x86-64
vsnprintf crashing mid-format call from the Vulkan loader iterating extension terminators — looks like a NULL string pointer being passed somewhere in device/extension name handling. I reproduced the same crash yesterday compiling the branch directly from source outside NixOS, so the ad-hoc build wasn't the cause.
Didn't get far enough to exercise the wlgrab multi-GPU fix from my original issue. Happy to retest when the Vulkan side is sorted out, or try a debug variant if you want more info from the core dump.
Full log attached 
[sunshine-pr5030-test.log](https://github.com/user-attachments/files/26893035/sunshine-pr5030-test.log)

**Comment by neatnoise** [comment]
@kabooHD added a fix for segfault

**Comment by kabooHD** [comment]
Thanks for the quick fix!  @ReenigneArcher can you please trigger CI again so I can grab a fresh build-Linux-AppImage artifact? Building the branch directly on NixOS turned out to be more trouble than it was worth, and the CI artifact from last round tested cleanly (up until the segfault they just patched).

**Comment by ReenigneArcher** [comment]
https://github.com/LizardByte/Sunshine/actions/runs/24665312160?pr=5030#artifacts

**Comment by kabooHD** [comment]
Confirmed the wlgrab multi-GPU fix works for the original #5023 scenario.
Tested CI artifact on dual RTX 5090 / NixOS 25.11 / Hyprland / NVIDIA 595.58.03 open driver, with no adapter_name set and no environment workarounds.
Can't fully exercise streaming on this system because appimage-run's sandbox isolates libEGL from /run/opengl-driver/lib, so NVENC and Vulkan both fail to init and Sunshine falls back to software encoding which can't sustain 1080p60 here. But the important part is the leak check:
During a Moonlight connection attempt (which failed on the encoder side):
GPU 0 VRAM: 292 MiB
GPU 1 VRAM: 2 MiB
FDs on /dev/dri/renderD128: 0
FDs on /dev/dri/renderD129: 0
Pre-fix, #5023 would have shown hundreds of FDs on renderD129 within seconds of connect and GPU 1 VRAM climbing into gigabytes via the failed dmabuf import retry loop. None of that happens now — the capture-side code correctly selected a render device (or failed cleanly without targeting the wrong one) even under the encoder-failure codepath.
I'll verify the full streaming path once this merges and lands in nixpkgs. Thanks for the fix.

(Please note: https://github.com/LizardByte/Sunshine/actions/runs/24665312160?pr=5030#artifacts didn't work for me 
Instead I used https://github.com/LizardByte/Sunshine/actions/runs/24696466510)

Thank you

**Comment by neatnoise** [comment]
@kabooHD , the build which worked for you it is correct auto GPU selection + revert of wlgrab vulkan support. The buffer formats (linear, non-linear) for various drivers/gpus break wlr screencopy so I reverted vulkan support in this PR unfortunately. I managed to work AMD GPU + wlgrab + vulkan scenario, but at the same time it broke Nvidia GPU + wlgrab + nvenc (from the users' reports).

@ReenigneArcher It can be TODO vulkan + wlgrab/wlr support I guess, if somebody is interested in adding it (specially who owns AMD and Nvidia GPU's to develop it). It seems to be tricky to support both. We have the commit history if it could help in the future (feat(linux): Add Vulkan video encoder (#4603))

**Comment by ReenigneArcher** [comment]
@netnoise fine with me. BTW, do you think this table should be updated to include Vulkan? https://github.com/LizardByte/Sunshine#-feature-compatibility

The intent is to track anything that varies between platforms or has incompatibilities in some cases. Can be a separate PR though.

This is probably good to go though, I see you got confirmation on 2 of the 3 issues.
